Repository NCI-Agency/anet, pull requests merged in 2018-11, with the labels that each got.

#1082 Fix print styles
  client/src/components/ResponsiveLayout.js
  client/src/index.css
Labels: bug

#1083 Use a new mosaic layout for insights and the daily rollup
  client/package.json
  client/src/HOC/LoaderHOC.js
  client/src/components/BarChart.css
  client/src/components/BarChart.js
  client/src/components/CancelledEngagementReports.js
  client/src/components/DailyRollupChart.js
  client/src/components/Fieldset.js
  client/src/components/FutureEngagementsByLocation.js
  client/src/components/HorizontalBarChart.js
  client/src/components/Leaflet.js
  client/src/components/MosaicLayout.css
  client/src/components/MosaicLayout.js
  client/src/components/Nav.js
  client/src/components/PendingApprovalReports.js
  client/src/components/ReportCollection.js
  client/src/components/ReportsByDayOfWeek.js
  client/src/components/ReportsByTask.js
  client/src/components/ReportsVisualisation.js
  client/src/components/ResponsiveLayout.js
  client/src/index.css
  client/src/pages/admin/MergePeople.js
  client/src/pages/insights/Show.js
  client/src/pages/rollup/Show.js
  client/yarn.lock
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteReportSearcher.java
Labels: enhancement

#1086 Change 'Org' label to 'Organization'
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/PositionTable.js
  client/src/pages/Search.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
Labels: enhancement

#1100 Fix error when going to daily rollup after searching on people by rank
  client/src/actions/index.js
  client/src/components/Nav.js
  client/src/components/Page.js
  client/src/pages/GraphiQL.js
  client/src/pages/Home.js
  client/src/pages/Search.js
  client/src/pages/admin/Index.js
  client/src/pages/insights/Show.js
  client/src/pages/reports/MyReports.js
  client/src/pages/rollup/Show.js
Labels: bug

#1103 Fix display of start date in advanced search
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/pages/rollup/Show.js
Labels: bug

#1073 Add python data science component for operational analysis analytics
  analytics/Pipfile
  analytics/Pipfile.lock
  analytics/README.md
  analytics/src/HelloAnet.py
Labels: enhancement

#1107 Don't put graph popover on top of advanced search
  client/src/components/MosaicLayout.css
  client/src/pages/rollup/Show.js
Labels: bug

#1116 Get label and placeholder for position code from the dictionary
  anet.yml
  client/src/pages/HopscotchTour.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#1097 Move exection of sql scripts from sql container into ANET application
  .travis.yml
  build.gradle
  docs/dev-setup.md
  examples/persistentContainerDemo/anet.yml
  examples/persistentContainerDemo/docker-compose.yml
  examples/persistentContainerDemo/insertBaseData.sql
  examples/simpleContainerDemo/docker-compose.yml
  insertBaseData.sql
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/DatabaseScriptCommand.java
Labels: debt

#1117 Fix typo that is preventing users that have not taken the tour from using ANET
  client/src/components/GuidedTour.js
Labels: bug

#1121 Update yarn.lock to latest. Replace uglify with terser
  client/config/webpack.prod.js
  client/yarn.lock
Labels: debt

#1118 Show warnings before submitting or approving report
  client/src/index.css
  client/src/models/Report.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
Labels: enhancement

#1123 Allow admins to set an inactive person back to active
  client/src/pages/people/Form.js
Labels: enhancement

#1125 Collect statistics for our data loaders
  src/main/java/mil/dds/anet/resources/GraphQLResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
Labels: enhancement

#1130 Add notes to objects
  client/package.json
  client/src/components/BlueprintOverrides.css
  client/src/components/Model.js
  client/src/components/MosaicLayout.css
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ResponsiveLayout.js
  client/src/models/AuthorizationGroup.js
  client/src/models/Comment.js
  client/src/models/Location.js
  client/src/models/Organization.js
  client/src/models/Person.js
  client/src/models/Position.js
  client/src/models/Report.js
  client/src/models/Tag.js
  client/src/models/Task.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Show.js
  client/yarn.lock
  insertBaseData.sql
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/beans/NoteRelatedObject.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/mappers/NoteMapper.java
  src/main/java/mil/dds/anet/database/mappers/NoteRelatedObjectMapper.java
  src/main/java/mil/dds/anet/resources/NoteResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/java/mil/dds/anet/views/AbstractAnetBean.java
  src/main/resources/migrations.xml
Labels: enhancement

#1131 Super users can change a person's status to INACTIVE
  client/src/pages/people/Form.js
Labels: bug

#1133 Fix and improve unassigned banner
  client/src/components/NoPositionBanner.js
  client/src/components/TopBar.js
Labels: bug

#1134 Remove container requirement from travis builds
  .travis.yml
Labels: debt
