Repository NCI-Agency/anet, pull requests merged in 2018-10, with the labels that each got.

#945 Update yarn.lock with integrity data
  client/yarn.lock
Labels: dependencies

#946 Show reports if saved search is not about a specific object type
  client/src/components/SavedSearchTable.js
Labels: bug

#951 Upgrade gradle to 4.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: debt

#651 Improve ANET Application layout
  client/package.json
  client/public/index.hbs
  client/src/components/CalendarButton.js
  client/src/components/Fieldset.js
  client/src/components/Header.js
  client/src/components/Nav.js
  client/src/components/NavWrap.js
  client/src/components/Page.js
  client/src/components/ReportSummary.js
  client/src/components/ResponsiveLayout.js
  client/src/components/TopBar.js
  client/src/index.css
  client/src/index.js
  client/src/pages/App.js
  client/src/pages/Routing.js
  client/src/pages/Search.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/insights/Show.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Form.js
  client/src/resources/anet-menu.png
  client/yarn.lock
Labels: feature

#970 NCI-Agency/anet#940: Principal organization fields are read-only for super-users
  client/src/pages/organizations/Form.js
Labels: enhancement

#984 Upgrade Dropwizard to 1.3.7
  build.gradle
Labels: debt

#978 NCI-Agency/anet#903: Change placeholder for first name field
  client/src/pages/people/Form.js
Labels: enhancement

#977 NCI-Agency/anet#519: Use separate labels for position type/permissons
  anet.yml
  client/src/models/Position.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#986 Add missing rank to Merge People Tool
  client/src/pages/admin/MergePeople.js
Labels: bug

#987 NCI-Agency/anet#940: Update test for super user permissions
  client/tests/e2e/permissions.js
Labels: debt

#989 Fix incomplete autosuggests
  client/src/components/Autocomplete.js
  client/src/components/SearchBar.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/organizations/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
  client/src/utils.js
Labels: bug

#990 Fix for missing keystrokes
  client/package.json
  client/src/components/Autocomplete.js
  client/yarn.lock
Labels: bug

#994 Fix report autosave to not create a new report each time
  client/src/pages/reports/Form.js
Labels: bug

#997 Specify an explicit mapId for the reports map
  client/src/pages/locations/Show.js
Labels: bug

#1016 Allow in-line images in HTML fields
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/utils/UtilsTest.java
Labels: enhancement

#1025 Improve use of position code
  client/src/models/Person.js
  client/src/pages/App.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPositionSearcher.java
Labels: enhancement

#795 Add coverage reports
  .travis.yml
  build.gradle
Labels: debt, preview

#1032 NCI-Agency/anet#1029: Correctly show sub-navigation in all cases
  client/src/components/SubNav.js
Labels: bug

#1030 GH-348 update
  client/src/pages/Search.js
  client/src/pages/reports/Show.js
Labels: bug, enhancement

#1028 Remove sonarcube and coverity from build
  .travis.yml
  README.md
  build.gradle
Labels: debt

#1051 Show position code and location in search results
  client/src/components/PositionTable.js
  client/src/pages/Search.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/tests/e2e/report.js
Labels: enhancement

#1052 NCI-Agency/anet#998: Also filter out empty positions from the history
  src/main/java/mil/dds/anet/beans/PersonPositionHistory.java
Labels: bug

#1070 Fix reports search for location
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteReportSearcher.java
Labels: bug
