Repository NCI-Agency/anet, pull requests merged in 2018-09, with the labels that each got.

#854 NCI-Agency/anet#853: Fix retrieval of approval steps for list of reports
  src/main/java/mil/dds/anet/database/OrganizationDao.java
Labels: bug

#866 Fix broken email sharing
  src/main/resources/emails/emailReport.ftl
Labels: bug

#868 Fix bug in init srcipt
  build.gradle
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: bug

#883 Make init command's admin user active
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: bug

#885 Simplify Gradle script.
  build.gradle
Labels: debt

#887 NCI-Agency/anet#853: (Only) quote tables/fields that contain capitals
  src/main/java/mil/dds/anet/database/OrganizationDao.java
Labels: enhancement

#892 Fix dependency of filters in advanced search
  client/src/components/AdvancedSearch.js
  client/src/components/SearchFilters.js
Labels: bug

#908 Make subnavigation for organization page content dependent
  client/src/components/Nav.js
  client/src/components/SubNav.js
  client/src/pages/App.js
  client/src/pages/Search.js
  client/src/pages/organizations/Show.js
Labels: enhancement

#913 Make end of tour date required for advisors
  client/src/components/FormField.js
  client/src/pages/people/Form.js
  client/tests/e2e/report.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/specs/createNewPerson.spec.js
  insertBaseData.sql
Labels: enhancement

#914 Fix error in create person form
  client/src/pages/people/Form.js
Labels: bug

#916 Fix warning on organization details page
  client/src/components/SubNav.js
Labels: bug

#938 Do not show no results found before search finished
  client/src/pages/Search.js
Labels: bug

#918 Add position history to person page
  client/src/pages/people/Show.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/PersonPositionHistory.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
Labels: enhancement

#939 Add rank filter to person advanced search
  client/src/components/SearchFilters.js
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqlitePersonSearcher.java
Labels: enhancement
