Repository NCI-Agency/anet, pull requests merged in 2018-12, with the labels that each got.

#1143 Fix intcore gql test
  src/test/resources/graphQLTests/intcore.gql
Labels: debt

#1166 NCI-Agency/anet#1078: Merge notes when merging people
  src/main/java/mil/dds/anet/database/PersonDao.java
Labels: bug

#1142 Add basic search based on a gazetteer to ANET
  anet.yml
  client/package.json
  client/src/components/Leaflet.js
  client/yarn.lock
  src/main/resources/anet-schema.yml
Labels: change in anet.yml, enhancement

#1168 Gh 1141 - Fix search
  client/src/pages/Search.js
Labels: bug

#1176 Gh 1175 - Fix issues with insights when navigating
  client/src/components/AdvisorReports/FilterableAdvisorReportsTable.js
  client/src/components/ReportsVisualisation.js
  client/src/pages/insights/Show.js
Labels: bug

#1185 Fix tests after dataloader improvements
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQLResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
Labels: bug

#1180 Use blueprint icons
  client/src/components/ConfirmDelete.js
  client/src/components/MosaicLayout.js
  client/src/components/RelatedObjectNotes.js
  client/src/resources/tasks.png
Labels: enhancement

#1205 Remove the ability of non-admin users to approve their own reports
  client/src/pages/reports/Show.js
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteReportSearcher.java
Labels: enhancement

#1206 Authors can no longer approve or reject their own reports
  client/src/pages/reports/Show.js
  client/tests/e2e/report.js
  insertBaseData.sql
  src/main/java/mil/dds/anet/resources/ReportResource.java
Labels: enhancement

#1222 Fix export showing only first page of search results
  client/src/pages/Search.js
Labels: bug
