Repository NCI-Agency/anet, pull requests merged in 2018-08, with the labels that each got.

#816 Simplify supplier code
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
Labels: debt

#817 Fix issues resulting from GraphQL upgrade
  client/src/components/SavedSearchTable.js
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/Comment.java
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/ReportPerson.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/lists/AnetBeanList.java
  src/main/java/mil/dds/anet/database/mappers/ApprovalActionMapper.java
  src/main/java/mil/dds/anet/database/mappers/ApprovalStepMapper.java
  src/main/java/mil/dds/anet/database/mappers/AuthorizationGroupMapper.java
  src/main/java/mil/dds/anet/database/mappers/CommentMapper.java
  src/main/java/mil/dds/anet/database/mappers/LocationMapper.java
  src/main/java/mil/dds/anet/database/mappers/OrganizationMapper.java
  src/main/java/mil/dds/anet/database/mappers/PersonMapper.java
  src/main/java/mil/dds/anet/database/mappers/PositionMapper.java
  src/main/java/mil/dds/anet/database/mappers/ReportMapper.java
  src/main/java/mil/dds/anet/database/mappers/ReportSensitiveInformationMapper.java
  src/main/java/mil/dds/anet/database/mappers/TagMapper.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/views/AbstractAnetBean.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/beans/ReportTest.java
  src/test/java/mil/dds/anet/test/beans/TaskTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: bug

#823 Add temporary height fix to make graphiql work in IE11
  client/src/pages/GraphiQL.js
Labels: bug

#825 Fix typo when setting default localSettings.gradle
  .travis.yml
  build.gradle
Labels: debt

#839 Add a sleep to the autocomplete page helper
  client/tests/util/test.js
Labels: bug

#845 NCI-Agency/anet#844: Fix display of location status
  client/src/pages/locations/Show.js
Labels: bug

#843 NCI-Agency/anet#819: Use props instead of state
  client/src/components/NavigationWarning.js
Labels: bug

#840 Add batching for Report.loadApprovalStatus()
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/ApprovalAction.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ApprovalActionDao.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/resources/ApprovalStepResource.java
  src/main/java/mil/dds/anet/resources/GraphQLResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: enhancement
