Repository NCI-Agency/anet, pull requests merged in 2019-11, with the labels that each got.

#2468 Bump JS dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2471 Add some extra fields to the Excel export for tasks/effort
  client/src/exportUtils.js
Labels: enhancement

#2472 Ignore coverage changes less than 0.2%
  .codecov.yml
Labels: debt

#2490 Bump @babel devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2491 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2492 Bump client dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2493 Reset total count while search is running
  client/src/components/ReportCalendar.js
  client/src/components/ReportMap.js
  client/src/components/ReportSummary.js
  client/src/components/ReportTable.js
  client/src/pages/Search.js
Labels: debt

#2518 Release drafter
  .github/release-drafter.yml
Labels: feature

#2553 Bump dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2555 Add several simulator improvements
  client/tests/sim/Simulator.js
  client/tests/sim/scenarios/buildup/lotsOfData.js
  client/tests/sim/simutils.js
  client/tests/sim/stories/LocationStories.js
  client/tests/sim/stories/NoteStories.js
  client/tests/sim/stories/ReportStories.js
Labels: debt

#2578 Bump dependencies
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, java, javascript
