Repository NCI-Agency/anet, pull requests merged in 2019-04, with the labels that each got.

#1536 Move Person email validation to the Yup schema
  client/src/models/Person.js
  client/src/pages/people/Form.js
Labels: bug, enhancement

#1538 Make form initially valid
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
Labels: enhancement

#1539 Remove uuid's from related objects in the Excel export
  src/main/java/mil/dds/anet/resources/GraphQLResource.java
Labels: enhancement

#1540 Super users can not edit principal orgs
  client/src/pages/organizations/Show.js
  client/tests/e2e/permissions.js
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
Labels: enhancement

#1498 NCI-Agency/anet#530: Add auto account deactivation and warnings
  anet.yml
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/emails/AccountDeactivationEmail.java
  src/main/java/mil/dds/anet/emails/AccountDeactivationWarningEmail.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/search/AbstractSearchBuilder.java
  src/main/java/mil/dds/anet/search/PersonSearchBuilder.java
  src/main/java/mil/dds/anet/search/ReportSearchBuilder.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteReportSearcher.java
  src/main/java/mil/dds/anet/threads/AccountDeactivationWorker.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/accountDeactivation.tflh
  src/main/resources/emails/deactivationWarning.tflh
Labels: enhancement

#1560 Use correct label for tasks in search
  anet.yml
  client/package.json
  client/src/actions/index.js
Labels: bug

#1562 Correct check if approval step is used in report
  client/src/pages/organizations/Form.js
Labels: bug

#1561 Restrict super user editing of organizations
  client/src/pages/organizations/Form.js
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
Labels: enhancement

#1565 Also retrieve responsible organization during task autocomplete
  client/src/models/Task.js
Labels: bug

#1577 Fix loading of autocomplete suggestions
  client/src/components/Autocomplete.js
Labels: bug

#1566 Make maxTextFieldLength configurable
  anet.yml
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/reports/Form.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/resources/anet-schema.yml
Labels: change in anet.yml, enhancement

#1600 Use object labels only for display purposes
  client/src/actions/index.js
  client/src/components/AdvancedSearch.js
  client/src/components/SearchBar.js
  client/src/components/SearchFilters.js
  client/src/pages/Search.js
  client/tests/e2e/report.js
Labels: bug

#1601 Show toast when approving or rejecting report
  client/src/pages/App.js
  client/src/pages/Search.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
Labels: bug

#1607 Fix some Checkstyle warnings
  config/google_checks.xml
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetCheckCommand.java
  src/main/java/mil/dds/anet/WaitForDbCommand.java
  src/main/java/mil/dds/anet/auth/UrlParamsAuthFilter.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/graphql/DateTimeMapper.java
  src/main/java/mil/dds/anet/graphql/GraphQlDateTimeType.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/LoggingResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractSearchBuilder.java
  src/main/java/mil/dds/anet/search/PersonSearchBuilder.java
  src/main/java/mil/dds/anet/search/ReportSearchBuilder.java
  src/main/java/mil/dds/anet/utils/ResponseUtils.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SavedSearchResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQLResponse.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlClient.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlData.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlHelper.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlResponse.java
Labels: debt

#1646 fix pagination and resuts layout in FF and IE
  client/src/pages/Search.js
Labels: bug

#1649 Change redux storage to session storage
  client/src/reducers/persistReducer.js
Labels: bug

#1652 Use configured quarantine period instead of hard-coded value
  client/src/pages/reports/Show.js
Labels: bug

#1635 Add optional time to reports.engagementDate and add reports.duration
  anet.yml
  client/src/components/BlueprintOverrides.css
  client/src/components/CustomDateInput.js
  client/src/components/FutureEngagementsByLocation.js
  client/src/components/ReportCollection.js
  client/src/components/ReportSummary.js
  client/src/components/ReportTable.js
  client/src/components/ReportWorkflow.js
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/index.css
  client/src/models/Report.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/report.js
  client/tests/sim/stories/ReportStories.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/ReportMapper.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/reportRejection.ftlh
  src/main/resources/emails/rollup.ftlh
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/beans/ReportTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/resources/graphQLTests/intcore.gql
  src/test/resources/graphQLTests/orgShow.gql
  src/test/resources/graphQLTests/person.gql
  src/test/resources/graphQLTests/report.gql
  src/test/resources/graphQLTests/search.gql
  src/test/resources/testJson/reports/test.json
Labels: enhancement

#1653 Fix date conversion for Excel export
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
Labels: bug

#1598 nci-agency/anet#37: Add descriptions to rank dropdown
  anet.yml
  client/src/components/SearchFilters.js
  client/src/pages/people/Form.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/resources/anet-schema.yml
Labels: enhancement, priority

#1665 Fix some eslint warnings
  client/package.json
  client/src/components/CancelledEngagementReports.js
  client/src/components/CreateButton.js
  client/src/components/CustomDateInput.js
  client/src/components/MosaicLayout.js
  client/src/components/PendingApprovalReports.js
  client/src/components/PositionTable.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/ReportWorkflow.js
  client/src/components/ReportsVisualisation.js
  client/src/components/TaskTable.js
  client/src/models/Position.js
  client/src/pages/Home.js
  client/src/pages/Search.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/insights/Show.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Show.js
  client/src/pages/rollup/Show.js
  client/tests/e2e/permissions.js
  client/tests/sim/stories/OrganizationStories.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/ReportStories.js
  client/tests/util/test.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/rollup.page.js
Labels: debt

#1671 GH-1668 fix validation message not showing end of tour date
  client/src/components/Model.js
  client/src/pages/people/Form.js
Labels: bug
