Repository NCI-Agency/anet, pull requests merged in 2019-10, with the labels that each got.

#2266 Upgrade Gradle from 5.5 to 5.6.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: debt

#2267 Fix error reporting for FieldArray elements
  client/src/components/FieldHelper.js
  client/src/models/Organization.js
Labels: bug

#2268 Update browser tests
  client/src/HOC/LoaderHOC.css
  client/src/HOC/LoaderHOC.js
  client/src/components/Page.js
  client/src/index.css
  client/src/pages/Home.js
  client/tests/e2e/report.js
  client/tests/util/test.js
  client/tests/webdriver/pages/page.js
  client/tests/webdriver/specs/printRollup.spec.js
Labels: bug, debt

#2264 Use react router dom hooks
  client/package.json
  client/src/components/AdvancedSearch.js
  client/src/components/CreateButton.js
  client/src/components/GuidedTour.js
  client/src/components/LinkTo.js
  client/src/components/Messages.js
  client/src/components/Nav.js
  client/src/components/NavigationWarning.js
  client/src/components/Page.js
  client/src/components/ReportCalendar.js
  client/src/components/ResponsiveLayout.js
  client/src/components/SearchBar.js
  client/src/components/TopBar.js
  client/src/pages/App.js
  client/src/pages/Home.js
  client/src/pages/PageMissing.js
  client/src/pages/Search.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/dashboards/DecisivesDashboard.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/insights/Show.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/src/pages/onboarding/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/New.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/New.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/New.js
  client/src/pages/tasks/Show.js
  client/yarn.lock
Labels: debt

#2292 Bump Dropwizard
  build.gradle
Labels: dependencies

#2294 Bump build dependencies as well as apollo's react-hooks
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2295 Fix search with date filter of type LAST
  client/src/dateUtils.js
Labels: bug

#2297 Update search on date filters
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/dateUtils.js
Labels: enhancement

#2299 Bump react from 16.9.0 to 16.10.2
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2301 Fix error in emailRollup GraphQL request
  client/src/pages/rollup/Show.js
Labels: bug

#2302 Fix merge error in minimal report workflow
  client/src/pages/reports/Minimal.js
Labels: bug

#2308 Bump @blueprintjs dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2303 Fix relative date filters in saved searches
  client/src/dateUtils.js
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
Labels: bug

#2311 Free batching resources
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
Labels: debt

#2316 Only retrieve fields needed for the report map
  client/src/components/ReportMap.js
Labels: debt

#2319 Only re-request data if the report calendar parameters have changed
  client/src/components/Page.js
  client/src/components/ReportCalendar.js
Labels: debt

#2341 Bump Javascript dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2320 Change super user permissions for position editing
  client/src/components/PositionTable.js
  client/src/pages/Search.js
  client/tests/e2e/permissions.js
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: enhancement

#2343 Minor touchups
  client/config/webpack.common.js
  client/package.json
  client/src/components/AssignPersonModal.js
  client/src/components/ReportTable.js
  client/src/components/advancedSearch/SelectSearchFilter.js
  client/src/pages/admin/AuthorizationGroupTable.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/organizations/Approvals.js
  client/src/pages/organizations/Form.js
  client/src/pages/tasks/Form.js
  client/yarn.lock
  src/main/java/mil/dds/anet/database/EmailDao.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
Labels: debt

#2345 Completely revert e48f1351f6a0ebdc723e666f6e66f08f2349cebc
  client/yarn.lock
Labels: dependencies, javascript

#2346 Use the more compatible getBoundingClientRect() instead of clientWidth and clientHeight
  client/src/components/BarChart.js
  client/src/components/DailyRollupChart.js
  client/src/components/HorizontalBarChart.js
  client/src/components/graphs/OrganizationalChart.js
Labels: bug, debt

#2350 Fix tests
  client/tests/e2e/permissions.js
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: bug

#2348 Try to avoid deadlocks when checking authorization
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
Labels: bug

#2372 Bump js dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2373 Bump powermock dependency
  build.gradle
Labels: dependencies, java

#2374 Fix save of richtexteditor fields
  client/src/components/RichTextEditor.js
Labels: bug

#2375 Do not display organization related tiles on home for new users
  client/package.json
  client/platform/web-dev/api.js
  client/src/components/AdvisorReports/FilterableAdvisorReportsTable.js
  client/src/components/AvatarComponent.js
  client/src/components/AvatarDisplayComponent.js
  client/src/pages/Home.js
Labels: bug

#2377 Fix reset of search text when navigating
  client/src/components/SearchBar.js
Labels: bug

#2260 Improve simulator
  client/package.json
  client/tests/sim/Scenario.js
  client/tests/sim/Simulator.js
  client/tests/sim/scenarios/buildup/lotsOfData.js
  client/tests/sim/scenarios/buildup/oldScenario.js
  client/tests/sim/scenarios/scenarios.js
  client/tests/sim/scenarios/stories/storySim.js
  client/tests/sim/scenarios/users/userTypes.js
  client/tests/sim/simutils.js
  client/tests/sim/stories/OrganizationStories.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/ReportStories.js
  client/tests/sim/stories/afghanFirstNames.js
  client/yarn.lock
Labels: debt

#2315 Add "has biography" people search filter
  build.gradle
  client/src/components/SearchFilters.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/MaintenanceCommand.java
  src/main/java/mil/dds/anet/WaitForDbCommand.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
Labels: enhancement

#2406 Ignore coverage changes less than .1%
  .codecov.yml
Labels: debt

#2407 No longer run FutureEngagementWorker every minute in development
  src/main/java/mil/dds/anet/AnetApplication.java
Labels: debt

#2405 Fix error in emailReport GraphQL request
  client/src/pages/reports/Show.js
Labels: bug

#2437 Bump dropwizard from 1.3.15 to 1.3.16
  build.gradle
Labels: dependencies, java

#2438 Bump react from 16.10.2 to 16.11.0
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2440 Bump Apache POI from 4.1.0 to 4.1.1
  build.gradle
Labels: dependencies, java

#2441 Bump @storybook from 5.2.4 to 5.2.5
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2379 Update MS SQL Server to 2017 CU17
  docker/anet-mssql-linux/Dockerfile
  docker/anet-mssql-linux/README.md
Labels: debt

#2376 Make transactions more finely grained
  src/main/java/mil/dds/anet/database/AdminDao.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/EmailDao.java
  src/main/java/mil/dds/anet/database/ForeignKeyBatcher.java
  src/main/java/mil/dds/anet/database/IdBatcher.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlSearchQueryBuilder.java
Labels: debt

#2448 Fix some eslint warnings
  client/package.json
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/components/LinkTo.js
  client/src/components/ReportSummary.js
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
Labels: debt

#2449 Fix location marker in edit form
  client/src/pages/locations/Form.js
Labels: bug

#2446 Fix daily rollup cutoff date
  client/src/components/ReportCalendar.js
  client/src/components/ReportTable.js
  client/src/pages/rollup/Show.js
Labels: bug
