Repository NCI-Agency/anet, pull requests merged in 2019-05, with the labels that each got.

#1670 Add assessment of task project status
  client/src/components/FieldHelper.js
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ResponsiveLayout.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
  insertBaseData.sql
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/mappers/NoteMapper.java
  src/main/resources/migrations.xml
Labels: enhancement

#1701 Close advanced search on click outside overlay
  client/src/components/CustomDateInput.js
  client/src/components/SearchBar.js
Labels: enhancement

#1720 Replace getAll GraphQL query with search
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/advancedSearch/OrganizationFilter.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/Home.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Form.js
  client/tests/sim/Simulator.js
  client/tests/sim/stories/OrganizationStories.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/IAnetDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TagResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSearcher.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/resources/graphQLTests/person-all-paged.gql
  src/test/resources/graphQLTests/person-all.gql
  src/test/resources/graphQLTests/reportsAll.gql
  src/test/resources/graphQLTests/tagsAll.gql
Labels: debt

#1702 nci-agency/anet#1597: Do not send emails to addresses not whitelisted as active
  anet.yml
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/resources/anet-schema.yml
Labels: change in anet.yml, enhancement

#1739 Move Mosaic Layout description to navbar
  client/src/components/BlueprintOverrides.css
  client/src/components/MosaicLayout.css
  client/src/components/MosaicLayout.js
  client/src/index.css
Labels: enhancement

#1755 NCI-Agency/anet#379: Make sim cycle and running time configurable
  client/tests/sim/Simulator.js
Labels: debt

#1756 GraphQL search updates
  client/src/components/ReportsVisualisation.js
  client/src/models/Person.js
  client/src/pages/App.js
  client/src/pages/Help.js
  client/src/pages/Home.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/rollup/Show.js
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/Comment.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/PersonPositionHistory.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/ReportAction.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/search/AbstractSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/AuthorizationGroupSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/ISearchQuery.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/SavedSearch.java
  src/main/java/mil/dds/anet/beans/search/TagSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/threads/AccountDeactivationWorker.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/threads/ReportPublicationWorker.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/views/ForeignKeyFetcher.java
  src/main/java/mil/dds/anet/views/UuidFetcher.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/resources/graphQLTests/appQuery.gql
  src/test/resources/graphQLTests/intcore.gql
  src/test/resources/graphQLTests/orgShow.gql
  src/test/resources/graphQLTests/person-all.gql
  src/test/resources/graphQLTests/person.gql
  src/test/resources/graphQLTests/reportsAll.gql
  src/test/resources/graphQLTests/search.gql
  src/test/resources/graphQLTests/tagsAll.gql
Labels: debt, feature

#1576 Verify end of tour date not in past
  client/src/models/Person.js
  client/src/pages/people/Form.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/onboard.page.js
  client/tests/webdriver/pages/page.js
  client/tests/webdriver/specs/createNewPerson.spec.js
  client/tests/webdriver/specs/onboardNewUser.spec.js
Labels: enhancement

#1727 Fix warning about duration field in report form
  client/src/components/FieldHelper.js
Labels: debt

#1779 Make sure ResultIterable is closed, freeing up resources
  src/main/java/mil/dds/anet/database/ForeignKeyBatcher.java
  src/main/java/mil/dds/anet/database/IdBatcher.java
Labels: bug
