Repository NCI-Agency/anet, pull requests merged in 2019-01, with the labels that each got.

#1236 Escape HTML in FreeMarker templates
  src/main/java/mil/dds/anet/emails/ApprovalNeededEmail.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/emails/FutureEngagementUpdated.java
  src/main/java/mil/dds/anet/emails/NewReportCommentEmail.java
  src/main/java/mil/dds/anet/emails/ReportEditedEmail.java
  src/main/java/mil/dds/anet/emails/ReportEmail.java
  src/main/java/mil/dds/anet/emails/ReportRejectionEmail.java
  src/main/java/mil/dds/anet/emails/ReportReleasedEmail.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/futureEngagementUpdated.ftlh
  src/main/resources/emails/newReportComment.ftlh
  src/main/resources/emails/reportEdited.ftlh
  src/main/resources/emails/reportRejection.ftlh
  src/main/resources/emails/reportReleased.ftlh
  src/main/resources/emails/rollup.ftlh
  src/main/resources/emails/test.ftlh
Labels: bug, enhancement

#1237 Extract date formats to dictionary
  anet.yml
  client/package.json
  client/src/components/BlueprintOverrides.css
  client/src/components/CalendarButton.js
  client/src/components/CustomDateInput.js
  client/src/components/FutureEngagementsByLocation.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ReportApprovals.js
  client/src/components/ReportCollection.js
  client/src/components/ReportSummary.js
  client/src/components/ReportTable.js
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/dateUtils.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/report.js
  client/tests/util/test.js
  client/yarn.lock
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/resources/GraphQLResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/reportRejection.ftlh
  src/main/resources/emails/rollup.ftlh
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: enhancement

#1239 Replace react-scrollspy with react-scroll everywhere
  client/package.json
  client/src/components/Nav.js
  client/src/components/ResponsiveLayout.js
  client/src/pages/Search.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/MyReports.js
  client/yarn.lock
Labels: debt

#1238 Replace "reject" with "request changes"
  client/src/components/ReportApprovals.js
  client/src/components/ReportSummary.js
  client/src/components/advancedSearch/ReportStateSearch.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  docs/User_Workflows_and_Documentation.md
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/reportRejection.ftlh
Labels: enhancement

#1253 Enable a browser page refresh to keep the current state
  client/package.json
  client/src/components/AdvancedSearch.js
  client/src/index.js
  client/src/store.js
  client/yarn.lock
Labels: enhancement

#1266 GH-1135 Fix nav overlay position in Safari
  client/src/components/ResponsiveLayout.js
  client/src/index.css
Labels: bug

#1294 Change "All EFs / AOs" to "Advisor Organizations"
  anet.yml
  docs/INSTALL.md
  docs/User_Workflows_and_Documentation.md
  docs/anet.yml.production.template
  src/main/resources/anet-schema.yml
Labels: enhancement

#1295 Show only the organization's shortName for a task
  client/src/models/Organization.js
  client/src/pages/organizations/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/tasks/Show.js
Labels: enhancement

#1296 Have rollup run from midnight to midnight
  client/src/components/BlueprintOverrides.css
  client/src/components/DailyRollupChart.js
  client/src/pages/rollup/Show.js
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/resources/emails/rollup.ftlh
Labels: enhancement

#1293 Reset search filter when clicking on ANET logo
  client/src/components/Header.js
Labels: enhancement

#1285 Change how report text is shown
  anet.yml
  build.gradle
  client/src/components/MultiSelector.js
  client/src/components/ReportSummary.js
  client/src/components/SearchFilters.js
  client/src/models/Report.js
  client/src/pages/HopscotchTour.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/tests/e2e/position.js
  client/tests/e2e/report.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/rollup.ftlh
Labels: enhancement

#1297 Add model-specific icon to LinkTo links
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/components/LinkTo.js
  client/src/components/Model.js
  client/src/components/Nav.js
  client/src/components/PositionTable.js
  client/src/components/ReportCollection.js
  client/src/components/SecurityBanner.js
  client/src/models/Location.js
  client/src/models/Organization.js
  client/src/models/Person.js
  client/src/models/Position.js
  client/src/models/Report.js
  client/src/models/Task.js
  client/src/pages/App.js
  client/src/pages/Help.js
  client/src/pages/Search.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/AttendeesTable.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Form.js
Labels: enhancement
