Repository NCI-Agency/anet, pull requests merged in 2019-03, with the labels that each got.

#1265 Gh 18 redux
  client/package.json
  client/src/actions/index.js
  client/src/components/AdvancedSearch.js
  client/src/components/Header.js
  client/src/components/Nav.js
  client/src/components/Page.js
  client/src/components/SearchBar.js
  client/src/components/TopBar.js
  client/src/constants/ActionTypes.js
  client/src/constants/index.js
  client/src/index.js
  client/src/pages/Search.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/MyReports.js
  client/src/reducers/index.js
  client/src/reducers/pagination.js
  client/src/reducers/persistReducer.js
  client/src/store/configureStore.js
  client/tests/actions/index.test.js
  client/tests/reducers/pagination.test.js
  client/yarn.lock
Labels: enhancement

#1410 Run client-side tests on BrowserStack when building on Travis CI
  .travis.yml
  CONTRIBUTING.md
  build.gradle
  client/config/browserstack.config.js
  client/config/wdio.config.js
  client/package.json
  client/tests/e2e/position.js
  client/tests/e2e/report.js
  client/tests/util/test.js
  client/yarn.lock
  docs/BUILD.md
  docs/dev-setup.md
  docs/frontend-overview.md
Labels: debt

#1423 NCI-Agency/anet#912: Enforce assigning a rank when saving a principal
  client/src/models/Person.js
Labels: enhancement

#1424 Upgrade to Babel 7
  client/config/wdio.config.js
  client/package.json
  client/tests/util/test.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/editPosition.page.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/rollup.page.js
  client/tests/webdriver/specs/createAuthorizationGroup.spec.js
  client/tests/webdriver/specs/createNewPerson.spec.js
  client/tests/webdriver/specs/editPosition.spec.js
  client/tests/webdriver/specs/printRollup.spec.js
  client/yarn.lock
Labels: debt

#1432 NCI-Agency/anet#1425: Add datetime formatting including time for emails
  anet.yml
  client/src/components/ReportApprovals.js
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/emailReport.ftlh
Labels: bug, enhancement

#1428 Gh 1426 fix email errors for daily rollup
  src/main/java/mil/dds/anet/emails/AnetEmailAction.java
  src/main/java/mil/dds/anet/emails/ApprovalNeededEmail.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/emails/FutureEngagementUpdated.java
  src/main/java/mil/dds/anet/emails/NewReportCommentEmail.java
  src/main/java/mil/dds/anet/emails/ReportEditedEmail.java
  src/main/java/mil/dds/anet/emails/ReportEmail.java
  src/main/java/mil/dds/anet/emails/ReportRejectionEmail.java
  src/main/java/mil/dds/anet/emails/ReportReleasedEmail.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: bug

#1433 Run local Selenium e2e tests in HeadlessChrome
  client/tests/e2e/home.js
  client/tests/e2e/permissions.js
  client/tests/e2e/position.js
  client/tests/e2e/report.js
  client/tests/util/test.js
Labels: debt

#1409 NCI-Agency/anet#332: Add approval step popup when trying to delete it
  client/src/pages/organizations/Form.js
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
Labels: enhancement

#1435 Refactor inserts, updates and deletes
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/IAnetDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/SavedSearchResource.java
  src/main/java/mil/dds/anet/threads/ReportPublicationWorker.java
Labels: debt, preview

#1458 nci-agency/anet#1457: Do not clear tasks when saving cancelled reports
  client/src/pages/reports/Form.js
Labels: bug

#1459 Try fix for https://github.com/eclipse/jetty.project/issues/2205
  build.gradle
  src/main/java/org/eclipse/jetty/io/ManagedSelector.java
Labels: bug

#1464 nci-agency/anet#1463: Temporarily disable insights for anyone but admins
  client/src/components/Nav.js
Labels: bug

#1462 Prevent loops in the organization and task hierarchies
  client/src/pages/rollup/Show.js
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/search/mssql/MssqlOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlTaskSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteTaskSearcher.java
  src/main/java/mil/dds/anet/utils/Utils.java
Labels: bug, enhancement

#1460 NCI-Agency/anet#1177: Assign reports to primary advisor’s original org
  src/main/java/mil/dds/anet/beans/Report.java
Labels: enhancement

#1466 Log report deletions in the audit logger
  src/main/java/mil/dds/anet/resources/ReportResource.java
Labels: enhancement

#1467 Make AuthUtils::isAdmin work for users without position
  src/main/java/mil/dds/anet/utils/AuthUtils.java
Labels: bug

#1469 Introduce guicey-jdbi3
  build.gradle
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/database/AdminDao.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/EmailDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/StatementLogger.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/database/mappers/ForeignKeyMapper.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractSearcherBase.java
  src/main/java/mil/dds/anet/search/IAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/ILocationSearcher.java
  src/main/java/mil/dds/anet/search/IOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/IPersonSearcher.java
  src/main/java/mil/dds/anet/search/IPositionSearcher.java
  src/main/java/mil/dds/anet/search/IReportSearcher.java
  src/main/java/mil/dds/anet/search/ITagSearcher.java
  src/main/java/mil/dds/anet/search/ITaskSearcher.java
  src/main/java/mil/dds/anet/search/Searcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlLocationSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPositionSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlTagSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlTaskSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteLocationSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqlitePersonSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqlitePositionSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteReportSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteTagSearcher.java
  src/main/java/mil/dds/anet/search/sqlite/SqliteTaskSearcher.java
  src/main/java/mil/dds/anet/threads/ReportPublicationWorker.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
Labels: enhancement

#1470 Remove all traces of the obsolete old API calls
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/GraphQLResource.java
  src/main/java/mil/dds/anet/resources/HomeResource.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/NoteResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/SavedSearchResource.java
  src/main/java/mil/dds/anet/resources/TagResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
Labels: debt

#1492 Prevent hanging requests
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/ForeignKeyBatcher.java
  src/main/java/mil/dds/anet/database/IdBatcher.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/threads/ReportPublicationWorker.java
Labels: bug

#1493 Make sure reportSensitiveInformation is not null after autoSave
  client/src/pages/reports/Form.js
Labels: bug

#1495 Make sure isSubmitting is reset in case of error
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/pages/Search.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/MyReports.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Form.js
Labels: bug

#1499 Add 'Availability of Interpreter(s)' as a new cancellation reason
  client/src/components/advancedSearch/ReportStateSearch.js
  client/src/models/Report.js
  client/src/pages/reports/Form.js
  src/main/java/mil/dds/anet/beans/Report.java
Labels: enhancement
