Repository NCI-Agency/anet, pull requests merged in 2019-06, with the labels that each got.

#1823 Bump dropwizard from 1.3.11 to 1.3.12
  build.gradle
Labels: dependencies, java

#1824 Bump autoprefixer, webpack, babel and eslint to the latest
  client/yarn.lock
Labels: dependencies, javascript

#1826 Bump spqr from 0.9.9 to 0.10.0
  build.gradle
  src/main/java/mil/dds/anet/graphql/DateTimeMapper.java
  src/main/java/mil/dds/anet/graphql/GraphQlDateTimeType.java
Labels: dependencies, java

#1825 Bump wdio and storybook to the latest
  client/yarn.lock
Labels: dependencies, javascript

#1831 Bump wdio and storybook to the latest
  client/yarn.lock
Labels: dependencies, javascript

#1836 Bump webdriverio dependencies
  client/yarn.lock
Labels: dependencies, javascript

#1851 Bump react-router-dom from 4.3.1 to 5.0.1
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1875 nci-agency/anet#1874: Remove unneeded dependency
  client/package.json
  client/yarn.lock
Labels: dependencies

#1902 Pick the correct tag if there are multiple matches
  client/src/components/ReportTags.js
Labels: bug

#1904 Explicitly set sorting by name (ascending) to reinstate pre-SOUNDEX search behaviour
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
Labels: bug

#1915 Make React refs more strict
  client/src/components/BarChart.js
  client/src/components/CustomDateInput.js
  client/src/components/DailyRollupChart.js
  client/src/components/HorizontalBarChart.js
  client/src/components/SearchBar.js
  client/src/components/TriggerableConfirm.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/people/Form.js
Labels: debt
