Repository NCI-Agency/anet, pull requests merged in 2019-07, with the labels that each got.

#1921 Upgrade graphql-cli, graphiql and graphql
  client/package.json
  client/yarn.lock
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Task.java
Labels: debt

#1920 Add a configurable assets bundle
  anet.yml
  build.gradle
  docs/INSTALL.md
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
Labels: debt

#1923 Upgrade Gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: debt

#1918 Add NVG and KML output
  client/src/pages/Search.js
  docs/INSTALL.md
  src/main/java/mil/dds/anet/graphql/OutputTransformers/JsonToXlsxTransformer.java
  src/main/java/mil/dds/anet/graphql/OutputTransformers/JsonToXmlTransformer.java
  src/main/java/mil/dds/anet/graphql/OutputTransformers/XsltXmlTransformer.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/resources/assets/img/anet-circle.png
  src/main/resources/stylesheets/kml.xslt
  src/main/resources/stylesheets/nvg.xslt
Labels: feature

#1892 Add reports calendar view
  client/package.json
  client/src/actions/index.js
  client/src/components/Calendar.css
  client/src/components/Calendar.js
  client/src/components/CancelledEngagementReports.js
  client/src/components/FutureEngagementsByLocation.js
  client/src/components/Page.js
  client/src/components/PendingApprovalReports.js
  client/src/components/ReportCollection.js
  client/src/components/ReportCollectionContainer.js
  client/src/components/ReportsByDayOfWeek.js
  client/src/components/ReportsByTask.js
  client/src/components/ReportsVisualisation.js
  client/src/components/SavedSearchTable.js
  client/src/graphqlapi.js
  client/src/index.css
  client/src/pages/Search.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Show.js
  client/src/pages/reports/MyReports.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Show.js
  client/src/reducers/pagination.js
  client/tests/actions/index.test.js
  client/tests/e2e/report.js
  client/tests/reducers/pagination.test.js
  client/yarn.lock
Labels: feature

#1494 Dashboards
  anet.yml
  client/config/webpack.client.dev.js
  client/src/components/FieldHelper.js
  client/src/components/Kanban.js
  client/src/components/Nav.js
  client/src/components/SearchFilters.js
  client/src/components/graphs/Pie.js
  client/src/components/graphs/SVGCanvas.js
  client/src/models/Task.js
  client/src/pages/Routing.js
  client/src/pages/dashboards/DecisivesDashboard.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  data/dashboards/dashboard0.json
  data/dashboards/dashboard1.json
  data/dashboards/decisives.json
  docs/INSTALL.md
  docs/anet.yml.production.template
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
Labels: feature

#1948 Fix search
  client/src/components/Calendar.js
  client/src/components/Kanban.js
  client/src/components/Page.js
  client/src/components/ReportCollection.js
  client/src/components/ReportCollectionContainer.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/GraphiQL.js
  client/src/pages/Search.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/MyReports.js
  src/main/java/mil/dds/anet/emails/AccountDeactivationEmail.java
  src/main/java/mil/dds/anet/emails/AccountDeactivationWarningEmail.java
  src/main/resources/emails/accountDeactivation.ftlh
  src/main/resources/emails/deactivationWarning.ftlh
Labels: bug

#1956 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1957 Bump some babel devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1960 Bump @fullcalendar dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1955 Fix text in editor being duplicated
  client/src/components/RichTextEditor.js
Labels: bug

#1961 Bump some eslint devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1962 Address some Checkstyle warnings
  config/eclipse-java-google-style.xml
  config/google_checks.xml
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/database/AdminDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/graphql/outputtransformers/JsonToXlsxTransformer.java
  src/main/java/mil/dds/anet/graphql/outputtransformers/JsonToXmlTransformer.java
  src/main/java/mil/dds/anet/graphql/outputtransformers/XsltXmlTransformer.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: debt, java

#2005 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1977 Honour Liskov substitution principle in equals()
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/Comment.java
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/ReportAction.java
  src/main/java/mil/dds/anet/beans/ReportPerson.java
  src/main/java/mil/dds/anet/beans/ReportSensitiveInformation.java
  src/main/java/mil/dds/anet/beans/Tag.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/search/SavedSearch.java
Labels: debt, java

#2007 Bump some @babel devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2029 Bump dropwizard from 1.3.12 to 1.3.13
  build.gradle
Labels: dependencies, java

#2030 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2031 Use the local timezone on BrowserStack
  client/config/browserstack.config.js
  client/package.json
  client/tests/e2e/report.js
  client/yarn.lock
Labels: debt

#2008 Add indexes for all foreign keys and columns used in ORDER BY clauses
  anet.yml
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/utils/AnetDbLogger.java
  src/main/resources/migrations.xml
Labels: debt

#2033 Change the default view for showing report collections
  client/src/components/CancelledEngagementReports.js
  client/src/components/ReportCollection.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Show.js
Labels: enhancement

#1852 Add profile pictures for people
  anet.yml
  build.gradle
  client/package.json
  client/src/components/AvatarComponent.js
  client/src/components/AvatarDisplayComponent.js
  client/src/components/AvatarEditModal.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/models/Person.js
  client/src/pages/App.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/reports/AttendeesTable.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/resources/default_avatar.svg
  client/tests/e2e/report.js
  client/yarn.lock
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/mappers/PersonMapper.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/resources/assets/default_avatar.png
Labels: feature

#1973 GH-1811 editor add links
  client/package.json
  client/src/components/Portal.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RichTextEditor.css
  client/src/components/RichTextEditor.js
  client/src/components/Tooltip.css
  client/src/components/Tooltip.js
  client/src/components/editor/Icon.css
  client/src/components/editor/Icon.js
  client/src/components/editor/ImageBlock.js
  client/src/components/editor/ImageSource.js
  client/src/components/editor/Link.js
  client/src/components/editor/LinkSource.css
  client/src/components/editor/LinkSource.js
  client/src/components/editor/MediaBlock.js
  client/src/components/editor/TooltipEntity.css
  client/src/components/editor/TooltipEntity.js
  client/src/components/editor/plugins/linkifyPlugin.js
  client/src/components/editor/plugins/newlinePlugin.js
  client/src/components/editor/utils/createEntity.js
  client/src/pages/people/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
  client/tests/e2e/permissions.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/yarn.lock
Labels: feature

#2054 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2053 Address repeated loadData calls by keeping a reference count during page render
  client/src/components/Page.js
Labels: debt

#2055 Fix intermittent "yarn run test-jest" failures
  client/package.json
  client/platform/node/api.js
Labels: debt
