Repository NCI-Agency/anet, pull requests merged in 2019-08, with the labels that each got.

#2077 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2078 Bump some webpack devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2076 Bump mssql-jdbc from 7.2.2.jre8 to 7.4.0.jre8
  build.gradle
Labels: dependencies, java

#2083 Bump @storybook devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#1970 Update dev-setup documentation
  docs/dev-setup.md
Labels: debt

#2103 Bump dropwizard from 1.3.13 to 1.3.14
  build.gradle
Labels: dependencies, java

#2104 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2105 Bump webpack and some related devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2106 Remove imports-loader (was only used by alloy editor)
  client/config/webpack.common.js
  client/package.json
  client/yarn.lock
Labels: debt, dependencies, javascript

#2129 Bump react dependencies from 16.8.6 to 16.9.0
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2130 Bump @storybook dependencies from 5.1.10 to 5.1.11
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2131 Bump webdriverio/@wdio devDependencies to 5.12.1
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2132 Bump @fullcalendar dependencies to 4.3.[01]
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2133 Replace fetch polyfill for Jest with cross-fetch
  client/config/polyfills.js
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2134 Fix showing alert or checkbox in people merge
  client/src/pages/admin/MergePeople.js
Labels: bug

#2137 Fix GraphQL media types
  client/tests/sim/simutils.js
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
Labels: bug

#2082 Normalise location coordinates
  client/src/components/Leaflet.js
  client/src/pages/locations/Form.js
Labels: debt, enhancement

#2135 Add authorization checks inside GraphQL methods
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/HomeResource.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/LoggingResource.java
  src/main/java/mil/dds/anet/resources/NoteResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/SavedSearchResource.java
  src/main/java/mil/dds/anet/resources/TagResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
Labels: security

#2084 Upgrade mssql to latest version
  docker/anet-mssql-linux/Dockerfile
Labels: dependencies

#2158 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2161 Small Apollo Client cleanups
  client/src/baseAPI.js
Labels: debt

#2162 Fix history replace renders
  client/src/components/Page.js
  client/src/components/SearchBar.js
  client/src/pages/Home.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Form.js
Labels: debt

#2163 Use generic component for task.longName
  client/src/HOC/DictionaryField.js
  client/src/pages/tasks/Show.js
Labels: debt

#2166 Partially revert 945bdbb
  client/src/components/Page.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
Labels: bug

#2182 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript
