Repository NCI-Agency/anet, pull requests merged in 2019-02, with the labels that each got.

#1300 Only reload reports when paging through a location's or task's reports
  client/src/pages/locations/Show.js
  client/src/pages/tasks/Show.js
Labels: enhancement

#1323 Exclude report authors from receiving emails for approving their own reports
  src/main/java/mil/dds/anet/resources/ReportResource.java
Labels: bug

#1322 Add pytext-nlp as a dependency.
  analytics/Pipfile
  analytics/Pipfile.lock
Labels: debt, dependencies

#1284 GH-1268 Fix mosaic layout for daily rollup
  client/src/components/MosaicLayout.css
  client/src/pages/insights/Show.js
  client/src/pages/rollup/Show.js
Labels: bug

#1346 Fix note delete
  src/main/java/mil/dds/anet/resources/NoteResource.java
Labels: bug

#1328 Fix Advisor Organizations menu
  client/src/components/Nav.js
Labels: bug

#1327 Fix approval status
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/Report.java
Labels: bug

#1345 Improve map markers
  client/package.json
  client/src/components/Leaflet.js
  client/src/components/ReportCollection.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/yarn.lock
Labels: feature

#1348 Remove breadcrumbs
  client/src/components/Breadcrumbs.js
  client/src/pages/GraphiQL.js
  client/src/pages/Home.js
  client/src/pages/Search.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/New.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/insights/Show.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/New.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/New.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/New.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/New.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/MyReports.js
  client/src/pages/reports/New.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/New.js
  client/src/pages/tasks/Show.js
Labels: enhancement

#1329 Update mandatory data fields for completed or cancelled engagements
  client/src/components/RichTextEditor.js
  client/src/models/Report.js
  client/src/pages/reports/Form.js
  client/src/utils.js
  client/tests/e2e/report.js
Labels: enhancement

#1384 Add batching for getting a person's current position through GraphQL
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
Labels: enhancement

#1373 GH-153 testdb
  .gitignore
  anet.yml
  build.gradle
  client/config/wdio.config.js
  client/config/webpack.dev.js
  client/package.json
  client/tests/load/load.yml
  client/tests/util/test.js
  docs/dev-setup.md
Labels: debt

#1298 Gh 1000 storybook v2
  client/.storybook/config.js
  client/package.json
  client/src/components/RichTextEditor.js
  client/stories/Button.stories.js
  client/stories/RichtTextEditor.stories.js
  client/yarn.lock
Labels: debt
