Repository NCI-Agency/anet, pull requests merged in 2019-09, with the labels that each got.

#2192 Fix date range for date filters of type last day/week/month
  client/src/dateUtils.js
Labels: bug

#1778 Add note templates for partner assessment and improve notes user interface
  anet.yml
  client/package.json
  client/src/components/FieldHelper.js
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ResponsiveLayout.js
  client/src/components/graphs/Pie.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/tests/webdriver/specs/editPosition.spec.js
  client/yarn.lock
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/resources/anet-schema.yml
Labels: change in anet.yml, feature

#2210 Only show active persons in advanced select widget
  client/src/components/AssignPersonModal.js
  client/src/pages/reports/Form.js
Labels: enhancement

#2211 Require gender when saving a principal
  client/src/models/Person.js
  client/tests/webdriver/specs/createNewPerson.spec.js
Labels: enhancement

#2212 Remove ability of super users to edit existing location names
  client/src/pages/Search.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/tests/e2e/permissions.js
Labels: enhancement

#2207 Add rudimentary trend indicators to dashboards
  client/src/components/Kanban.js
  client/src/components/Trends.js
  client/src/pages/dashboards/KanbanDashboard.js
Labels: enhancement

#2232 Update dependencies
  client/package.json
  client/yarn.lock
Labels: dependencies

#2185 Add future engagements planning workflow
  build.gradle
  client/src/components/ReportSummary.js
  client/src/components/ReportWorkflow.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/ReportStateSearch.js
  client/src/models/Organization.js
  client/src/models/Report.js
  client/src/pages/Home.js
  client/src/pages/HopscotchTour.js
  client/src/pages/organizations/Approvals.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/MyReports.js
  client/src/pages/reports/Show.js
  client/tests/e2e/home.js
  client/tests/e2e/report.js
  client/tests/selenium/report-submit.xml
  client/tests/util/test.js
  insertBaseData-mssql.sql
  src/integration-test/java/mil/dds/anet/integrationtest/config/AnetITConfiguration.java
  src/integration-test/java/mil/dds/anet/integrationtest/db/FutureEngagementWorkerIT.java
  src/integration-test/java/mil/dds/anet/integrationtest/emails/AnetEmailWorkerIT.java
  src/integration-test/java/mil/dds/anet/integrationtest/emails/EmailServerIT.java
  src/integration-test/java/mil/dds/anet/integrationtest/utils/FakeSmtpServer.java
  src/integration-test/java/mil/dds/anet/integrationtest/utils/TestBeans.java
  src/integration-test/resources/anet-integrationtest.yml
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/ApprovalStepMapper.java
  src/main/java/mil/dds/anet/emails/FutureEngagementUpdated.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/beans/ApprovalStepTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/resources/graphQLTests/orgShow.gql
  src/test/resources/testJson/approvalSteps/testStep.json
Labels: feature

#2233 Alter the stoplist used for most of the tables in the full-text index
  src/main/resources/migrations.xml
Labels: debt, enhancement

#2259 Bump some webdriverio/@wdio devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2263 Bump some @babel devDependencies
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2261 Delete obsolete/unused Selenium tests
  client/tests/selenium/Test Suite as Arthur
  client/tests/selenium/admin - change security banner text
  client/tests/selenium/admin flow - change security banner text
  client/tests/selenium/comment on draft report
  client/tests/selenium/create a new position
  client/tests/selenium/create future engagement
  client/tests/selenium/create new PoAM
  client/tests/selenium/create new advisor org
  client/tests/selenium/create new afghan principal org
  client/tests/selenium/create new coalition member
  client/tests/selenium/create new coalition position - admin
  client/tests/selenium/create new coalition position - super user
  client/tests/selenium/create new draft - edit - and submit
  client/tests/selenium/create new location
  client/tests/selenium/create new position - principal
  client/tests/selenium/create new principal
  client/tests/selenium/create-saved-search
  client/tests/selenium/report submit - change primary advisor
  client/tests/selenium/report-submit - cancelled engagement
  client/tests/selenium/report-submit - cancelled engagement - cancelled by advisor
  client/tests/selenium/report-submit neg atmo to pos atmo
  client/tests/selenium/report-submit-atmosphere-negative
  client/tests/selenium/report-submit-atmospherics-neutral
  client/tests/selenium/report-submit-cancel-and-uncancel-enagement
  client/tests/selenium/report-submit.xml
Labels: debt
