Repository NCI-Agency/anet, pull requests merged in 2020-02, with the labels that each got.

#2783 Fix recursive clause when searching for parents
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
Labels: bug

#2785 Make sure label is updated when position type is changed
  client/src/pages/positions/Form.js
Labels: bug

#2784 Fix selecting/saving cancelled reason
  client/src/pages/reports/Form.js
Labels: bug

#2789 Pass the style down to the LinkTo component
  client/src/components/LinkTo.js
Labels: bug

#2791 Allow non-admin task owners to update their tasks
  client/src/components/CustomDateInput.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/tasks/Form.js
  src/main/java/mil/dds/anet/resources/TaskResource.java
Labels: enhancement

#2792 Properly process orgRecurseStrategy for reports search
  client/src/pages/Home.js
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
Labels: bug

#2814 Bump dependencies
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, java, javascript

#2818 Report approval workflow for tasks
  anet.yml
  client/src/components/ReportTable.js
  client/src/components/ReportWorkflow.js
  client/src/components/approvals/Approvals.js
  client/src/components/approvals/ApprovalsDefinition.js
  client/src/models/Task.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/report.js
  insertBaseData-mssql.sql
  src/integration-test/java/mil/dds/anet/integrationtest/utils/TestBeans.java
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/database/ApprovalStepDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/ApprovalStepMapper.java
  src/main/java/mil/dds/anet/emails/ApprovalNeededEmail.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/resources/ApprovalStepResource.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/threads/ReportApprovalWorker.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/beans/ApprovalStepTest.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/resources/testJson/approvalSteps/testStep.json
Labels: feature

#2819 Update customfields validation
  anet.yml
  client/src/components/CustomFields.js
  client/src/components/Model.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#2777 Fix some LGTM warnings
  client/src/components/AssignPositionModal.js
  client/src/components/TopBar.js
  client/src/pages/App.js
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/graphql/outputtransformers/JsonToXlsxTransformer.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
Labels: debt

#2832 Bump dependencies
  build.gradle
  client/config/browserstack.config.js
  client/package.json
  client/yarn.lock
Labels: dependencies, java, javascript

#2835 Fix Leaflet icon showing up as broken image
  client/package.json
  client/src/components/Leaflet.js
  client/yarn.lock
Labels: bug

#2837 Fix some LGTM alerts
  client/src/pages/people/Form.js
  client/src/store/configureStore.js
  src/main/java/mil/dds/anet/auth/AnetAuthenticationFilter.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CommentDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportActionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/SavedSearchDao.java
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractTagSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPositionSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlLocationSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlPositionSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlTagSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlTaskSearcher.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: debt, java, javascript

#2836 Move project to JUnit 5 test platform
  .travis.yml
  build.gradle
  src/integration-test/java/mil/dds/anet/integrationtest/emails/AnetEmailWorkerTest.java
  src/integration-test/java/mil/dds/anet/integrationtest/emails/EmailServerTest.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlSearcher.java
  src/test/java/mil/dds/anet/test/DaoUtilsTest.java
  src/test/java/mil/dds/anet/test/RandomTests.java
  src/test/java/mil/dds/anet/test/beans/ApprovalStepTest.java
  src/test/java/mil/dds/anet/test/beans/AuthorizationGroupTest.java
  src/test/java/mil/dds/anet/test/beans/OrganizationTest.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/beans/PositionTest.java
  src/test/java/mil/dds/anet/test/beans/ReportTest.java
  src/test/java/mil/dds/anet/test/beans/TagTest.java
  src/test/java/mil/dds/anet/test/beans/TaskTest.java
  src/test/java/mil/dds/anet/test/emails/AccountDeactivationWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/config/AnetTestConfiguration.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/emails/AnetEmailWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/emails/EmailServerTest.java
  src/test/java/mil/dds/anet/test/integration/utils/EmailResponse.java
  src/test/java/mil/dds/anet/test/integration/utils/FakeSmtpServer.java
  src/test/java/mil/dds/anet/test/integration/utils/TestBeans.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/RollupGraphComparatorTest.java
  src/test/java/mil/dds/anet/test/resources/SavedSearchResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/java/mil/dds/anet/utils/UtilsTest.java
  src/test/resources/integration/anet-integrationtest.yml
Labels: debt, java

#2838 Make recents a regular search
  client/src/pages/reports/Form.js
  src/main/java/mil/dds/anet/beans/search/AbstractSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/AuthorizationGroupSearchSortBy.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchSortBy.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchSortBy.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchSortBy.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/resources/graphQLTests/location-recents-maxResults.gql
  src/test/resources/graphQLTests/location-recents.gql
  src/test/resources/graphQLTests/person-recents-maxResults.gql
  src/test/resources/graphQLTests/person-recents.gql
  src/test/resources/graphQLTests/report-all-recents.gql
  src/test/resources/graphQLTests/task-recents-maxResults.gql
  src/test/resources/graphQLTests/task-recents.gql
Labels: debt, enhancement

#2868 Fix app tests
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/emails/AnetEmailWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/emails/EmailServerTest.java
  src/test/java/mil/dds/anet/test/integration/utils/TestApp.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: debt

#2863 Allow report to have an engagementDate yet a NULL nextSteps
  client/src/models/Report.js
Labels: bug

#2839 Bump dependencies
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, java, javascript

#2867 nci-agency/anet#2866: Fix unable to submit edit form when no customFields
  client/src/components/CustomFields.js
Labels: bug

#2888 Remove unused depenencies - uuid and graphql
  client/package.json
Labels: debt
