Repository NCI-Agency/anet, pull requests merged in 2020-09, with the labels that each got.

#3175 Fix createReport test
  .github/workflows/build-gradle.yml
  client/tests/webdriver/specs/createReport.spec.js
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/resources/LoggingResource.java
Labels: debt

#3189 Fix delete of associated position
  client/src/components/EditAssociatedPositionsModal.js
Labels: bug

#3017 Gh 1839 Detect planning conflicts
  client/config/wdio.config.js
  client/package.json
  client/src/components/PlanningConflictForPerson.js
  client/src/components/PlanningConflictForReport.js
  client/src/models/Report.js
  client/src/pages/reports/AttendeesTable.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/tests/models/report.test.js
  client/tests/webdriver/pages/report/createReport.page.js
  client/tests/webdriver/pages/report/editReport.page.js
  client/tests/webdriver/pages/report/myReports.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/specs/createReportWithPlanningConflict.spec.js
Labels: feature

#3192 Code formatting: remove odd spaces. To prevent triggering false changes.
  anet.yml
Labels: debt

#3198 Be more explicit in what we want renovate to do/ignore
  .github/renovate.json
Labels: debt, dependencies

#3200 Remove minimal report view
  client/src/pages/Routing.js
  client/src/pages/reports/Minimal.js
  src/main/resources/emails/rollup.ftlh
Labels: debt

#3197 Fix RichTextEditor story
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/platform/storybook/settings.js
  client/platform/utils.js
  client/platform/web-dev/settings.js
  client/stories/RichTextEditor.stories.js
Labels: debt

#3201 Fix planning conflict intermittent wdio test errors
  client/tests/webdriver/pages/report/createReport.page.js
Labels: bug

#3202 Pin leaflet version at 1.6.0 for leaflet.markercluster
  client/package.json
Labels: debt

#3066 Gh 3019 Add an anet service graphql interface - GH 2081 Change email address message
  anet-dictionary.yml
  anet.yml
  build.gradle
  client/package.json
  client/platform/web-dev/settings.js
  client/platform/web/settings.js
  client/public/index.hbs
  client/src/components/SecurityBanner.js
  client/src/models/Person.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/UserActivityTable.css
  client/src/pages/admin/UserActivityTable.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/specs/userLogin.spec.js
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetCheckCommand.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/resources/HomeResource.java
  src/main/java/mil/dds/anet/utils/AnetConstants.java
  src/main/java/mil/dds/anet/views/IndexView.java
  src/main/java/mil/dds/anet/views/ViewResponseFilter.java
  src/main/resources/anet-schema.yml
  src/main/resources/version.properties
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlHelper.java
Labels: change in anet.yml, feature

#3213 User without position can create draft reports again
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/reports/Form.js
Labels: bug

#3211 Fix customFields assessments
  anet-dictionary.yml
  client/src/components/CustomFields.js
  client/src/components/Model.js
  client/src/utils.js
  insertBaseData-mssql.sql
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
Labels: bug, debt

#3216 Pin Yarn version at 1.22.10
  .github/workflows/build-gradle.yml
  CONTRIBUTING.md
  build.gradle
  docs/dev-setup.md
Labels: debt

#3219 Fix a bug where periodic assessments were always missing
  client/src/components/Model.js
Labels: bug

#3222 Use 'now' instead of the end-of-day in UTC
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
Labels: bug, enhancement
