Repository NCI-Agency/anet, pull requests merged in 2020-04, with the labels that each got.

#2930 Fix dev-setup markdown
  docs/dev-setup.md
Labels: debt

#2966 Improve task assessments
  anet.yml
  client/src/components/AggregationWidget.js
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/TaskTable.js
  client/src/components/assessments/AddAssessmentModal.js
  client/src/components/assessments/AssessmentResultsTable.css
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/graphs/LikertScale.js
  client/src/models/AuthorizationGroup.js
  client/src/models/Location.js
  client/src/models/Organization.js
  client/src/models/Person.js
  client/src/models/Position.js
  client/src/models/Report.js
  client/src/models/Task.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  insertBaseData-mssql.sql
  src/main/resources/anet-schema.yml
Labels: feature

#2975 Explicitly set the FreeMarker Configuration version
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: debt

#2976 Conservatively cache domain users
  build.gradle
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/resources/ehcache-config.xml
Labels: debt

#2972 Parallellise client side tests
  client/ava.config.js
  client/package.json
  client/tests/e2e/permissions.js
  client/tests/e2e/position.js
  client/tests/e2e/report.js
  client/tests/util/test.js
Labels: debt

#2985 Defensively copy objects in the domainUsersCache
  build.gradle
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
Labels: debt

#2996 Fix comment email when report was deleted
  src/main/java/mil/dds/anet/emails/ApprovalNeededEmail.java
  src/main/java/mil/dds/anet/emails/FutureEngagementUpdated.java
  src/main/java/mil/dds/anet/emails/NewReportCommentEmail.java
  src/main/java/mil/dds/anet/emails/ReportEditedEmail.java
  src/main/java/mil/dds/anet/emails/ReportEmail.java
  src/main/java/mil/dds/anet/emails/ReportPublishedEmail.java
  src/main/java/mil/dds/anet/emails/ReportRejectionEmail.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: bug
