Repository NCI-Agency/anet, pull requests merged in 2020-11, with the labels that each got.

#3277 Set READ_COMMITTED_SNAPSHOT to ON on MS SQL to prevent hangs due to locking
  src/main/java/mil/dds/anet/threads/AbstractWorker.java
  src/main/resources/migrations.xml
Labels: bug

#3271 Add annually option to the dictionary for assessment period choice
  anet-dictionary.yml
Labels: enhancement

#3275 Change the format of assessment period start date
  client/src/components/Model.js
  client/src/components/assessments/AssessmentModal.js
  client/src/periodUtils.js
  src/main/resources/migrations.xml
Labels: debt

#3280 Update READ_COMMITTED_SNAPSHOT migration
  src/main/resources/migrations.xml
Labels: debt

#3283 Change conflicting report tests to test more general case
  client/tests/webdriver/specs/createReportWithPlanningConflict.spec.js
Labels: bug

#3287 Correct parent organization selection for new principal organizations
  client/src/pages/organizations/Form.js
Labels: bug

#3289 Make insights & rollup use the whole page under Chrome 86 and up
  client/src/index.css
  client/src/pages/insights/Show.js
  client/src/pages/rollup/Show.js
Labels: bug

#3291 Fix map for report statistics
  client/src/components/Leaflet.js
  client/src/components/ReportCollection.js
  client/src/components/ReportStatistics.js
  client/src/components/aggregations/AggregationWidgetContainer.js
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/assessments/InstantAssessmentResults.js
  client/tests/webdriver/pages/myOrg.page.js
Labels: bug

#3279 Java 15 and rpm/deb packaging
  .github/workflows/build-gradle.yml
  .github/workflows/codeql-analysis.yml
  build.gradle
  docs/BUILD.md
  docs/INSTALL.md
  lib/license62.txt
  lib/sqljdbc_auth.dll
  scripts/anet.service
Labels: debt

#3294 Fix position table missing locations in task page
  client/src/pages/tasks/Show.js
Labels: bug

#3292 Remove uses of `_uniqueId` for React component keys
  client/src/components/AdvisorReports/AdvisorReportsRow.js
  client/src/components/AdvisorReports/AdvisorReportsTable.js
  client/src/components/ReportMap.js
  client/src/components/aggregations/AggregationWidgetContainer.js
  client/src/components/aggregations/DefaultAggWidget.js
  client/src/components/aggregations/ReportsByTaskWidget.js
  client/src/components/aggregations/ReportsMapWidget.js
  client/src/components/aggregations/utils.js
  client/src/pages/dashboards/DiagramNode.js
Labels: debt

#3272 Fix semiannually and semimonthly period calculations
  anet-dictionary.yml
  client/package.json
  client/src/periodUtils.js
  client/tests/utils/periodUtils.test.js
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
Labels: bug

#3297 Replace JSON validator
  build.gradle
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/resources/anet-schema.yml
Labels: debt

#3276 Add a biweekly period implementation
  client/src/periodUtils.js
  client/tests/utils/periodUtils.test.js
Labels: enhancement

#3301 Deprecate GHA `set-env`
  .github/workflows/build-gradle.yml
Labels: debt

#3305 Fix FutureEngagementWorker
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
Labels: bug

#3299 Fix LGTM warnings
  client/config/polyfills.js
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/graphql/GraphQlDateTimeType.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: debt

#3307 Fix ReportCollection undefined widgetIds as no mapId supplied
  client/src/components/ReportMap.js
Labels: bug

#3309 Add test case for reproducible scenario of NCI-Agency/anet#3304
  anet-dictionary.yml
  anet.yml
  client/tests/e2e/report.js
  client/tests/webdriver/specs/createNewPerson.spec.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  insertBaseData-mssql.sql
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  src/test/resources/testJson/people/jack.json
  src/test/resources/testJson/reports/test.json
Labels: bug, debt

#3205 Update documents due to change of dictionary loading approach
  anet-dictionary.yml
  client/platform/node/settings.js
  client/platform/storybook/settings.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
Labels: change in anet.yml

#3311 Fix double warning messages on report forms
  client/src/models/Report.js
Labels: bug

#3174 Fix nodeSize making useEffect run every render
  client/src/components/graphs/OrganizationalChart.js
Labels: bug

#3314 Don't show assessments for future engagements
  client/src/components/CustomFields.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/pages/createFutureReport.page.js
  client/tests/webdriver/pages/createReport.page.js
  client/tests/webdriver/specs/createFutureReport.spec.js
  client/tests/webdriver/specs/createReport.spec.js
  insertBaseData-mssql.sql
Labels: enhancement

#3316 Fix report number fields' errors
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/pages/reports/Form.js
  client/src/utils.js
  client/tests/webdriver/pages/createReport.page.js
  client/tests/webdriver/specs/createReport.spec.js
Labels: bug

#3321 Remove circular dependencies from our JavaScript code
  client/config/webpack.common.js
  client/package.json
  client/src/components/AdvancedSearch.js
  client/src/components/AssignPositionModal.js
  client/src/components/CustomFields.js
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/Nav.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ResponsiveLayout.js
  client/src/components/ResponsiveLayoutContext.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/OrganizationFilter.js
  client/src/components/editor/LinkAnet.js
  client/src/models/Person.js
  client/src/models/Report.js
  client/src/pages/Home.js
  client/src/pages/dashboards/DecisivesDashboard.js
  client/src/pages/insights/Show.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/MyTasks.js
  client/src/searchUtils.js
  client/src/utils_links.js
  client/yarn.lock
Labels: debt
