Repository NCI-Agency/anet, pull requests merged in 2020-10, with the labels that each got.

#3227 Fix required value prop failing on null values
  client/src/components/advancedSelectWidget/AdvancedSingleSelect.js
Labels: bug

#3232 Make the RelatedObjectsTable a true multi-select
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectsTable.js
Labels: debt

#3234 Fix spurious auto-save
  client/src/pages/reports/Form.js
Labels: bug

#3253 Fix LGTM warnings about Cloneable
  src/main/java/mil/dds/anet/beans/search/AbstractBatchParams.java
  src/main/java/mil/dds/anet/beans/search/AbstractSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/AuthorizationGroupSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/FkBatchParams.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/M2mBatchParams.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/RecursiveFkBatchParams.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TagSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
Labels: debt

#3255 Pin fullcalendar version
  .github/renovate.json
Labels: debt

#3257 Add Network Issues as a cancellation reason
  client/src/components/advancedSearch/ReportStateFilter.js
  client/src/models/Report.js
  client/src/pages/reports/Form.js
  src/main/java/mil/dds/anet/beans/Report.java
Labels: enhancement

#3259 Stop the auto-save from rescheduling itself after unmount
  client/src/pages/reports/Form.js
Labels: bug, debt

#3258 Disable report form submit buttons while submitting
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
Labels: debt

#3261 Improve account deactivation warning mechanism
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/JobHistory.java
  src/main/java/mil/dds/anet/database/JobHistoryDao.java
  src/main/java/mil/dds/anet/database/mappers/JobHistoryMapper.java
  src/main/java/mil/dds/anet/threads/AbstractWorker.java
  src/main/java/mil/dds/anet/threads/AccountDeactivationWorker.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/threads/MaterializedViewRefreshWorker.java
  src/main/java/mil/dds/anet/threads/ReportApprovalWorker.java
  src/main/java/mil/dds/anet/threads/ReportPublicationWorker.java
  src/main/resources/migrations.xml
Labels: bug, debt

#3266 Fix getting responsibleTasks
  client/src/components/EditAssociatedPositionsModal.js
  client/src/notificationsUtils.js
  client/src/pages/App.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/MyTasks.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
Labels: bug

#3263 Add coordinates to location link label
  client/src/models/Location.js
  client/src/pages/reports/Show.js
  client/tests/e2e/permissions.js
Labels: enhancement

#3269 Fix missing location in position table
  client/src/components/PositionTable.js
  client/src/pages/App.js
Labels: bug
