Repository NCI-Agency/anet, pull requests merged in 2020-03, with the labels that each got.

#2872 Fix the sim to work with the new custom fields
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/ReportStories.js
Labels: debt

#2900 Fix OrganizationFilter on double click overlay row
  client/src/components/advancedSearch/OrganizationFilter.js
Labels: bug

#2903 Fix error when clicking on a report's notes
  client/src/components/RelatedObjectNotes.js
Labels: bug

#2887 Report approval workflow for location
  client/src/components/approvals/Approvals.js
  client/src/models/Location.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: feature

#2902 Relax author approval requirement
  client/src/pages/reports/Show.js
  client/tests/e2e/report.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
Labels: enhancement

#2899 Fix React warnings since 16.13.0
  client/src/components/ReportMap.js
  client/src/components/ReportSummary.js
  client/src/components/ReportTable.js
  client/src/components/RichTextEditor.js
  client/src/pages/Search.js
Labels: debt

#2913 Fix Gradle deprecation warnings
  build.gradle
Labels: debt

#2908 Use general task labels, or top-level or sub-level task labels when appropriate
  anet.yml
  client/src/components/ReportSummary.js
  client/src/components/ReportsByTask.js
  client/src/components/TaskTable.js
  client/src/models/Report.js
  client/src/pages/HopscotchTour.js
  client/src/pages/insights/Show.js
  client/src/pages/organizations/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/rollup.ftlh
Labels: enhancement

#2919 Refactor GraphQL for organizations
  client/src/pages/App.js
  client/src/pages/positions/Form.js
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/resources/graphQLTests/appQuery.gql
Labels: debt

#2918 Store the avatar as binary data in the database
  client/src/components/AvatarDisplayComponent.js
  client/src/components/AvatarEditModal.js
  client/src/components/graphs/OrganizationalChart.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/mappers/MapperUtils.java
  src/main/java/mil/dds/anet/database/mappers/PersonMapper.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
Labels: debt

#2920 Contributors.md file is updated.
  Contributors.md
Labels: debt

#2921 Update person customFields
  anet.yml
  client/tests/e2e/permissions.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/specs/createNewPerson.spec.js
Labels: debt

#2924 Fix error when loading the LikertScale
  client/src/components/graphs/LikertScale.js
Labels: debt

#2927 Fix editing avatar
  client/src/components/AvatarEditModal.js
Labels: bug

#2928 Update dev setup documentation
  docs/INSTALL.md
  docs/dev-setup.md
  docs/frontend-overview.md
Labels: debt

#2865 Harmonise report state colours
  client/src/components/DailyRollupChart.js
  client/src/components/ReportCalendar.js
  client/src/components/ReportSummary.js
  client/src/components/ReportWorkflow.css
  client/src/components/ReportWorkflow.js
  client/src/index.css
  client/src/models/Report.js
  client/src/pages/rollup/Show.js
Labels: enhancement

#2944 Fix FutureEngagementsByLocation insight
  client/src/components/FutureEngagementsByLocation.js
Labels: bug

#2953 Remove Travis CI integration
  .travis.yml
  README.md
  client/config/browserstack.config.js
  client/config/wdio.config.js
  client/tests/util/test.js
Labels: debt

#2940 Lazy-load avatars
  build.gradle
  client/src/components/AvatarDisplayComponent.js
  client/src/components/AvatarEditModal.js
  client/src/components/graphs/OrganizationalChart.js
  client/src/exportUtils.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/ForeignKeyBatcher.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/mappers/ForeignKeyMapper.java
  src/main/java/mil/dds/anet/database/mappers/PersonMapper.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/IdDataLoaderKey.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
Labels: debt
