Repository NCI-Agency/anet, pull requests merged in 2020-07, with the labels that each got.

#3090 Make sure we keep our initial admin
  client/tests/sim/simutils.js
  client/tests/sim/stories/NoteStories.js
  client/tests/sim/stories/PositionStories.js
Labels: debt

#3092 Improve layout/scrolling of NATO Member Reports insight if there are many organizations
  client/src/pages/insights/Show.js
Labels: debt

#3099 Fix Uncaught TypeError: First argument must be a string
  client/src/utils_links.js
Labels: debt

#3101 Replace <AppContext.Consumer> with useContext()
  client/src/components/AssignPositionModal.js
  client/src/components/CreateButton.js
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/GuidedTour.js
  client/src/components/Nav.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/SecurityBanner.js
  client/src/components/TopBar.js
  client/src/pages/Help.js
  client/src/pages/Home.js
  client/src/pages/Routing.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/insights/Show.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/organizations/OrganizationTasks.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/MyReports.js
  client/src/pages/reports/New.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
Labels: debt

#3106 Fix report approval/rejection warnings
  client/src/pages/reports/Show.js
Labels: bug

#3107 Add CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: debt

#3012 Json sanitization
  build.gradle
  client/src/components/Nav.js
  client/src/components/ReportTags.js
  client/src/pages/Routing.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Show.js
  client/src/pages/util.js
  src/main/java/mil/dds/anet/database/TagDao.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/NoteResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TagResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/java/mil/dds/anet/views/AbstractCustomizableAnetBean.java
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TagResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/java/mil/dds/anet/utils/UtilsTest.java
  src/test/resources/graphQLTests/person-all-paged.gql
  src/test/resources/graphQLTests/person-all.gql
  src/test/resources/graphQLTests/person-recents-maxResults.gql
  src/test/resources/graphQLTests/person-recents.gql
  src/test/resources/graphQLTests/person.gql
  src/test/resources/graphQLTests/report-all-recents.gql
  src/test/resources/graphQLTests/report.gql
  src/test/resources/graphQLTests/reportsAll.gql
  src/test/resources/graphQLTests/tasks-with-positions.gql
  src/test/resources/graphQLTests/tasks-with-reports.gql
  src/test/resources/graphQLTests/tasksAll-with-reports.gql
  src/test/resources/graphQLTests/tasksAll.gql
Labels: debt

#3111 Remove unused headers from wdio test config
  client/config/wdio.config.js
Labels: security
