Repository NCI-Agency/anet, pull requests merged in 2020-12, with the labels that each got.

#3325 Fix parsing smtp config in anet.yml
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: debt

#3328 Refactor recent users & activities
  client/src/pages/admin/Index.js
  client/src/pages/admin/UserActivityTable.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/views/ViewResponseFilter.java
Labels: debt

#3331 Update chromedriver to v87
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#3322 Fix customFields's bugs and refactor / add test cases
  client/src/components/CustomFields.js
  client/src/components/Kanban.js
  client/src/components/Model.js
  client/src/components/ReportStatistics.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/ReportStateFilter.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/aggregations/utils.js
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/graphs/Pie.js
  client/src/models/Report.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/dashboards/DiagramNode.js
  client/src/pages/locations/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Form.js
  client/src/pages/people/New.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/MyReports.js
  client/src/pages/reports/New.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/New.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/createNewTask.page.js
  client/tests/webdriver/pages/createReport.page.js
  client/tests/webdriver/specs/customFields.spec.js
Labels: bug, debt

#3329 Fix state update after unmount in LinkAnetEntity
  client/src/components/editor/LinkAnetEntity.js
Labels: bug, debt

#3333 Refactor automaticallyInactivateUsers.ignoredDomainNames
  src/main/java/mil/dds/anet/threads/AccountDeactivationWorker.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/test/java/mil/dds/anet/utils/UtilsTest.java
Labels: debt

#3161 Add print report functionality
  client/src/components/Compact.js
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/components/Fieldset.js
  client/src/components/ReportWorkflow.js
  client/src/components/SecurityBanner.js
  client/src/components/SimpleMultiCheckboxDropdown.js
  client/src/index.css
  client/src/pages/Routing.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Show.js
  client/src/utils.js
  client/stories/SimpleMultiCheckboxDropdown.stories.js
  client/tests/webdriver/pages/showReport.page.js
  client/tests/webdriver/specs/printReport.spec.js
Labels: feature

#3341 Fix aggregation function modifying the Settings
  client/src/components/aggregations/utils.js
Labels: bug

#3353 Remove unused dependency mathjs
  client/package.json
  client/yarn.lock
Labels: debt

#3362 Provide a sensible default if fieldsConfig is not set
  client/src/components/CustomFields.js
Labels: bug

#3363 Filter out people pending verification from advanced search
  client/src/components/SearchFilters.js
Labels: bug

#3370 Add tests for a different anet dictionary which doesn't have custom fields
  .github/workflows/build-gradle.yml
  anet.yml
  build.gradle
  client/config/wdio.config.js
  client/package.json
  client/src/pages/people/Edit.js
  client/src/pages/people/New.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/New.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/New.js
  client/tests/webdriver/baseSpecs/createAuthorizationGroup.spec.js
  client/tests/webdriver/baseSpecs/createNewLocation.spec.js
  client/tests/webdriver/baseSpecs/createNewPerson.spec.js
  client/tests/webdriver/baseSpecs/createReportWithPlanningConflict.spec.js
  client/tests/webdriver/baseSpecs/editLocation.spec.js
  client/tests/webdriver/baseSpecs/editPosition.spec.js
  client/tests/webdriver/baseSpecs/ie/ie11RetiredBanner.spec.js
  client/tests/webdriver/baseSpecs/locationUtils.js
  client/tests/webdriver/baseSpecs/myCounterparts.spec.js
  client/tests/webdriver/baseSpecs/myTasks.spec.js
  client/tests/webdriver/baseSpecs/newUserUtils.js
  client/tests/webdriver/baseSpecs/onboardNewUser.spec.js
  client/tests/webdriver/baseSpecs/previewRollupEmail.spec.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/baseSpecs/userLogin.spec.js
  client/tests/webdriver/customFieldsSpecs/createFutureReport.spec.js
  client/tests/webdriver/customFieldsSpecs/createReport.spec.js
  client/tests/webdriver/customFieldsSpecs/customFields.spec.js
  client/tests/webdriver/customFieldsSpecs/myOrg.spec.js
  client/tests/webdriver/customFieldsSpecs/notifications.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/noCustomFieldsSpecs/anetObjectForms.spec.js
  client/tests/webdriver/pages/createNewOrganization.page.js
  testDictionaries/no-custom-fields.yml
Labels: debt

#3373 Fix unused env variable at wdio script in package.json
  anet-dictionary.yml
  client/config/wdio.config.ie.js
  client/config/wdio.config.js
  client/package.json
  client/tests/webdriver/ie/ie11RetiredBanner.spec.js
Labels: debt

#3372 Add a default search filter for filtering unverified people
  client/src/components/AdvancedSearch.js
  client/src/components/SearchFilters.js
  client/tests/webdriver/baseSpecs/advancedSearch.spec.js
  client/tests/webdriver/pages/advancedSearch.js
Labels: debt, enhancement

#3371 Change engagementDate format in emailed reports
  anet-dictionary.yml
  src/main/java/mil/dds/anet/database/JobHistoryDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/MapperUtils.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/threads/PendingAssessmentsNotificationWorker.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/java/mil/dds/anet/views/ViewResponseFilter.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/integration/utils/TestBeans.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: bug, debt
