Repository NCI-Agency/anet, pull requests merged in 2020-01, with the labels that each got.

#2684 Fix Draftail editor tests
  client/src/components/RelatedObjectNoteModal.js
  client/src/pages/people/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
  client/tests/e2e/permissions.js
  client/tests/e2e/report.js
  client/tests/util/test.js
Labels: bug

#2687 Bump Java dependencies
  build.gradle
Labels: dependencies, java

#2688 Refactor GraphQL schema
  build.gradle
  src/main/java/mil/dds/anet/beans/AdminSetting.java
  src/main/java/mil/dds/anet/beans/AdvisorReportsEntry.java
  src/main/java/mil/dds/anet/beans/AdvisorReportsStats.java
  src/main/java/mil/dds/anet/beans/AnetEmail.java
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/Comment.java
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/beans/NoteRelatedObject.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/PersonPositionHistory.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/ReportAction.java
  src/main/java/mil/dds/anet/beans/ReportPerson.java
  src/main/java/mil/dds/anet/beans/ReportSensitiveInformation.java
  src/main/java/mil/dds/anet/beans/RollupGraph.java
  src/main/java/mil/dds/anet/beans/Tag.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/lists/AnetBeanList.java
  src/main/java/mil/dds/anet/beans/search/AbstractSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/AuthorizationGroupSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/SavedSearch.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/views/AbstractAnetBean.java
Labels: debt, dependencies, java

#2659 Fix the wdio printRollup test
  client/src/pages/rollup/Show.js
  client/tests/webdriver/pages/rollup.page.js
  client/tests/webdriver/specs/previewRollupEmail.spec.js
Labels: debt

#2581 Fix Advanced Search and Advanced Select issues
  client/src/HOC/LoaderHOC.js
  client/src/components/AdvancedSearch.js
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/FieldHelper.js
  client/src/components/ResponsiveLayout.js
  client/src/components/SearchBar.js
  client/src/components/SearchFilters.js
  client/src/components/TopBar.js
  client/src/components/advancedSearch/AdvancedSelectFilter.js
  client/src/components/advancedSearch/CheckboxSearchFilter.js
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/components/advancedSearch/OrganizationFilter.js
  client/src/components/advancedSearch/ReportStateSearch.js
  client/src/components/advancedSearch/SelectSearchFilter.js
  client/src/components/advancedSearch/TextInputFilter.js
  client/src/components/advancedSelectWidget/AdvancedMultiSelect.js
  client/src/components/advancedSelectWidget/AdvancedSelect.css
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/components/advancedSelectWidget/AdvancedSingleSelect.js
  client/src/index.css
  client/src/pages/admin/MergePeople.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/organizations/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Form.js
  client/tests/e2e/report.js
  client/tests/util/test.js
  client/tests/webdriver/specs/previewRollupEmail.spec.js
Labels: bug, enhancement

#2695 Downgrade react-scroll to 1.7.14
  client/package.json
  client/yarn.lock
Labels: bug

#2749 Bump dependencies
  build.gradle
  client/package.json
  client/src/components/FieldHelper.js
  client/yarn.lock
Labels: dependencies, java, javascript

#2694 Support for multiple tasked organizations
  anet.yml
  client/src/components/AssignPositionModal.js
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/Kanban.js
  client/src/components/LinkTo.js
  client/src/components/OrganizationTable.js
  client/src/components/SearchFilters.js
  client/src/components/TaskTable.js
  client/src/components/advancedSearch/OrganizationFilter.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/exportUtils.js
  client/src/models/Task.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/OrganizationTasks.js
  client/src/pages/organizations/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Minimal.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/New.js
  client/src/pages/tasks/Show.js
  docs/INSTALL.md
  docs/anet.yml.production.template
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/search/ISearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PersonSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/database/mappers/TaskMapper.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/resources/graphQLTests/report-all-recents.gql
  src/test/resources/graphQLTests/report.gql
  src/test/resources/graphQLTests/task-recents-maxResults.gql
  src/test/resources/graphQLTests/task-recents.gql
Labels: enhancement

#2758 Bump dev dependencies as well as nodejs
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, javascript

#2686 Improve organization diagram layout and behavior
  client/src/components/Kanban.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/graphs/OrganizationalChart.js
  client/src/components/graphs/Pie.js
  client/src/components/graphs/SVGCanvas.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/organizations/Show.js
  client/src/resources/plus.png
  client/src/utils.js
Labels: debt, enhancement

#2773 Bump dependencies
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, java, javascript

#2751 Minor improvements to advanced search filters
  client/src/components/AdvancedSearch.js
  client/src/components/advancedSearch/DateRangeSearch.js
  client/src/components/advancedSearch/ReportStateSearch.js
  client/src/components/advancedSelectWidget/AdvancedSelect.css
  client/src/index.css
Labels: enhancement
