Repository NCI-Agency/anet, pull requests merged in 2021-11, with the labels that each got.

#3908 Fix typo in error handling
  client/src/index-auth.js
Labels: bug

#3911 Make tests run again on BrowserStack
  .github/workflows/build-gradle.yml
  README.md
  build.gradle
  client/.gitignore
  client/config/wdio.config.ie.js
  client/config/wdio.config.js
  client/config/webpack.common.js
  client/package.json
  client/src/pages/reports/Form.js
  client/tests/e2e/report.js
  client/tests/util/test.js
  client/tests/webdriver/baseSpecs/createReportWithPlanningConflict.spec.js
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
  client/tests/webdriver/baseSpecs/myTasks.spec.js
  client/tests/webdriver/baseSpecs/newUserUtils.js
  client/tests/webdriver/baseSpecs/onboardNewUser.spec.js
  client/tests/webdriver/customFieldsSpecs/createFutureReport.spec.js
  client/tests/webdriver/customFieldsSpecs/createReport.spec.js
  client/tests/webdriver/customFieldsSpecs/customFields.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/ie/ie11RetiredBanner.spec.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  client/tests/webdriver/pages/createNewOrganization.page.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/createNewPosition.page.js
  client/tests/webdriver/pages/createNewTask.page.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/onboard.page.js
  client/tests/webdriver/pages/page.js
  client/tests/webdriver/pages/report/editReport.page.js
  client/tests/webdriver/pages/showPerson.page.js
  client/tests/webdriver/pages/showTask.page.js
  client/yarn.lock
  docs/dev-setup.md
  testDictionaries/no-custom-fields.yml
Labels: debt

#3922 Show field validation errors for button groups and links to ANET objects
  client/src/components/FieldHelper.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
Labels: bug

#3924 Prevent unnecessary scrollbar on roll-up page
  client/src/index.css
  client/src/pages/insights/Show.js
  client/src/pages/rollup/Show.js
Labels: enhancement

#3925 Update JSON schema validator
  .github/renovate.json
  build.gradle
  src/main/resources/anet-schema.yml
Labels: debt

#3917 Group assessment questions
  anet-dictionary.yml
  client/src/components/CustomFields.js
  client/src/components/Fieldset.js
  client/src/components/Model.js
  client/src/components/assessments/AssessmentModal.js
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/assessments/InstantAssessmentResults.js
  client/src/components/assessments/InstantAssessmentsContainerField.js
  client/src/components/assessments/OndemandAssessments.js
  client/src/components/assessments/PeriodicAssessmentResults.js
  client/src/components/assessments/QuestionSet.js
  client/src/index.css
  client/src/pages/dashboards/DiagramNode.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Form.js
  client/src/utils.js
  client/stories/LinguistAssessments.stories.js
  client/tests/webdriver/baseSpecs/assessmentsForPeople.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/pages/showPerson.page.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#3537 Enhance merge people for fine grained control
  build.gradle
  client/src/components/PreviousPositions.js
  client/src/mergeUtils.js
  client/src/models/Person.js
  client/src/pages/admin/MergePeople.js
  client/src/pages/people/Show.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/pages/mergePeople.page.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/utils/ResourceUtils.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/merge/LocationMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PersonMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PositionMergeTest.java
  src/test/java/mil/dds/anet/test/utils/ResourceUtilsTest.java
  src/test/resources/anet.graphql
Labels: enhancement

#3930 Fix task assessments disappearing
  client/src/pages/reports/Edit.js
Labels: bug

#3933 Fix name conflict while importing bootstrap component
  client/src/pages/positions/Form.js
Labels: bug

#3931 Remove task custom fields assessments
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/models/Task.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/customFieldsSpecs/customFields.spec.js
  client/tests/webdriver/customFieldsSpecs/myOrg.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: debt

#3902 Add deprecation feature to custom fields
  anet-dictionary.yml
  client/src/components/CustomFields.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#3928 Ensure we can use the on demand assessment without expiration
  anet-dictionary.yml
  client/src/components/assessments/AssessmentResultsContainer.js
  client/src/components/assessments/OnDemandAssessments/Ondemand.css
  client/src/components/assessments/OnDemandAssessments/OndemandAssessment.js
  client/src/components/assessments/OnDemandAssessments/ValidationBar.js
  client/stories/1-user/VettingAndScreening.stories.js
  client/stories/1-user/vettingAndScreening.stories.mdx
  src/main/resources/anet-schema.yml
Labels: enhancement
