Repository NCI-Agency/anet, pull requests merged in 2021-06, with the labels that each got.

#3632 Edit location and display location types
  client/src/components/LocationTable.js
  client/src/components/Messages.js
  client/src/components/ReportSummary.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/exportUtils.js
  client/src/models/Location.js
  client/src/models/Position.js
  client/src/pages/Search.js
  client/src/pages/admin/MergeLocations.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/tests/webdriver/baseSpecs/advancedSearch.spec.js
  client/tests/webdriver/baseSpecs/createNewLocation.spec.js
  client/tests/webdriver/baseSpecs/editLocation.spec.js
  client/tests/webdriver/baseSpecs/locationUtils.js
  client/tests/webdriver/pages/location/createNewLocation.page.js
  client/tests/webdriver/pages/location/editLocation.page.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchQuery.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/mappers/LocationMapper.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/resources/anet.graphql
Labels: feature

#3639 Update Node.js to latest 14.x LTS
  build.gradle
Labels: debt

#3644 Add a location type for place of birth
  anet-dictionary.yml
  client/src/components/CustomFields.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#3622 Print or export people profiles
  anet-dictionary.yml
  client/src/components/Compact.js
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/components/SimpleMultiCheckboxDropdown.js
  client/src/index.css
  client/src/pages/Routing.js
  client/src/pages/people/Compact.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Compact.js
  client/tests/webdriver/baseSpecs/printPerson.spec.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/pages/showPerson.page.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#3674 Update (most) @babel dependencies to v7.14.x
  client/package.json
  client/yarn.lock
Labels: dependencies

#3673 Update dropwizard dependencies to v2.0.23
  build.gradle
Labels: dependencies
