Repository NCI-Agency/anet, pull requests merged in 2021-02, with the labels that each got.

#3409 Make postgresql schema consistent with mssql
  src/main/resources/migrations.xml
Labels: bug

#3429 Fix yupDate conversion
  client/src/components/CustomDateInput.js
  client/src/components/Model.js
Labels: bug

#3439 Remove unused dependency html-loader
  client/package.json
  client/yarn.lock
Labels: dependencies

#3427 Migrate to @blueprintjs/popover2
  client/package.json
  client/src/components/AdvancedSearch.js
  client/src/components/BlueprintOverrides.css
  client/src/components/PlanningConflictForPerson.js
  client/src/components/PlanningConflictForReport.js
  client/src/components/SearchBar.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/index.css
  client/src/pages/locations/GeoLocation.js
  client/tests/webdriver/pages/advancedSearch.js
  client/tests/webdriver/pages/location/createNewLocation.page.js
  client/tests/webdriver/pages/location/editLocation.page.js
  client/yarn.lock
Labels: debt

#3435 Use inclusive language
  CONTRIBUTING.md
  build.gradle
  client/README.md
  client/ava.config.js
  client/src/utils.js
  docs/dev-setup.md
  scripts/githooks/pre-commit
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/db/ReportPublicationWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/emails/AnetEmailWorkerTest.java
  src/test/java/mil/dds/anet/utils/UtilsTest.java
Labels: debt

#3441 Update react-tooltip to 4.2.14
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3450 Remove unused client side scripts folder
  client/package.json
  client/scripts/test.js
Labels: debt

#3454 Fix my counterparts tab not showing fields
  client/src/pages/App.js
Labels: bug

#3430 Upgrade NodeJS to latest LTS 14.16.0 'Fermium'
  build.gradle
Labels: debt

#3451 Refactor `userActivities`
  client/src/pages/admin/Index.js
  client/src/pages/admin/UserActivityTable.js
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/userActivity/Activity.java
  src/main/java/mil/dds/anet/beans/userActivity/RecentActivities.java
  src/main/java/mil/dds/anet/beans/userActivity/UserActivity.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/utils/InsertionOrderLinkedList.java
  src/main/java/mil/dds/anet/views/ViewResponseFilter.java
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
Labels: debt

#3445 Fix report search for "pending approval of"
  client/tests/webdriver/baseSpecs/homeTiles.spec.js
  client/tests/webdriver/pages/home.page.js
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
Labels: bug

#3457 Refactor rollup GraphQL schema to use Instant instead of Long
  client/src/pages/rollup/Show.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: debt
