Repository NCI-Agency/anet, pull requests merged in 2021-07, with the labels that each got.

#3689 Add location type to simulator
  client/tests/sim/stories/LocationStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/ReportStories.js
Labels: debt

#3711 Update leaflet to v1.7.1
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3709 Update @fullcalendar dependencies to v5.8.0
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3713 Update react-tooltip to v4.2.21
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3712 Update autoprefixer to v10.3.1
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3714 Update yup to v0.32.9
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: dependencies

#3715 Update Storybook builder to webpack5
  client/.env
  client/.storybook/main.js
  client/package.json
  client/yarn.lock
Labels: dependencies

#3720 Update logback dependencies to v1.2.4
  build.gradle
Labels: dependencies

#3721 Wait for the modal to slide in before continuing the test
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
Labels: debt

#3723 Change the way report is selected from MyReports
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/baseSpecs/unpublishReport.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/myReports.page.js
  client/tests/webdriver/pages/page.js
Labels: debt

#3731 Update webdriverio dependencies to v7.8.0
  client/package.json
  client/yarn.lock
Labels: dependencies

#3728 Fix invalid dom warnings in compact view of reports
  client/src/components/Compact.js
  client/src/pages/people/Compact.js
  client/src/pages/reports/Compact.js
Labels: debt, enhancement

#3740 Update BrowserStack tests to use W3C standard capabilities
  .github/workflows/build-gradle.yml
  client/config/browserstack.config.js
  client/config/wdio.config.js
  client/tests/util/test.js
Labels: debt

#3734 Group some items in the navigation menu
  anet-dictionary.yml
  client/src/components/Nav.js
  client/src/index.css
  client/tests/e2e/home.js
  client/tests/e2e/permissions.js
  client/tests/e2e/position.js
  client/tests/util/test.js
  client/tests/webdriver/baseSpecs/myCounterparts.spec.js
  client/tests/webdriver/baseSpecs/myTasks.spec.js
  client/tests/webdriver/customFieldsSpecs/myOrg.spec.js
  client/tests/webdriver/customFieldsSpecs/notifications.spec.js
  client/tests/webdriver/pages/home.page.js
  src/main/resources/anet-schema.yml
Labels: debt
