Repository NCI-Agency/anet, pull requests merged in 2021-01, with the labels that each got.

#3381 Notify users when there is new version of ANET or ANET server is down
  anet-dictionary.yml
  build.gradle
  client/platform/utils.js
  client/platform/web-dev/settings.js
  client/src/api.js
  client/src/components/SecurityBanner.js
  client/src/connectionUtils.js
  client/src/pages/App.js
  client/tests/models/securityBanner.test.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#3376 Remove partner assessments, add conditional questions
  anet-dictionary.yml
  anet.yml
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/assessments/InstantAssessmentsContainerField.js
  client/src/components/assessments/PeriodicAssessmentResults.js
  client/src/models/Person.js
  client/src/models/Report.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/customFieldsSpecs/customFields.spec.js
  client/tests/webdriver/customFieldsSpecs/notifications.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/pages/assessments.page.js
  client/tests/webdriver/pages/createFutureReport.page.js
  client/tests/webdriver/pages/createReport.page.js
  client/tests/webdriver/pages/myCounterparts.page.js
  client/tests/webdriver/pages/myTasks.page.js
  client/tests/webdriver/pages/report/createReport.page.js
  src/main/java/mil/dds/anet/MaintenanceCommand.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/threads/PendingAssessmentsNotificationWorker.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/integration/commands/MaintenanceCommandTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#3383 Add development and storybook build tests for github workflows and fix storybook
  .github/workflows/build-gradle.yml
  client/.storybook/main.js
Labels: debt

#3377 Extend custom fields to Position, Organization, Location
  anet-dictionary.yml
  client/src/components/CustomFields.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/models/Location.js
  client/src/models/Organization.js
  client/src/models/Position.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/New.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/New.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Edit.js
  client/src/pages/people/New.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/New.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/New.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/New.js
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/database/mappers/LocationMapper.java
  src/main/java/mil/dds/anet/database/mappers/OrganizationMapper.java
  src/main/java/mil/dds/anet/database/mappers/PositionMapper.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/views/AbstractCustomizableAnetBean.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
Labels: enhancement

#3357 Unique assessments per period
  client/src/components/assessments/PeriodicAssessmentResults.js
  client/src/pages/people/Show.js
  client/src/periodUtils.js
  client/tests/webdriver/baseSpecs/assessmentsForPeople.spec.js
  client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
  client/tests/webdriver/pages/report/editReport.page.js
  client/tests/webdriver/pages/search.page.js
  client/tests/webdriver/pages/showPerson.page.js
  client/tests/webdriver/pages/showTask.page.js
  insertBaseData-mssql.sql
  mssql2pg.pl
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/resources/NoteResource.java
Labels: enhancement

#3391 Fix assessment tests
  client/tests/webdriver/baseSpecs/assessmentsForPeople.spec.js
  client/tests/webdriver/customFieldsSpecs/notifications.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/pages/myCounterparts.page.js
  client/tests/webdriver/pages/showPerson.page.js
Labels: debt

#3399 Fix future engagement worker
  src/main/java/mil/dds/anet/beans/ApprovalStep.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/db/ReportPublicationWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/utils/TestBeans.java
Labels: bug

#3402 Fix KML and NVG exports
  client/src/exportUtils.js
  src/main/resources/stylesheets/kml.xslt
  src/main/resources/stylesheets/nvg.xslt
Labels: bug
