Repository NCI-Agency/anet, pull requests merged in 2021-04, with the labels that each got.

#3506 Force super users to enter a location for advisor positions
  client/src/models/Position.js
  client/tests/webdriver/baseSpecs/createNewPosition.spec.js
  client/tests/webdriver/pages/createNewPosition.page.js
  insertBaseData-mssql.sql
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
Labels: enhancement

#3523 Use correct label for principal organization identificationCode field
  client/src/models/Organization.js
Labels: bug

#3524 Fix notes and map errors when merging positions
  client/src/models/Position.js
  client/src/pages/admin/MergePositions.js
Labels: bug

#3256 Add selection feature for dynamically selecting location format
  client/src/models/Location.js
  client/src/pages/locations/GeoLocation.js
  client/tests/models/geoLocation.test.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#3527 Show absolute date/time on periodic assessments and report comments
  client/src/components/assessments/PeriodicAssessmentResults.js
  client/src/pages/reports/Show.js
Labels: enhancement

#3534 Improve and extend merge for locations object
  client/src/components/ApprovalSteps.js
  client/src/components/GeoLocation.js
  client/src/components/Nav.js
  client/src/components/approvals/ApprovalsDefinition.js
  client/src/mergeUtils.js
  client/src/models/Location.js
  client/src/pages/Routing.js
  client/src/pages/admin/MergeLocations.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/tests/models/geoLocation.test.js
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/pages/mergeLocations.page.js
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/resources/anet.graphql
Labels: feature

#3540 Svg version of ANET logo is needed to prevent distortion of the image in different sizes.
  client/src/components/Header.js
  client/src/pages/reports/Compact.js
  client/src/resources/anet-menu.svg
  client/src/resources/logo.svg
  src/main/resources/assets/img/anet-circle.svg
  src/main/resources/assets/img/anet.svg
  src/main/resources/stylesheets/kml.xslt
Labels: enhancement

#3514 Fix formCustomFields error when creating objects
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/Model.js
  client/src/components/approvals/ApprovalsDefinition.js
  client/src/models/Location.js
  client/src/models/Position.js
  client/src/pages/admin/MergePositions.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/locations/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/tasks/Form.js
Labels: bug

#3496 Add a back to draft capability for published reports
  anet-dictionary.yml
  client/src/components/ConfirmDestructive.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ReportWorkflow.js
  client/src/components/assessments/PeriodicAssessmentResults.js
  client/src/pages/Home.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/baseSpecs/unpublishReport.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/myReports.page.js
  client/tests/webdriver/pages/report/editReport.page.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/beans/ReportAction.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: feature

#3532 Update permissions
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/models/Position.js
  client/tests/e2e/position.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/resources/migrations.xml
Labels: enhancement

#3554 Improve eslint
  client/package.json
  client/src/components/AssignPersonModal.js
  client/yarn.lock
Labels: debt

#3558 Fix ANET init command
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: bug
