Repository NCI-Agency/anet, pull requests merged in 2021-12, with the labels that each got.

#3334 Add preview feature to links for ANET objects
  .github/renovate.json
  client/src/components/AssignPersonModal.js
  client/src/components/AssignPositionModal.js
  client/src/components/AvatarDisplayComponent.js
  client/src/components/BlueprintOverrides.css
  client/src/components/EditAssociatedPositionsModal.js
  client/src/components/FieldHelper.js
  client/src/components/Kanban.js
  client/src/components/LinkTo.js
  client/src/components/Model.js
  client/src/components/ModelTooltip.css
  client/src/components/ModelTooltip.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/components/editor/LinkAnet.js
  client/src/components/previews/AuthorizationGroupPreview.js
  client/src/components/previews/LocationPreview.js
  client/src/components/previews/ModelPreview.css
  client/src/components/previews/ModelPreview.js
  client/src/components/previews/OrganizationPreview.js
  client/src/components/previews/PersonPreview.js
  client/src/components/previews/PositionPreview.js
  client/src/components/previews/PreviewComponentFactory.js
  client/src/components/previews/RegisterPreviewComponents.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/pages/App.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/people/PreviousPositions.js
  client/src/pages/reports/AuthorizationGroupTable.js
  client/tests/webdriver/pages/createFutureReport.page.js
  client/tests/webdriver/pages/mergeLocations.page.js
  client/tests/webdriver/pages/mergePositions.page.js
  client/tests/webdriver/pages/report/createReport.page.js
Labels: feature

#3935 Update several non-major dependencies
  build.gradle
  client/package.json
  client/tests/webdriver/baseSpecs/createNewLocation.spec.js
  client/tests/webdriver/baseSpecs/createNewPerson.spec.js
  client/tests/webdriver/baseSpecs/editLocation.spec.js
  client/tests/webdriver/baseSpecs/unpublishReport.spec.js
  client/tests/webdriver/customFieldsSpecs/customSensitiveFields.spec.js
  client/yarn.lock
Labels: dependencies

#3936 Uniquely identify assessments in the dictionary by key
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/components/assessments/AssessmentResultsContainer.js
  client/src/models/Person.js
  client/src/models/Task.js
  client/src/pages/dashboards/DiagramNode.js
  src/main/java/mil/dds/anet/MaintenanceCommand.java
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#3937 Allow on-demand assessment expiration to be specified per assessment definition
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/components/assessments/OnDemandAssessments/OndemandAssessment.js
  client/src/components/assessments/OnDemandAssessments/ValidationBar.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#3938 Make sure buttons are disabled when they should be
  client/src/components/FieldHelper.js
  client/tests/e2e/permissions.js
Labels: bug

#3939 Update several non-major dependencies
  build.gradle
  client/package.json
  client/yarn.lock
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#3940 Update log4j2
  build.gradle
Labels: dependencies, security

#3943 Update several non-major dependencies
  build.gradle
  client/package.json
  client/yarn.lock
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#3944 Update to Keycloak 16.1.0
  ANET-Realm-export.json
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies
