Repository NCI-Agency/anet, pull requests merged in 2021-03, with the labels that each got.

#3415 Add an Insight showing the positions that have pending assessments
  client/src/components/Nav.js
  client/src/components/PendingAssessmentsByPosition.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/CheckboxFilter.js
  client/src/notificationsUtils.js
  client/src/pages/App.js
  client/src/pages/insights/Show.js
  client/src/pages/positions/MyCounterparts.js
  client/src/pages/tasks/MyTasks.js
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/MaintenanceCommand.java
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/IPositionSearcher.java
  src/main/java/mil/dds/anet/threads/PendingAssessmentsNotificationWorker.java
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/test/java/mil/dds/anet/test/integration/commands/MaintenanceCommandTest.java
  src/test/java/mil/dds/anet/test/integration/db/PendingAssessmentsNotificationWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlHelper.java
Labels: enhancement

#3471 Enable editing maxCharLength for some text fields
  anet-dictionary.yml
  client/src/components/ReportSummary.js
  client/src/models/Report.js
  client/src/pages/HopscotchTour.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/utils.js
  docs/INSTALL.md
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/rollup.ftlh
  testDictionaries/no-custom-fields.yml
Labels: enhancement, feature

#3479 Update jsonpath-plus
  anet-dictionary.yml
  client/package.json
  client/yarn.lock
Labels: debt, dependencies, javascript

#3483 Fix editing associated positions
  client/src/components/EditAssociatedPositionsModal.js
Labels: bug

#3147 Improve and extend merge for positions object
  client/src/components/EditHistory.css
  client/src/components/EditHistory.js
  client/src/components/MergeField.js
  client/src/components/Model.js
  client/src/components/Nav.js
  client/src/mergeUtils.js
  client/src/models/Position.js
  client/src/pages/Routing.js
  client/src/pages/admin/MergePositions.js
  client/src/pages/positions/AssociatedPositions.js
  client/src/pages/positions/PreviousPeople.js
  client/src/pages/positions/Show.js
  client/src/periodUtils.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
  client/tests/webdriver/pages/mergePositions.page.js
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: feature, priority

#3505 Show absolute date/time on notes instead of relative
  client/src/components/RelatedObjectNotes.js
Labels: enhancement, feature

#3484 Refactor GraphQL tests
  .github/renovate.json
  build.gradle
  client/.graphqlconfig.yaml
  client/package.json
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/positions/Form.js
  client/yarn.lock
  docs/dev-setup.md
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/beans/search/AbstractSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/graphql/DateTimeMapper.java
  src/main/java/mil/dds/anet/graphql/GraphQlDateTimeType.java
  src/test/java/mil/dds/anet/test/RandomTests.java
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/beans/ApprovalStepTest.java
  src/test/java/mil/dds/anet/test/beans/AuthorizationGroupTest.java
  src/test/java/mil/dds/anet/test/beans/BeanTester.java
  src/test/java/mil/dds/anet/test/beans/OrganizationTest.java
  src/test/java/mil/dds/anet/test/beans/PersonTest.java
  src/test/java/mil/dds/anet/test/beans/PositionTest.java
  src/test/java/mil/dds/anet/test/beans/ReportTest.java
  src/test/java/mil/dds/anet/test/beans/TaskTest.java
  src/test/java/mil/dds/anet/test/integration/commands/MaintenanceCommandTest.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/db/ReportPublicationWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SavedSearchResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlClient.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlData.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlHelper.java
  src/test/java/mil/dds/anet/test/resources/utils/GraphQlResponse.java
  src/test/resources/anet.graphql
  src/test/resources/testJson/approvalSteps/testStep.json
  src/test/resources/testJson/authorizationGroups/test.json
  src/test/resources/testJson/organizations/test.json
  src/test/resources/testJson/people/jack.json
  src/test/resources/testJson/positions/testPosition.json
  src/test/resources/testJson/reports/test.json
  src/test/resources/testJson/tags/test.json
  src/test/resources/testJson/task/testTask.json
Labels: debt

#3511 Remove obsolete step from CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: debt

#3390 Add similarity feature to avoid duplicate object creation
  client/src/components/LocationTable.js
  client/src/components/PersonTable.js
  client/src/components/SimilarObjectsModal.js
  client/src/pages/Search.js
  client/src/pages/locations/Form.js
  client/src/pages/people/Form.js
  client/src/pages/positions/Form.js
  client/tests/webdriver/baseSpecs/createNewLocation.spec.js
  client/tests/webdriver/baseSpecs/createNewPerson.spec.js
  client/tests/webdriver/baseSpecs/createNewPosition.spec.js
  client/tests/webdriver/baseSpecs/locationUtils.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/createNewPosition.page.js
  client/tests/webdriver/pages/location/createNewLocation.page.js
Labels: feature

#3330 Enhance person view and make ANET more responsive
  anet-dictionary.yml
  client/src/components/AdvancedSearch.js
  client/src/components/CustomFields.js
  client/src/components/FieldHelper.js
  client/src/components/Fieldset.js
  client/src/components/Kanban.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/ReportCollection.js
  client/src/components/ReportTable.js
  client/src/components/ResponsiveLayout.js
  client/src/components/SearchBar.js
  client/src/components/assessments/AssessmentResultsContainer.js
  client/src/index.css
  client/src/models/Person.js
  client/src/pages/HopscotchTour.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/rollup/Show.js
  client/src/periodUtils.js
  client/tests/e2e/position.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement, feature
