Repository NCI-Agency/anet, pull requests merged in 2021-09, with the labels that each got.

#3814 Ensure location types fits all missions
  anet-dictionary.yml
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/pages/locations/Form.js
  client/src/pages/positions/Form.js
  client/src/pages/reports/Form.js
  client/tests/e2e/report.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement, feature

#3841 Log JavaScript initialization errors
  client/src/index-auth.js
Labels: enhancement

#3862 Add hot reload configuration for webpack 5
  client/config/webpack.client.dev.js
Labels: DevOps

#3863 Add the Azure Boards badge to the README
  README.md
Labels: debt

#3857 Reserve pinpoint locations term for user pinned location
  anet-dictionary.yml
  client/src/components/SearchFilters.js
  client/src/models/Location.js
  client/src/pages/locations/Form.js
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: enhancement, Sprint 9

#3873 Configure general banner through dropdown fields
  client/src/components/GeneralBanner.js
  client/src/components/TopBar.js
  client/src/pages/admin/Index.js
Labels: enhancement

#3848 Allow assessments for advisors
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/components/assessments/InstantAssessmentsContainerField.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  insertBaseData-mssql.sql
  src/main/resources/anet-schema.yml
Labels: enhancement

#3758 Allow admins to edit people/position history
  client/src/components/CustomDateInput.js
  client/src/components/EditHistory.css
  client/src/components/EditHistory.js
  client/src/components/ReportStatistics.js
  client/src/components/aggregations/AggregationWidgetContainer.js
  client/src/index.css
  client/src/models/Position.js
  client/src/pages/admin/MergePositions.js
  client/src/pages/dashboards/DiagramNode.js
  client/src/pages/people/PreviousPositions.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Show.js
  insertBaseData-mssql.sql
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/utils/ResourceUtils.java
  src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/java/mil/dds/anet/test/utils/ResourceUtilsTest.java
  src/test/java/mil/dds/anet/test/utils/UtilsTest.java
  src/test/resources/anet.graphql
Labels: enhancement
