Repository NCI-Agency/anet, pull requests merged in 2021-05, with the labels that each got.

#3566 Lift calendar up from the other DOM elements
  client/src/components/BlueprintOverrides.css
  client/src/components/CustomDateInput.js
  client/src/components/advancedSearch/DateRangeFilter.js
Labels: bug

#3568 Fix reports insights
  client/src/pages/insights/Show.js
  client/tests/webdriver/baseSpecs/insights.spec.js
  client/tests/webdriver/pages/insights.page.js
Labels: bug

#3598 Add client-side tests for custom sensitive information
  client/tests/webdriver/customFieldsSpecs/customSensitiveFields.spec.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/showPerson.page.js
Labels: debt

#3617 Sanitize JSON before storing it
  src/main/java/mil/dds/anet/database/CustomSensitiveInformationDao.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
Labels: enhancement

#3589 Update @fullcalendar dependencies to v5.7.0
  client/package.json
  client/src/components/Calendar.css
  client/src/components/Calendar.js
  client/src/components/aggregations/CalendarWidget.js
  client/src/index.css
  client/tests/webdriver/customFieldsSpecs/myOrg.spec.js
  client/yarn.lock
Labels: debt

#3623 Update sim
  client/tests/sim/scenarios/users/userTypes.js
  client/tests/sim/stories/LocationStories.js
  client/tests/sim/stories/NoteStories.js
  client/tests/sim/stories/OrganizationStories.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/ReportStories.js
Labels: debt

#3612 Update io.dropwizard dependencies to v2.0.22
  build.gradle
Labels: dependencies

#3624 Fix advanced selects inside advanced search
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/index.css
Labels: bug
