Repository NCI-Agency/anet, pull requests merged in 2022-03, with the labels that each got.

#3977 Update to latest Node.js v14 and Yarn v1
  build.gradle
Labels: debt

#3984 Assessment titles can be configured through the dictionary
  anet-dictionary.yml
  client/src/components/assessments/AssessmentResultsTable.js
  client/src/components/assessments/OnDemandAssessments/OndemandAssessment.js
  client/src/components/assessments/PeriodicAssessmentResults.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#3965 Remove MS SQL Server support
  .github/renovate.json
  .github/workflows/build-gradle.yml
  .gitignore
  build.gradle
  client/tests/util/test.js
  docker/README.md
  docker/anet-mssql-linux/Dockerfile
  docker/anet-mssql-linux/README.md
  docker/anet-mssql-linux/entrypoint.sh
  docker/anet-mssql-linux/waitTillServiceStarted.sh
  docs/dev-setup.md
  examples/README.md
  examples/simpleContainerDemo/anet.yml
  examples/simpleContainerDemo/docker-compose.yml
  examples/simpleContainerDemo/insertBaseData.sql
  insertBaseData-mssql.sql
  insertBaseData-psql.sql
  mssql2pg.pl
  prepare-mssql.sql
  src/main/java/mil/dds/anet/WaitForDbCommand.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/MapperUtils.java
  src/main/java/mil/dds/anet/search/Searcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlLocationSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPersonSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlPositionSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSubscriptionSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlSubscriptionUpdateSearcher.java
  src/main/java/mil/dds/anet/search/mssql/MssqlTaskSearcher.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/DaoUtilsTest.java
Labels: debt, DevOps

#3986 Fix external documentation link
  client/src/components/Nav.js
Labels: bug

#3982 Allow editing deprecated fields
  anet-dictionary.yml
  client/src/components/CustomFields.js
Labels: enhancement

#3976 Show attendee options in single column
  client/src/components/CustomFields.js
  client/src/index.css
  client/src/pages/reports/ReportPeople.css
  client/src/pages/reports/ReportPeople.js
  client/tests/e2e/report.js
Labels: enhancement

#3988 Hide engagement information field if empty
  client/src/components/CustomFields.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
Labels: enhancement

#3987 Show only summary in rollup
  client/src/components/MosaicLayout.js
  client/src/pages/rollup/Show.js
Labels: enhancement
