Repository NCI-Agency/anet, pull requests merged in 2022-02, with the labels that each got.

#3956 Run Renovate every day
  .github/renovate.json
Labels: DevOps

#3503 Improve development documentation: DB container initialization
  docs/dev-setup.md
Labels: debt

#3955 Singular column titles for advisor attendee attributes
  client/src/pages/reports/ReportPeople.js
Labels: enhancement

#3968 Push Gradle to 7.4 and update plugins
  .github/renovate.json
  ANET-Realm-export.json
  build.gradle
  export-anet-realm.sh
  gradle/wrapper/gradle-wrapper.properties
Labels: debt

#3957 Replace "Add" hyperlink with button
  client/src/components/FieldHelper.js
  client/src/index.css
Labels: enhancement

#3958 Exclude selected items from proposed recents list
  client/src/pages/reports/Form.js
  client/yarn.lock
Labels: enhancement

#3959 Add ability to define custom attendee search groups
  anet-dictionary.yml
  client/src/pages/reports/Form.js
  insertBaseData-mssql.sql
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement
