Repository NCI-Agency/anet, pull requests merged in 2022-10, with the labels that each got.

#4098 Fix text field bug
  client/src/components/RichTextEditor.js
  insertBaseData-psql.sql
Labels: bug

#4099 Update browserslist db
  client/yarn.lock
Labels: dependencies

#4120 Fix related object notes bug
  client/src/components/RelatedObjectNotes.js
Labels: bug

#4111 Show usage over time
  client/src/actions/index.js
  client/src/components/Nav.js
  client/src/constants/ActionTypes.js
  client/src/pages/Routing.js
  client/src/pages/admin/merge/MergeLocations.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/admin/useractivities/UserActivitiesOverTime.js
  client/src/pages/admin/useractivities/UserActivitiesPerPeriod.js
  client/src/reducers/index.js
  client/src/reducers/userActivitiesState.js
  client/tests/webdriver/pages/mergeLocations.page.js
  client/tests/webdriver/pages/mergePeople.page.js
  client/tests/webdriver/pages/mergePositions.page.js
  src/main/java/mil/dds/anet/beans/search/UserActivitySearchQuery.java
  src/main/java/mil/dds/anet/beans/search/UserActivitySearchSortBy.java
  src/main/java/mil/dds/anet/search/AbstractUserActivitySearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlUserActivitySearcher.java
  src/test/resources/anet.graphql
Labels: feature

#4126 Update most non-major Java dependencies
  .github/actions/build-cache/action.yml
  .github/renovate.json
  .github/workflows/build-gradle.yml
  build.gradle
Labels: dependencies
