Repository NCI-Agency/anet, pull requests merged in 2022-12, with the labels that each got.

#4139 Allow to write an engagement report without a principal participating in the meeting
  client/src/components/ReportSummary.js
  client/src/models/Report.js
  client/src/pages/reports/Compact.js
  client/tests/webdriver/baseSpecs/createReportWithoutPrincipal.spec.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/richTextField.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/baseSpecs/unpublishReport.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/myReports.page.js
  client/tests/webdriver/pages/page.js
  client/tests/webdriver/pages/report/createReport.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/pages/search.page.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: enhancement

#4186 Upgrade faker
  client/package.json
  client/tests/sim/Simulator.js
  client/tests/sim/scenarios/users/userTypes.js
  client/tests/sim/stories/LocationStories.js
  client/tests/sim/stories/NoteStories.js
  client/tests/sim/stories/OrganizationStories.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/ReportStories.js
  client/yarn.lock
Labels: debt, dependencies, internal

#4173 Explain ANET roles
  client/.storybook/main.js
  client/package.json
  client/stories/0-general/1-userRoles.stories.mdx
  client/stories/0-general/authorizationForNotes.stories.mdx
  client/stories/1-user/linguistAssessments.stories.mdx
  client/stories/3-admin/newTask.stories.mdx
Labels: debt, documentation

#4145 Allow picking people with different roles when merging
  client/src/components/EditHistory.js
  client/src/components/RemoveButton.js
  client/src/mergeUtils.js
  client/src/models/Report.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/baseSpecs/createReportWithoutPrincipal.spec.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/baseSpecs/userLogin.spec.js
  client/tests/webdriver/pages/mergePeople.page.js
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/test/java/mil/dds/anet/test/resources/merge/PersonMergeTest.java
Labels: enhancement
