Repository NCI-Agency/anet, pull requests merged in 2022-11, with the labels that each got.

#4121 Utilize the HTML page title
  client/src/components/AdvisorReports/FilterableAdvisorReportsTable.js
  client/src/components/CancelledEngagementReports.js
  client/src/components/FutureEngagementsByLocation.js
  client/src/components/MySubscriptions.js
  client/src/components/Page.js
  client/src/components/PendingApprovalReports.js
  client/src/components/PendingAssessmentsByPosition.js
  client/src/components/ReportsByDayOfWeek.js
  client/src/components/ReportsByTask.js
  client/src/pages/GraphiQL.js
  client/src/pages/Help.js
  client/src/pages/Home.js
  client/src/pages/PageMissing.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/Index.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/New.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/admin/merge/MergeLocations.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/admin/useractivities/UserActivitiesOverTime.js
  client/src/pages/admin/useractivities/UserActivitiesPerPeriod.js
  client/src/pages/dashboards/BoardDashboard.js
  client/src/pages/dashboards/DecisivesDashboard.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/locations/Edit.js
  client/src/pages/locations/New.js
  client/src/pages/locations/Show.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/onboarding/Show.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/New.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Compact.js
  client/src/pages/people/Edit.js
  client/src/pages/people/New.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/MyCounterparts.js
  client/src/pages/positions/New.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/MyReports.js
  client/src/pages/reports/New.js
  client/src/pages/reports/Show.js
  client/src/pages/rollup/Show.js
  client/src/pages/searches/MySavedSearches.js
  client/src/pages/searches/Search.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/MyTasks.js
  client/src/pages/tasks/New.js
  client/src/pages/tasks/Show.js
Labels: enhancement

#4140 Fix intermittently failing custom fields test
  client/tests/webdriver/customFieldsSpecs/customFields.spec.js
Labels: debt

#4127 Make rich text headings smaller
  client/src/components/CustomFields.js
  client/src/components/MergeField.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/editor/RichTextEditor.css
  client/src/components/previews/PersonPreview.js
  client/src/components/previews/ReportPreview.js
  client/src/index.css
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/people/Compact.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Show.js
Labels: enhancement

#3983 Do not sort attendees when editing
  client/src/components/previews/ReportPreview.js
  client/src/models/Report.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/ReportPeople.js
  client/src/pages/reports/Show.js
Labels: enhancement

#4144 Fix test report including two primary attendees
  insertBaseData-psql.sql
Labels: bug, internal

#4125 Fix problems with position history
  client/src/components/AssignPersonModal.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/PersonPositionHistory.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/resources/migrations.xml
Labels: bug

#4142 Rename Gradle group `database` to `database runtime`
  build.gradle
Labels: DevOps

#4146 Upgrade Keycloak to 20.0.1
  anet.yml
  build.gradle
  client/package.json
  client/yarn.lock
  keycloak/import/ANET-realm.json
Labels: debt

#4148 Minor client-side fixes
  client/package.json
  client/src/components/Nav.js
  client/yarn.lock
Labels: debt

#4152 Fix typos in the SUM document
  client/stories/1-user/draftEngagement.stories.mdx
  client/stories/1-user/reviewingReports.stories.mdx
Labels: documentation

#4149 Update leaflet
  client/package.json
  client/yarn.lock
Labels: dependencies

#3971 Allow super users to edit organisations they are responsible for
  anet-dictionary.yml
  client/src/components/EditAdministratingPositionsModal.js
  client/src/components/EditOrganizationsAdministratedModal.js
  client/src/components/previews/OrganizationPreview.js
  client/src/components/previews/PersonPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/models/Person.js
  client/src/models/Position.js
  client/src/pages/App.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/OrganizationsAdministrated.js
  client/src/pages/positions/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/permissions.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4160 Update most minor dependencies
  .github/renovate.json
  build.gradle
  client/package.json
  client/yarn.lock
Labels: dependencies, DevOps

#4128 Redesign Security Banner and move logout button to banner
  client/.storybook/preview-body.html
  client/package.json
  client/public/index.hbs
  client/src/components/Compact.js
  client/src/components/Nav.js
  client/src/components/SecurityBanner.js
  client/src/components/TopBar.js
  client/src/components/previews/OrganizationPreview.js
  client/src/utils.js
  client/tests/models/securityBanner.test.js
  client/tests/webdriver/baseSpecs/createNewPosition.spec.js
  client/tests/webdriver/baseSpecs/myCounterparts.spec.js
  client/tests/webdriver/baseSpecs/myTasks.spec.js
  client/tests/webdriver/baseSpecs/onboardNewUser.spec.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/userLogin.spec.js
  client/tests/webdriver/customFieldsSpecs/customSensitiveFields.spec.js
  client/tests/webdriver/noCustomFieldsSpecs/anetObjectForms.spec.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/page.js
  client/yarn.lock
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/InitializationCommand.java
  src/main/java/mil/dds/anet/database/AdminDao.java
  src/main/java/mil/dds/anet/resources/HomeResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/views/IndexView.java
  src/main/resources/emails/accountDeactivation.ftlh
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/deactivationWarning.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/futureEngagementUpdated.ftlh
  src/main/resources/emails/newReportComment.ftlh
  src/main/resources/emails/pendingAssessmentsNotification.ftlh
  src/main/resources/emails/reportEdited.ftlh
  src/main/resources/emails/reportPublished.ftlh
  src/main/resources/emails/reportRejection.ftlh
  src/main/resources/emails/rollup.ftlh
  src/main/resources/migrations.xml
Labels: enhancement
