Repository NCI-Agency/anet, pull requests merged in 2022-06, with the labels that each got.

#4021 Fix ie 11 tests
  client/config/browserstack.config.js
  client/tests/webdriver/pages/page.js
Labels: debt

#4025 Search behaviour changes
  client/src/components/AdvancedSearch.js
  client/src/components/SearchFilters.js
  client/src/pages/insights/Show.js
  client/src/pages/searches/Search.js
Labels: enhancement

#4039 Run ShiftLeft on push only to main
  .github/workflows/shiftleft-analysis.yml
Labels: debt, DevOps

#4045 Update leaflet and leaflet-geosearch
  .github/renovate.json
  client/package.json
  client/yarn.lock
Labels: debt, DevOps
