Repository NCI-Agency/anet, pull requests merged in 2023-06, with the labels that each got.

#4365 Make all draft reports accessible to admins
  client/src/pages/reports/Show.js
  client/tests/webdriver/baseSpecs/createReportWithPlanningConflict.spec.js
  client/tests/webdriver/baseSpecs/createReportWithoutPrincipal.spec.js
  client/tests/webdriver/baseSpecs/homeTiles.spec.js
  client/tests/webdriver/baseSpecs/submitReport.spec.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/pages/search.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: enhancement

#4355 Update SUM document for superuser permission
  client/stories/0-general/1-userRoles.stories.mdx
Labels: documentation

#4349 Provide position roles for an organization
  anet-dictionary.yml
  client/src/components/PendingAssessmentsByPosition.js
  client/src/components/PersonTable.js
  client/src/components/PositionTable.js
  client/src/components/previews/AuthorizationGroupPreview.js
  client/src/components/previews/OrganizationPreview.js
  client/src/components/previews/PersonPreview.js
  client/src/components/previews/PositionPreview.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/exportUtils.js
  client/src/models/Person.js
  client/src/models/Position.js
  client/src/pages/App.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Compact.js
  client/src/pages/people/Edit.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Edit.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Show.js
  client/src/pages/searches/Search.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/position.js
  client/tests/sim/stories/PositionStories.js
  client/tests/util/test.js
  client/tests/webdriver/baseSpecs/createNewPosition.spec.js
  client/tests/webdriver/pages/createNewPosition.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/mappers/PositionMapper.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SubscriptionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PersonMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PositionMergeTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: feature

#4380 Filter out non-applicable assessments
  client/src/components/Model.js
  client/src/components/assessments/AssessmentResultsContainer.js
  client/src/notificationsUtils.js
  client/src/pages/tasks/Show.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/pages/myCounterparts.page.js
  client/tests/webdriver/pages/myTasks.page.js
Labels: improvement

#4376 Distinguish between absent and empty authorizationGroupUuids
  anet-dictionary.yml
  client/stories/0-general/authorizationForNotes.stories.mdx
  client/stories/0-general/sensitiveInformation.stories.mdx
  src/main/java/mil/dds/anet/database/CustomSensitiveInformationDao.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4382 Include cancelled reports in the Daily Rollup
  client/src/pages/rollup/Show.js
Labels: enhancement
