Repository NCI-Agency/anet, pull requests merged in 2023-07, with the labels that each got.

#4378 Document build ANET RPM using containers
  docs/BUILD.md
Labels: documentation

#4397 Fix SVG export
  client/src/components/graphs/SVGCanvas.js
Labels: bug

#4390 Ensure classification can be defined dynamically
  anet-dictionary.yml
  client/src/components/Attachment/UploadAttachment.js
  client/src/models/Attachment.js
  client/src/pages/attachments/Form.js
  client/src/pages/attachments/Show.js
  client/tests/webdriver/baseSpecs/showAttachment.spec.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Attachment.java
  src/main/java/mil/dds/anet/database/AttachmentDao.java
  src/main/java/mil/dds/anet/database/mappers/AttachmentMapper.java
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4404 Merge position role
  client/src/pages/admin/merge/MergePositions.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
  insertBaseData-psql.sql
Labels: improvement

#4410 Remove chalk
  client/package.json
  client/tests/util/test.js
  client/yarn.lock
Labels: devDependencies

#4366 Summarize the leaders of organizations
  anet-dictionary.yml
  client/src/components/previews/OrganizationPreview.js
  client/src/models/Position.js
  client/src/pages/organizations/Show.js
  client/src/positionUtil.js
  client/tests/webdriver/baseSpecs/showOrganization.spec.js
  client/tests/webdriver/pages/search.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4416 Check the Javascript code formatting during the build
  .github/workflows/build-gradle.yml
  build.gradle
  client/package.json
Labels: DevOps, internal

#4413 Allow webp images for attachments and avatars
  anet-dictionary.yml
  client/src/components/AvatarComponent.js
  testDictionaries/no-custom-fields.yml
Labels: improvement
