Repository NCI-Agency/anet, pull requests merged in 2023-03, with the labels that each got.

#4264 Update to graphql-java 20
  build.gradle
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
Labels: dependencies

#4265 Update to the new namespace and latest version of the ospackage plugin
  build.gradle
Labels: DevOps

#4247 Replace JSON schema validator
  build.gradle
  src/main/java/mil/dds/anet/config/AnetConfiguration.java
  src/main/resources/anet-schema.yml
Labels: dependencies

#4261 Improve tasks
  anet-dictionary.yml
  client/src/components/Kanban.js
  client/src/components/NoPaginationTaskTable.js
  client/src/components/PendingAssessmentsByPosition.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/OrganizationFilter.js
  client/src/components/advancedSearch/TaskFilter.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/exportUtils.js
  client/src/models/Task.js
  client/src/pages/App.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/webdriver/baseSpecs/advancedSearch.spec.js
  docs/anet.yml.production.template
  insertBaseData-psql.sql
  requoteSqlIdentifiers.pl
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/database/mappers/TaskMapper.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/resources/anet.graphql
  src/test/resources/graphQLTests/appQuery.gql
  src/test/resources/graphQLTests/orgShow.gql
  src/test/resources/graphQLTests/person.gql
  src/test/resources/graphQLTests/positions.gql
  src/test/resources/graphQLTests/report.gql
  src/test/resources/graphQLTests/taskShow.gql
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4267 Refactor OrganizationFilter to always search in children
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/OrganizationFilter.js
Labels: enhancement

#4283 Replace Yes/No SelectFilters with a new RadioButtonFilter
  client/src/components/SearchFilters.js
  client/src/components/advancedSearch/RadioButtonFilter.js
Labels: improvement

#4257 Update dbInit to run with default arguments
  build.gradle
  docs/INSTALL.md
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: enhancement, DevOps

#4278 Add breadcrumb trail for tasks
  client/src/components/BreadcrumbTrail.js
  client/src/components/FieldHelper.js
  client/src/components/Kanban.js
  client/src/components/NoPaginationTaskTable.js
  client/src/components/PendingAssessmentsByPosition.js
  client/src/components/ReportSummary.js
  client/src/components/SearchFilters.js
  client/src/components/TaskTable.js
  client/src/components/advancedSearch/AdvancedSelectFilter.js
  client/src/components/advancedSearch/TaskFilter.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayTable.js
  client/src/components/advancedSelectWidget/AdvancedSingleSelect.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/assessments/instant/InstantAssessmentsContainerField.js
  client/src/components/assessments/periodic/PeriodicAssessmentResultsTable.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/index.css
  client/src/models/Task.js
  client/src/pages/App.js
  client/src/pages/dashboards/KanbanDashboard.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/OrganizationTasks.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/searches/Search.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/report.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/customFieldsSpecs/createFutureReport.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
  src/test/resources/graphQLTests/appQuery.gql
  src/test/resources/graphQLTests/taskShow.gql
Labels: enhancement

#4301 Correct default classification
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: improvement

#4259 Be able to sign-out
  client/public/favicon/logo.svg
  client/public/logout.html
  client/src/components/Compact.js
  client/src/components/Header.js
  client/tests/webdriver/baseSpecs/userLogin.spec.js
  client/tests/webdriver/pages/home.page.js
  src/main/java/mil/dds/anet/resources/HomeResource.java
Labels: improvement

#4271 Hide parent task if no parent task, and show sub tasks
  anet-dictionary.yml
  client/src/components/previews/TaskPreview.js
  client/src/pages/tasks/Show.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/pages/showTask.page.js
  src/main/resources/anet-schema.yml
Labels: enhancement

#4307 Open external links in the rich-text editor in a new tab
  client/src/components/editor/LinkExternalHref.js
Labels: improvement

#4310 Correct error handling of duplicate position code
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
Labels: bug
