Repository NCI-Agency/anet, pull requests merged in 2023-10, with the labels that each got.

#4369 Be able to upload attachment to Location
  anet-dictionary.yml
  client/src/components/Attachment/Attachment.css
  client/src/components/Attachment/AttachmentCard.js
  client/src/components/Attachment/UploadAttachment.js
  client/src/components/previews/AttachmentPreview.js
  client/src/pages/attachments/Edit.js
  client/src/pages/attachments/Form.js
  client/src/pages/attachments/Show.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/pages/attachment/showAttachment.page.js
  client/tests/webdriver/pages/location/showLocation.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4513 Rename Babel config for Jest
  client/babel.config.js
  client/jest.config.js
  client/package.json
  client/yarn.lock
Labels: internal

#4501 Add missing initialization of position role to init command
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: bug

#4522 Warn the user when the default approval workflow has not been defined
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ReportDao.java
Labels: bug

#4526 Add some tests for when the default approval workflow has not been defined
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: debt, internal

#4497 Add people and organizations to authorization groups
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectsTable.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/previews/AuthorizationGroupPreview.js
  client/src/models/AuthorizationGroup.js
  client/src/models/Person.js
  client/src/notificationsUtils.js
  client/src/pages/App.js
  client/src/pages/admin/AuthorizationGroupTable.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/stories/3-admin/authorizationGroups.stories.mdx
  client/tests/webdriver/baseSpecs/createAuthorizationGroup.spec.js
  client/tests/webdriver/customFieldsSpecs/notifications.spec.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Attachment.java
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/GenericRelatedObject.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/beans/NoteRelatedObject.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/AttachmentDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/CustomSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/mappers/AttachmentRelatedObjectMapper.java
  src/main/java/mil/dds/anet/database/mappers/GenericRelatedObjectMapper.java
  src/main/java/mil/dds/anet/database/mappers/NoteRelatedObjectMapper.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SubscriptionUpdateResourceTest.java
  src/test/resources/anet.graphql
  src/test/resources/graphQLTests/appQuery.gql
  src/test/resources/graphQLTests/authorizationGroupsAll.gql
  src/test/resources/graphQLTests/orgShow.gql
  src/test/resources/graphQLTests/person.gql
  src/test/resources/graphQLTests/positions.gql
  src/test/resources/graphQLTests/report.gql
  src/test/resources/graphQLTests/taskShow.gql
Labels: enhancement

#4530 Improve the performance of the query for a person's authorizationGroups memberships
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
Labels: debt, internal
