Repository NCI-Agency/anet, pull requests merged in 2023-02, with the labels that each got.

#4227 Minor improvements related to demo database
  build.gradle
  client/src/components/Kanban.js
  client/src/components/previews/OrganizationPreview.js
  client/src/models/Organization.js
  client/src/pages/dashboards/BoardDashboard.js
  client/src/pages/dashboards/DecisivesDashboard.js
  client/src/pages/dashboards/DiagramNode.js
  client/src/pages/dashboards/KanbanDashboard.js
Labels: bug, DevOps

#4234 Refactor rich-text links
  client/src/components/RichTextEditor.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/editor/LinkAnet.js
  client/src/components/editor/LinkAnetEntity.js
  client/src/components/editor/LinkExternalHref.js
  client/src/components/editor/LinkSourceAnet.js
  client/src/components/editor/Toolbar.js
  client/src/pages/tasks/Form.js
  client/src/utils_links.js
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/utils/UtilsTest.java
Labels: improvement

#4233 Update installation documentation
  docs/INSTALL.md
Labels: DevOps, documentation

#4258 Add improvements category to release-drafter
  .github/release-drafter.yml
Labels: DevOps, documentation

#4260 Split up dependencies and debt label
  .github/release-drafter.yml
Labels: DevOps, documentation

#4263 Leave the documentation label out of the release notes
  .github/release-drafter.yml
Labels: DevOps, documentation
