Repository NCI-Agency/anet, pull requests merged in 2023-01, with the labels that each got.

#3970 AB#337: Decrease min height of the rows on the calendar
  client/src/components/Calendar.css
  client/src/components/Calendar.js
Labels: enhancement

#4190 Use engagement date in report links in rich text editor
  client/package.json
  client/src/components/CustomFields.js
  client/src/components/LinkTo.js
  client/src/components/Model.js
  client/src/components/RelatedObjectNotes.js
  client/src/components/RichTextEditor.js
  client/src/components/aggregations/utils.js
  client/src/components/editor/LinkAnet.js
  client/src/components/editor/LinkAnetEntity.js
  client/src/components/editor/RichTextEditor.css
  client/src/components/previews/PersonPreview.js
  client/src/components/previews/ReportPreview.js
  client/src/index.css
  client/src/models/Report.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/people/Compact.js
  client/src/pages/people/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Show.js
  client/tests/webdriver/baseSpecs/richTextField.spec.js
  client/tests/webdriver/baseSpecs/richTextUtils.js
  client/tests/webdriver/pages/report/editReport.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/yarn.lock
Labels: enhancement

#4202 Add missing tests for notes
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
Labels: debt

#4187 Create hyperlink in rich text editor
  client/src/components/RichTextEditor.js
  client/src/components/editor/LinkAnet.js
  client/src/components/editor/LinkSourceAnet.js
  client/src/components/editor/Toolbar.js
Labels: enhancement

#4172 Add profile to organizations
  anet-dictionary.yml
  client/src/components/SearchFilters.js
  client/src/models/Organization.js
  client/src/pages/organizations/Edit.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Show.js
  client/tests/webdriver/baseSpecs/createNewOrganization.spec.js
  client/tests/webdriver/pages/createNewOrganization.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/beans/search/OrganizationSearchQuery.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/mappers/OrganizationMapper.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4214 CI: Ability to manually start the Release-Drafter workflow
  .github/workflows/release-drafter.yml
Labels: DevOps

#4216 Deprecate functionality for note types CHANGE_RECORD and PARTNER_ASSESSMENT
  client/src/components/Model.js
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/RelatedObjectNotes.js
  client/src/pages/organizations/Show.js
  client/src/pages/tasks/Form.js
  client/tests/e2e/report.js
  client/tests/webdriver/pages/mergePeople.page.js
  client/tests/webdriver/pages/mergePositions.page.js
  src/main/java/mil/dds/anet/MaintenanceCommand.java
  src/main/java/mil/dds/anet/beans/Note.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/integration/commands/MaintenanceCommandTest.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/resources/anet.graphql
Labels: debt

#4198 Exclude some internal labels from release notes
  .github/release-drafter.yml
  .github/renovate.json
Labels: internal

#4224 Make the build cache key build-specific
  .github/actions/build-cache/action.yml
Labels: DevOps

#4215 Add missing entities to report summary
  client/src/components/Compact.js
  client/src/components/SimpleMultiCheckboxDropdown.js
  client/src/components/assessments/instant/InstantAssessmentsContainerField.js
  client/src/pages/reports/Compact.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
  insertBaseData-psql.sql
Labels: bug

#4219 Build ANET RPM in OracleLinux8 docker for Redhat8
  build.gradle
Labels: DevOps

#4189 Initialize ANET database with command-line options
  build.gradle
  src/main/java/mil/dds/anet/InitializationCommand.java
Labels: enhancement, DevOps

#4226 Update to graphql-java 19.2
  build.gradle
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/resources/anet.graphql
Labels: dependencies

#4203 Add top-level test condition to assessments
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/components/assessments/instant/InstantAssessmentsContainerField.js
  client/src/components/assessments/ondemand/OndemandAssessment.js
  client/src/components/assessments/periodic/PeriodicAssessmentResultsTable.js
  client/tests/webdriver/baseSpecs/assessmentsForPeople.spec.js
  client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement
