Repository NCI-Agency/anet, pull requests merged in 2023-08, with the labels that each got.

#4389 Superusers should be able to edit persons in their organization hierarchy
  client/src/components/AssignPositionModal.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/people/Form.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/stories/0-general/1-userRoles.stories.mdx
  client/tests/e2e/permissions.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/search/PositionSearchQuery.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
Labels: enhancement

#4377 Be able to add assessment (periodic, ondemand) to organizations
  anet-dictionary.yml
  client/src/models/Organization.js
  client/src/pages/organizations/Show.js
  client/tests/webdriver/baseSpecs/assessmentsForOrganization.spec.js
  client/tests/webdriver/pages/showOrganization.page.js
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4440 Allow administrator positions in position history editing by administrators
  client/src/components/EditHistory.js
  client/src/pages/positions/Show.js
  src/main/java/mil/dds/anet/database/EmailDao.java
  src/main/java/mil/dds/anet/database/ForeignKeyBatcher.java
  src/main/java/mil/dds/anet/database/IdBatcher.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlSearchQueryBuilder.java
Labels: bug

#4439 Remove obsolete work-around for webpack
  client/config/webpack.common.js
Labels: debt

#4430 Replace react-notification-badge
  client/package.json
  client/src/components/RelatedObjectNotes.js
  client/yarn.lock
Labels: debt

#4426 Handle links in rich-text editor during copy-paste
  client/src/components/RichTextEditor.js
  client/src/components/editor/LinkExternalHref.js
  client/src/components/editor/LinkSourceAnet.js
  client/src/utils_links.js
Labels: enhancement

#4450 Work around a chromedriver bug
  client/tests/e2e/permissions.js
  client/tests/e2e/position.js
  client/tests/e2e/report.js
  client/tests/util/test.js
Labels: internal

#4449 Show a clear message when an ANET link points to a non-existing object
  client/src/components/editor/LinkAnetEntity.js
Labels: enhancement

#4457 Improve ANET-schema for the position-role
  src/main/resources/anet-schema.yml
Labels: internal

#4444 Ability to save link element in rich-text editor without plain text
  client/src/components/RichTextEditor.js
Labels: enhancement

#4387 Optimize order of fields in entity view pages by relevance
  anet-dictionary.yml
  client/src/components/GeoLocation.js
  client/src/components/previews/LocationPreview.js
  client/src/components/previews/OrganizationPreview.js
  client/src/components/previews/PositionPreview.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/geoUtils.js
  client/src/models/Location.js
  client/src/pages/locations/Form.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Form.js
  client/src/pages/organizations/Show.js
  client/src/pages/positions/Form.js
  client/src/pages/positions/Show.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/src/utils.js
  client/tests/webdriver/baseSpecs/createNewTask.spec.js
  client/tests/webdriver/pages/showTask.page.js
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4447 Delete attachments when deleting report
  src/main/java/mil/dds/anet/database/AttachmentDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: improvement
