Repository NCI-Agency/anet, pull requests merged in 2023-04, with the labels that each got.

#4316 Prevent accidental delete of avatar
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/database/PersonDao.java
Labels: improvement

#4321 Fix e2e test related to report validation
  client/tests/e2e/report.js
Labels: DevOps

#4320 Add explicit dependency on graphql-java
  .github/renovate.json
  build.gradle
Labels: improvement

#4326 Upgrade to Storybook v7
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/yarn.lock
Labels: devDependencies

#4342 Fix assessment saving problem with filtered-out questions
  anet-dictionary.yml
  client/src/components/Model.js
  client/src/components/assessments/ondemand/OndemandAssessment.js
  client/src/components/assessments/ondemand/ValidationBar.js
  client/src/components/assessments/periodic/PeriodicAssessmentResults.js
  client/src/components/assessments/periodic/PeriodicAssessmentResultsTable.js
  client/src/models/Report.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  testDictionaries/no-custom-fields.yml
Labels: bug

#4341 Use BrowserStack API to set Selenium test title and result
  client/tests/util/test.js
Labels: DevOps

#4343 Allow any task as a parent
  anet-dictionary.yml
  client/src/pages/tasks/Form.js
Labels: improvement
