Repository NCI-Agency/anet, pull requests merged in 2024-06, with the labels that each got.

#4803 Update the JSON aggregation function to also handle empty values
  src/main/resources/migrations.xml
Labels: improvement

#4816 Fix cancelledReason selection in report form
  client/src/pages/reports/Form.js
Labels: bug

#4819 Add the Sim to the GitHub Actions workflow
  .github/workflows/build-gradle.yml
  client/tests/sim/Simulator.js
Labels: debt

#4821 Remove remaining traces of Internet Explorer
  .github/ISSUE_TEMPLATE/bug_report.md
  client/config/polyfills.js
  client/config/wdio.config.ie.js
  client/package.json
  client/src/components/AdvisorReports/FilterableAdvisorReportsTable.js
  client/src/components/BlueprintOverrides.css
  client/tests/util/wdio.ie.js
  client/tests/webdriver/ie/ie11RetiredBanner.spec.js
Labels: debt

#4828 Remove zoom on hovering over attachment preview image
  client/src/components/Attachment/Attachment.css
  client/src/components/Attachment/AttachmentImage.js
Labels: improvement

#4825 Display correct classification in report print view footer
  client/src/components/Compact.js
  client/src/components/SecurityBanner.js
  client/src/pages/reports/Compact.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
Labels: improvement

#4829 Update entity links after merge
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/beans/MergedEntity.java
  src/main/java/mil/dds/anet/database/AdminDao.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/mappers/MergedEntityMapper.java
  src/main/java/mil/dds/anet/threads/MergedEntityWorker.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/integration/db/MergedEntityWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: enhancement

#4786 Add a new custom field type geo_location
  anet-dictionary.yml
  client/src/components/CustomFields.js
  client/src/components/GeoLocation.js
  client/src/components/Model.js
  client/tests/jest/models/geoLocation.test.js
  client/tests/webdriver/customFieldsSpecs/createReport.spec.js
  client/tests/webdriver/pages/createReport.page.js
  insertBaseData-psql.sql
  src/main/resources/anet-schema.yml
Labels: enhancement

#4818 Allow admins to edit attachments on all reports incl. published
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
Labels: bug

#4833 Replace deprecated querystring with modern URLSearchParams
  client/package.json
  client/src/components/Model.js
  client/src/pages/organizations/New.js
  client/src/pages/positions/New.js
  client/src/pages/tasks/New.js
  client/src/utils.js
  client/tests/util/test.js
  client/yarn.lock
Labels: debt

#4834 Remove obsolete postcss-flexbugs-fixes
  client/package.json
  client/postcss.config.js
  client/yarn.lock
Labels: debt

#4835 Remove unnecessary direct dependency on dagre package
  client/package.json
  client/yarn.lock
Labels: debt

#4836 Update Babel and ESLint configurations
  client/.eslintrc.js
  client/babel.config.js
  client/config/webpack.common.js
  client/package.json
  client/src/components/AdvancedSearch.js
  client/tests/sim/Simulator.js
  client/yarn.lock
Labels: debt

#4838 Fix attachmentRelatedObject deselection and ANET link deselection
  client/src/components/editor/LinkSourceAnet.js
  client/src/pages/attachments/Form.js
Labels: improvement

#4795 Simplify dictionary for tasks
  anet-dictionary.yml
  client/src/components/NoPaginationTaskTable.js
  client/src/components/ReportStatistics.js
  client/src/components/ReportSummary.js
  client/src/components/ReportsByTask.js
  client/src/components/aggregations/utils.js
  client/src/components/previews/ReportPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/models/Report.js
  client/src/models/Task.js
  client/src/pages/HopscotchTour.js
  client/src/pages/insights/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/e2e/report.js
  client/tests/webdriver/baseSpecs/advancedSearch.spec.js
  client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
  client/tests/webdriver/baseSpecs/createNewTask.spec.js
  client/tests/webdriver/baseSpecs/myReports.spec.js
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/customFieldsSpecs/pendingAssessments.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/report/createReport.page.js
  client/tests/webdriver/pages/showTask.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/main/resources/anet-schema.yml
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/rollup.ftlh
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4815 Add option to make tasks selectable
  anet-dictionary.yml
  client/src/components/SearchFilters.js
  client/src/components/previews/TaskPreview.js
  client/src/models/Task.js
  client/src/pages/reports/Form.js
  client/src/pages/tasks/Edit.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Task.java
  src/main/java/mil/dds/anet/beans/search/TaskSearchQuery.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/database/mappers/TaskMapper.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/resources/anet.graphql
  src/test/resources/graphQLTests/taskShow.gql
  testDictionaries/no-custom-fields.yml
Labels: improvement
