Repository NCI-Agency/anet, pull requests merged in 2024-12, with the labels that each got.

#5005 Fix date input styling
  client/src/BlueprintOverrides.css
  client/src/index.css
Labels: bug

#5006 Preserve case of the last name when creating or editing a user
  anet-dictionary.yml
  client/src/components/NameInput.css
  client/src/components/SecurityBanner.tsx
  client/src/components/previews/PersonPreview.tsx
  client/src/models/Person.ts
  client/src/pages/people/Edit.tsx
  client/src/pages/people/Show.tsx
  client/tests/e2e/position.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/baseSpecs/showPerson.spec.js
  docs/INSTALL.md
  insertBaseData-psql.sql
  src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AuthorizationGroupResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SubscriptionTestHelper.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5014 Use Spring dependency management plugin
  build.gradle
  client/src/api.ts
  src/main/java/mil/dds/anet/resources/LoggingResource.java
Labels: debt

#5017 Display rollup reports and insights based on their engagement date rather than their publication date
  client/src/pages/insights/Show.tsx
  client/src/pages/rollup/Show.tsx
Labels: improvement

#5025 Don't allow additional properties on classification and fileTypes
  src/main/resources/anet-schema.yml
Labels: debt

#5023 Preserve case of last name when onboarding a new user
  client/tests/webdriver/baseSpecs/onboardNewUser.spec.js
  src/main/java/mil/dds/anet/utils/SecurityUtils.java
Labels: improvement

#5027 Check active domain names for email dialogs
  client/src/utils.tsx
  client/tests/webdriver/baseSpecs/sendRollupEmail.spec.js
  client/tests/webdriver/pages/rollup.page.js
Labels: improvement
