Repository NCI-Agency/anet, pull requests merged in 2024-03, with the labels that each got.

#4687 Allow all users to access the Insights menu
  client/src/components/Nav.js
  client/src/pages/insights/Show.js
  client/tests/webdriver/baseSpecs/insights.spec.js
  client/tests/webdriver/pages/insights.page.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
Labels: improvement

#4679 Ability to select advisors or interlocutors names in calendar
  anet-dictionary.yml
  client/src/components/ReportCalendar.js
  client/src/components/ReportCollection.js
  client/src/components/aggregations/utils.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4690 Be able to set a security classification for an engagement report
  anet-dictionary.yml
  client/src/components/Compact.js
  client/src/components/SecurityBanner.js
  client/src/components/previews/AttachmentPreview.js
  client/src/components/previews/ReportPreview.js
  client/src/models/Attachment.js
  client/src/models/Report.js
  client/src/pages/attachments/Form.js
  client/src/pages/attachments/Show.js
  client/src/pages/reports/Compact.js
  client/src/pages/reports/Edit.js
  client/src/pages/reports/Form.js
  client/src/pages/reports/Show.js
  client/stories/0-general/attachments.stories.mdx
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/ReportMapper.java
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/utils/ResourceUtils.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/utils/ResourceUtilsTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4698 Update core dependencies
  .github/renovate.json
  build.gradle
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/resources/anet.graphql
Labels: dependencies

#4696 Be able to add location in engagement report
  anet-dictionary.yml
  client/src/components/GeoLocation.js
  client/src/components/advancedSelectWidget/AdvancedSelect.js
  client/src/components/advancedSelectWidget/AdvancedSingleSelect.js
  client/src/pages/locations/Form.js
  client/src/pages/reports/Form.js
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4712 Upgrade to Yarn Berry
  client/.gitignore
  client/.yarn/releases/yarn-4.1.1.cjs
  client/.yarnrc.yml
  client/package.json
  client/yarn.lock
Labels: debt, devDependencies

#4716 Allow SVG attachment MIME-types
  anet-dictionary.yml
  testDictionaries/no-custom-fields.yml
Labels: internal
