Repository NCI-Agency/anet, pull requests merged in 2024-01, with the labels that each got.

#4610 Improve MIME type checks
  src/main/java/mil/dds/anet/database/AttachmentDao.java
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
Labels: improvement

#4594 Add option to render enums as select dropdown
  anet-dictionary.yml
  client/src/components/FieldHelper.js
  src/main/resources/anet-schema.yml
Labels: improvement

#4584 Make attending authors and primary attendees configurable
  anet-dictionary.yml
  client/src/models/Report.js
  client/src/pages/reports/Form.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4600 Add dictionary settings to make report approval workflow optional
  anet-dictionary.yml
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4602 Fix modal dialogs with large contents
  client/src/components/RelatedObjectNoteModal.js
  client/src/components/assessments/AssessmentModal.js
  client/src/index.css
Labels: improvement

#4611 Allow links in the rich-text editor to be updated
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/editor/LinkSourceAnet.js
  client/src/components/editor/Toolbar.js
Labels: improvement

#4624 Restrict access for unverified accounts
  anet-dictionary.yml
  client/src/components/EditHistory.js
  client/src/components/Nav.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/pages/App.js
  client/src/pages/Home.js
  client/src/pages/Routing.js
  client/src/pages/admin/UsersPendingVerification.js
  client/src/pages/onboarding/Edit.js
  client/src/pages/onboarding/New.js
  client/src/pages/onboarding/Show.js
  client/src/pages/people/Form.js
  client/src/pages/reports/Form.js
  client/tests/webdriver/baseSpecs/newUserUtils.js
  client/tests/webdriver/baseSpecs/onboardNewUser.spec.js
  client/tests/webdriver/pages/onboard.page.js
  src/main/java/mil/dds/anet/AnetApplication.java
  src/main/java/mil/dds/anet/beans/AdminSetting.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/graphql/AllowUnverifiedUsers.java
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/resources/GraphQlResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#4575 Allow admins to edit published reports
  client/src/pages/reports/Show.js
  src/main/java/mil/dds/anet/resources/ReportResource.java
Labels: improvement

#4629 Show past and planned engagements separately in the Daily Rollup
  client/src/components/DailyRollupChart.js
  client/src/pages/rollup/Show.js
Labels: improvement

#4641 Update Storybook cross-references
  client/stories/0-general/1-userRoles.stories.mdx
  client/stories/1-user/principalsYouAdvise.stories.mdx
  client/stories/3-admin/authorizationGroups.stories.mdx
Labels: internal, documentation, improvement

#4644 Document report / engagement approval process
  client/stories/1-user/draftEngagement.stories.mdx
  client/stories/1-user/subscriptions.stories.mdx
  client/stories/2-superuser/editing.stories.mdx
  client/stories/3-admin/1-approval-chains.stories.mdx
  client/stories/3-admin/2-defaultApprovalOrganization.stories.mdx
  client/stories/3-admin/4-authorizationGroups.stories.mdx
  client/stories/assets/approvalFlowDiagram.png
  client/stories/assets/approvalFlowDiagram.svg
Labels: documentation

#4646 See icon in reports with attachments
  client/src/components/ReportSummary.js
  client/src/components/ReportTable.js
  client/tests/webdriver/baseSpecs/myReports.spec.js
  client/tests/webdriver/pages/myReports.page.js
  client/tests/webdriver/pages/report/myReports.page.js
Labels: improvement

#4640 Add administrative positions to authorization groups
  client/src/components/Attachment/AttachmentRelatedObjectsTable.js
  client/src/components/Nav.js
  client/src/components/RelatedObjectsTable.js
  client/src/models/AuthorizationGroup.js
  client/src/pages/App.js
  client/src/pages/Routing.js
  client/src/pages/admin/authorizationgroup/Edit.js
  client/src/pages/admin/authorizationgroup/Form.js
  client/src/pages/admin/authorizationgroup/MyAuthorizationGroups.js
  client/src/pages/admin/authorizationgroup/Show.js
  client/stories/2-superuser/authorizationGroups.stories.mdx
  client/stories/3-admin/4-authorizationGroups.stories.mdx
  client/tests/webdriver/baseSpecs/createAuthorizationGroup.spec.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AuthorizationGroupResourceTest.java
  src/test/resources/anet.graphql
Labels: enhancement

#4643 Add search for authorization groups
  anet-dictionary.yml
  client/src/actions/index.js
  client/src/components/AuthorizationGroupTable.js
  client/src/components/LocationTable.js
  client/src/components/Model.js
  client/src/components/MySubscriptionUpdates.js
  client/src/components/MySubscriptions.js
  client/src/components/Nav.js
  client/src/components/SearchFilters.js
  client/src/components/advancedSelectWidget/MultiTypeAdvancedSelectComponent.js
  client/src/components/previews/AuthorizationGroupPreview.js
  client/src/models/AuthorizationGroup.js
  client/src/pages/Routing.js
  client/src/pages/admin/AuthorizationGroupTable.js
  client/src/pages/admin/AuthorizationGroups.js
  client/src/pages/authorizationGroups/Edit.js
  client/src/pages/authorizationGroups/Form.js
  client/src/pages/authorizationGroups/MyAuthorizationGroups.js
  client/src/pages/authorizationGroups/New.js
  client/src/pages/authorizationGroups/Show.js
  client/src/pages/reports/AuthorizationGroupTable.js
  client/src/pages/reports/Form.js
  client/src/pages/searches/Search.js
  client/src/resources/authorizationGroups.png
  client/src/resources/search-alt.png
  client/stories/1-user/subscriptions.stories.mdx
  client/stories/3-admin/4-authorizationGroups.stories.mdx
  client/tests/webdriver/baseSpecs/advancedSearch.spec.js
  client/tests/webdriver/baseSpecs/createAuthorizationGroup.spec.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/AuthorizationGroup.java
  src/main/java/mil/dds/anet/beans/search/AuthorizationGroupSearchQuery.java
  src/main/java/mil/dds/anet/database/AnetSubscribableObjectDao.java
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/search/AbstractAuthorizationGroupSearcher.java
  src/main/java/mil/dds/anet/views/AbstractCustomizableAnetBean.java
  src/main/java/mil/dds/anet/views/AbstractSubscribableAnetBean.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/AuthorizationGroupResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SubscriptionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/SubscriptionUpdateResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: enhancement
