Repository NCI-Agency/anet, pull requests merged in 2024-07, with the labels that each got.

#4850 Remove unneeded Apache Commons dependencies
  build.gradle
Labels: debt

#4823 Migrate custom report field "securityMarkings" to standard "classification"
  src/main/resources/migrations.xml
Labels: internal

#4851 Move dictionary keys to more logical place
  anet-dictionary.yml
  client/src/components/EditAdministratingPositionsModal.js
  client/src/components/EditOrganizationsAdministratedModal.js
  client/src/models/Location.js
  client/src/models/Position.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/organizations/Show.js
  client/src/pages/positions/Show.js
  src/main/resources/anet-schema.yml
  testDictionaries/no-custom-fields.yml
Labels: improvement

#4855 Allow users to upload multiple attachments in one go
  client/src/components/Attachment/UploadAttachment.js
Labels: improvement

#4854 Show organizations and positions at a location
  client/src/components/EditAdministratingPositionsModal.js
  client/src/components/OrganizationTable.js
  client/src/components/PositionTable.js
  client/src/components/previews/AuthorizationGroupPreview.js
  client/src/components/previews/TaskPreview.js
  client/src/pages/authorizationGroups/Form.js
  client/src/pages/authorizationGroups/Show.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Laydown.js
  client/src/pages/positions/MyCounterparts.js
  client/src/pages/searches/Search.js
  client/src/pages/tasks/Form.js
  client/src/pages/tasks/Show.js
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/pages/location/showLocation.page.js
  insertBaseData-psql.sql
Labels: improvement

#4796 Add admin function to merge two organizations
  client/package.json
  client/platform/node/settings.js
  client/src/components/ApprovalSteps.js
  client/src/components/AssociatedPositions.js
  client/src/components/Checkbox.js
  client/src/components/EditAssociatedPositions.js
  client/src/components/EditHistory.js
  client/src/components/MergeField.js
  client/src/components/Nav.js
  client/src/components/PositionTable.js
  client/src/components/RichTextEditor.js
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayRow.js
  client/src/mergeUtils.js
  client/src/models/Organization.js
  client/src/models/Person.js
  client/src/pages/Routing.js
  client/src/pages/admin/merge/MergeLocations.js
  client/src/pages/admin/merge/MergeOrganizations.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/positions/PreviousPeople.js
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/mergeOrganizations.spec.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
  client/tests/webdriver/pages/mergeLocations.page.js
  client/tests/webdriver/pages/mergeOrganizations.page.js
  client/tests/webdriver/pages/mergePeople.page.js
  client/tests/webdriver/pages/mergePositions.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/merge/OrganizationMergeTest.java
  src/test/resources/anet.graphql
Labels: enhancement

#4860 Fix setting person avatar
  client/src/components/Attachment/UploadAttachment.js
  client/src/pages/people/Form.js
Labels: improvement

#4871 Remove markdown gradle plugin
  build.gradle
Labels: debt

#4856 Add merge buttons to the show pages for mergeable objects
  client/src/components/Model.js
  client/src/models/Location.js
  client/src/models/Person.js
  client/src/pages/admin/merge/MergeLocations.js
  client/src/pages/admin/merge/MergeOrganizations.js
  client/src/pages/admin/merge/MergePeople.js
  client/src/pages/admin/merge/MergePositions.js
  client/src/pages/locations/Show.js
  client/src/pages/organizations/Show.js
  client/src/pages/people/Show.js
  client/src/pages/positions/Show.js
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/baseSpecs/showOrganization.spec.js
  client/tests/webdriver/baseSpecs/showPerson.spec.js
  client/tests/webdriver/baseSpecs/showPosition.spec.js
  client/tests/webdriver/pages/location/showLocation.page.js
  client/tests/webdriver/pages/page.js
  client/tests/webdriver/pages/showOrganization.page.js
  client/tests/webdriver/pages/showPerson.page.js
  client/tests/webdriver/pages/showPosition.page.js
Labels: improvement
