Repository NCI-Agency/anet, pull requests merged in 2025-04, with the labels that each got.

#5130 Implement a MART report importer
  anet-dictionary.yml
  application.yml
  build.gradle
  client/src/components/Nav.tsx
  client/src/pages/Routing.tsx
  client/src/pages/admin/martImportedReports/Show.tsx
  client/tests/webdriver/baseSpecs/showMartImportedReports.spec.js
  client/tests/webdriver/pages/showMartImportedReports.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/mart/LogDto.java
  src/main/java/mil/dds/anet/beans/mart/MartImportedReport.java
  src/main/java/mil/dds/anet/beans/mart/ReportDto.java
  src/main/java/mil/dds/anet/config/AnetConfig.java
  src/main/java/mil/dds/anet/config/GraphQLConfig.java
  src/main/java/mil/dds/anet/database/MartImportedReportDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/mappers/MartImportedReportMapper.java
  src/main/java/mil/dds/anet/resources/MartImportedReportsResource.java
  src/main/java/mil/dds/anet/threads/mart/MartImporterWorker.java
  src/main/java/mil/dds/anet/threads/mart/services/EwsReceiver.java
  src/main/java/mil/dds/anet/threads/mart/services/ExchangeServiceFactory.java
  src/main/java/mil/dds/anet/threads/mart/services/IMailReceiver.java
  src/main/java/mil/dds/anet/threads/mart/services/IMartReportImporterService.java
  src/main/java/mil/dds/anet/threads/mart/services/IMartTransmissionLogImporterService.java
  src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
  src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
  src/main/java/mil/dds/anet/threads/mart/services/TrustEveryoneExchangeService.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/integration/mart/MartReportImporterWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/MartImportedReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/RestrictedFieldsTest.java
  src/test/resources/anet.graphql
  src/test/resources/integration/anet-integrationtest.yml
  testDictionaries/no-custom-fields.yml
Labels: feature

#5140 Fix reportRejection mail template
  src/main/resources/emails/reportRejection.ftlh
  src/test/java/mil/dds/anet/test/integration/emails/EmailTemplateTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
Labels: bug

#5118 Add Content Security Policy and Referrer Policy headers, and sanitize SVG uploads
  anet-dictionary.yml
  build.gradle
  client/config/webpack.client.dev.js
  client/platform/web-dev/settings.js
  client/platform/web-dev/version.js
  client/platform/web/settings.js
  client/platform/web/version.js
  client/public/index.hbs
  client/src/components/Leaflet.tsx
  client/src/resources/leaflet/marker-icon-search.svg
  src/main/java/mil/dds/anet/config/ContentSecurityPolicy.java
  src/main/java/mil/dds/anet/config/SecurityConfig.java
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
  src/main/java/mil/dds/anet/resources/HomeResource.java
  src/main/java/mil/dds/anet/utils/ResponseUtils.java
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5145 Add MART dictionary export to ANET admin GUI
  anet-dictionary.yml
  client/src/components/Nav.tsx
  client/src/pages/Routing.tsx
  client/src/pages/admin/martImportedReports/Show.tsx
  client/src/pages/admin/martImporter/Show.tsx
  client/tests/webdriver/baseSpecs/showAllTasks.spec.js
  client/tests/webdriver/baseSpecs/showMartImportedReports.spec.js
  client/tests/webdriver/pages/showMartImportedReports.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/resources/AdminResource.java
  src/main/java/mil/dds/anet/services/EwsReceiver.java
  src/main/java/mil/dds/anet/services/ExchangeServiceFactory.java
  src/main/java/mil/dds/anet/services/IMailReceiver.java
  src/main/java/mil/dds/anet/services/IMartDictionaryService.java
  src/main/java/mil/dds/anet/services/IMartReportImporterService.java
  src/main/java/mil/dds/anet/services/IMartTransmissionLogImporterService.java
  src/main/java/mil/dds/anet/services/MartDictionaryService.java
  src/main/java/mil/dds/anet/services/MartReportImporterService.java
  src/main/java/mil/dds/anet/services/MartTransmissionLogImporterService.java
  src/main/java/mil/dds/anet/services/TrustEveryoneExchangeService.java
  src/main/java/mil/dds/anet/threads/mart/MartImporterWorker.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/integration/mart/MartDictionaryServiceTest.java
  src/test/java/mil/dds/anet/test/integration/mart/MartReportImporterWorkerTest.java
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5152 Update dependency com.google.guava:guava to v33.4.7-jre
  build.gradle
Labels: dependencies

#5159 Prevent cropping when editing an existing SVG avatar
  client/src/components/avatar/EntityAvatarEditModal.tsx
Labels: bug, internal

#5161 Improve key outcomes and next steps
  client/src/components/ListItems.tsx
  client/src/components/previews/ReportPreview.tsx
  client/src/pages/reports/Compact.tsx
Labels: internal, improvement
