Repository NCI-Agency/anet, pull requests merged in 2025-09, with the labels that each got.

#5286 Add a new locations layer to the map
  client/src/components/Leaflet.tsx
  client/src/components/aggregations/EventsMapWidget.tsx
  client/src/components/aggregations/ReportsMapWidget.tsx
  client/src/index.css
  client/src/resources/leaflet/marker-icon-light-2x.png
  client/src/resources/leaflet/marker-icon-light.png
  src/main/java/mil/dds/anet/beans/search/BoundingBox.java
  src/main/java/mil/dds/anet/beans/search/LocationSearchQuery.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/test/resources/anet.graphql
Labels: enhancement

#5308 Handle unrecognized pendingEmails
  src/main/java/mil/dds/anet/database/mappers/AnetEmailMapper.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: bug

#5306 Improve error handling in MART dictionary export
  client/src/pages/admin/martImporter/Show.tsx
  src/main/java/mil/dds/anet/resources/AdminResource.java
Labels: improvement

#5317 Update to chai v6
  .github/renovate.json
  client/babel.config.cjs
  client/jest.config.cjs
  client/package.json
  client/yarn.lock
Labels: devDependencies

#5266 Hide inactive tasks
  client/src/components/TaskTree.tsx
  client/src/index.css
  client/src/models/Task.ts
  client/src/pages/tasks/Edit.tsx
  client/src/pages/tasks/Form.tsx
  client/src/pages/tasks/InactiveTaskModal.tsx
  client/src/pages/tasks/Top.tsx
  client/tests/webdriver/baseSpecs/searchFilters/taskFilter.spec.js
  client/tests/webdriver/baseSpecs/showAllTasks.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
Labels: improvement

#5305 Improve compact person view
  anet-dictionary.yml
  client/src/components/Compact.tsx
  client/src/components/CustomFields.tsx
  client/src/components/DictionaryField.tsx
  client/src/components/FieldHelper.tsx
  client/src/components/RichTextEditor.tsx
  client/src/pages/people/Compact.tsx
  client/src/utils.tsx
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5316 Add search option to exclude reports with specific tasks
  client/src/components/SearchFilters.tsx
  src/main/java/mil/dds/anet/beans/search/RecursiveFkBatchParams.java
  src/main/java/mil/dds/anet/beans/search/RecursiveM2mBatchParams.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/search/AbstractEventSearcher.java
  src/main/java/mil/dds/anet/search/AbstractEventSeriesSearcher.java
  src/main/java/mil/dds/anet/search/AbstractLocationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractOrganizationSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPersonSearcher.java
  src/main/java/mil/dds/anet/search/AbstractPositionSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/main/java/mil/dds/anet/ws/Nvg20WebService.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/resources/anet.graphql
Labels: improvement

#5324 Update APP-6 symbology for NVG
  src/main/java/mil/dds/anet/ws/Nvg20WebService.java
Labels: improvement
