Repository NCI-Agency/anet, pull requests merged in 2025-03, with the labels that each got.

#5096 Fix database connection leak
  build.gradle
  src/main/resources/application.yml
Labels: bug, internal

#5095 Add attachments and avatars to events/event series
  anet-dictionary.yml
  client/src/components/EventSeriesTable.tsx
  client/src/components/EventSummary.tsx
  client/src/components/EventTable.tsx
  client/src/components/avatar/EntityAvatarComponent.css
  client/src/components/avatar/EntityAvatarDisplay.tsx
  client/src/components/avatar/EntityAvatarEditModal.tsx
  client/src/components/previews/EventPreview.tsx
  client/src/components/previews/EventSeriesPreview.tsx
  client/src/models/Event.ts
  client/src/models/EventSeries.ts
  client/src/pages/eventSeries/Form.tsx
  client/src/pages/eventSeries/Show.tsx
  client/src/pages/events/Form.tsx
  client/src/pages/events/Show.tsx
  client/src/pages/organizations/Show.tsx
  client/src/pages/people/Show.tsx
  client/src/pages/searches/Search.tsx
  client/src/resources/authorizationGroups.png
  client/src/resources/default-event-avatar.svg
  client/src/resources/default-eventSeries-avatar.svg
  client/tests/webdriver/baseSpecs/myAttachments.spec.js
  client/tests/webdriver/baseSpecs/showEvent.spec.js
  client/tests/webdriver/baseSpecs/showEventSeries.spec.js
  client/tests/webdriver/pages/showEvent.page.js
  client/tests/webdriver/pages/showEventSeries.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Event.java
  src/main/java/mil/dds/anet/beans/EventSeries.java
  src/main/java/mil/dds/anet/resources/AttachmentResource.java
  src/main/java/mil/dds/anet/resources/EntityAvatarResource.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5099 Add date and time to engagement popup on geo-map
  client/src/components/aggregations/ReportsMapWidget.tsx
Labels: improvement

#5110 Add context to event and event series calendar
  client/src/components/EventCalendar.tsx
  client/src/components/EventCollection.tsx
  client/src/components/ReportCalendar.tsx
  client/src/components/ReportCollection.tsx
  client/src/components/aggregations/utils.tsx
  client/src/pages/events/Show.tsx
  insertBaseData-psql.sql
Labels: improvement

#5117 Update Spotless Java config
  config/eclipse-java-google-style.xml
  src/main/java/mil/dds/anet/beans/ConfidentialityRecord.java
  src/main/java/mil/dds/anet/beans/MergedEntity.java
  src/main/java/mil/dds/anet/beans/search/AssessmentSearchQuery.java
  src/main/java/mil/dds/anet/threads/MergedEntityWorker.java
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
Labels: debt

#5107 Use ISO 8601 dates
  anet-dictionary.yml
  client/src/components/AdvisorReports/AdvisorReportsTableHead.tsx
  client/src/components/Calendar.tsx
  client/src/components/CustomDateInput.tsx
  client/src/components/ReportsByDayOfWeek.tsx
  client/src/pages/admin/useractivities/UserActivitiesOverTime.tsx
  client/src/pages/admin/useractivities/UserActivitiesPerPeriod.tsx
  client/src/periodUtils.tsx
  src/main/java/mil/dds/anet/beans/Report.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlReportSearcher.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
  src/main/java/mil/dds/anet/utils/PendingAssessmentsHelper.java
  src/main/java/mil/dds/anet/utils/Utils.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/integration/db/PendingAssessmentsNotificationWorkerTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5119 Update graphql-java-generator to v2.9
  build.gradle
Labels: devDependencies

#5105 Implement extra organization privileges for superusers
  anet-dictionary.yml
  client/src/components/CreateButton.tsx
  client/src/components/previews/PersonPreview.tsx
  client/src/components/previews/PositionPreview.tsx
  client/src/models/Person.ts
  client/src/models/Position.ts
  client/src/pages/App.tsx
  client/src/pages/eventSeries/Form.tsx
  client/src/pages/events/Form.tsx
  client/src/pages/organizations/Form.tsx
  client/src/pages/positions/Edit.tsx
  client/src/pages/positions/Form.tsx
  client/src/pages/positions/Show.tsx
  client/tests/e2e/permissions.js
  client/tests/e2e/report.js
  client/tests/webdriver/pages/report/createReport.page.js
  insertBaseData-psql.sql
  keycloak/import/ANET-realm.json
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/mappers/PositionMapper.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/utils/AuthUtils.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/RestrictedFieldsTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5098 Improve organization diagram
  client/package.json
  client/src/components/graphs/OrganizationalChart.tsx
  client/src/pages/organizations/Laydown.tsx
  client/src/pages/organizations/Show.tsx
  client/tests/sim/stories/OrganizationStories.js
  client/yarn.lock
Labels: improvement

#5121 Be able to change approval steps in view mode
  client/src/components/ApprovalSteps.tsx
  client/src/components/RemoveButton.tsx
  client/src/components/approvals/ApprovalSteps.tsx
  client/src/components/approvals/Approvals.tsx
  client/src/components/approvals/ApprovalsDefinition.tsx
  client/src/components/approvals/EditApprovalsModal.tsx
  client/src/index.css
  client/src/pages/admin/merge/MergeLocations.tsx
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/locations/Show.tsx
  client/src/pages/organizations/Show.tsx
  client/src/pages/tasks/Show.tsx
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/baseSpecs/showOrganization.spec.js
  client/tests/webdriver/customFieldsSpecs/showTask.spec.js
  client/tests/webdriver/pages/location/showLocation.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  client/tests/webdriver/pages/showTask.page.js
Labels: improvement

#5132 Allow advanced search for multiple tasks
  client/src/components/SearchFilters.tsx
  client/src/components/TaskTable.tsx
  client/src/components/advancedSearch/TaskFilter.tsx
  src/main/java/mil/dds/anet/beans/search/EventSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
  src/main/java/mil/dds/anet/search/AbstractEventSearcher.java
  src/main/java/mil/dds/anet/search/AbstractReportSearcher.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/resources/anet.graphql
Labels: improvement

#5135 Add the EventMatrix to the tasks overview page
  client/src/components/EventMatrix.tsx
  client/src/index.css
  client/src/pages/reports/Form.tsx
  client/src/pages/tasks/Top.tsx
  client/tests/webdriver/baseSpecs/showAllTasks.spec.js
  client/tests/webdriver/pages/showAllTasks.page.js
Labels: improvement
