Repository NCI-Agency/anet, pull requests merged in 2025-02, with the labels that each got.

#5054 Make mail timeout configurable
  application.yml
  src/main/java/mil/dds/anet/config/AnetConfig.java
  src/main/java/mil/dds/anet/threads/AnetEmailWorker.java
Labels: improvement

#5053 Fix loop detection in object hierarchies
  client/src/utils.tsx
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/mergeOrganizations.spec.js
  client/tests/webdriver/pages/page.js
  src/main/java/mil/dds/anet/database/AuthorizationGroupDao.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/search/AbstractSearchQueryBuilder.java
  src/test/java/mil/dds/anet/test/resources/merge/LocationMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/OrganizationMergeTest.java
Labels: bug

#5086 Remove ProcessBoard
  anet-dictionary.yml
  client/package.json
  client/src/pages/Routing.tsx
  client/src/pages/dashboards/BoardDashboard.tsx
  client/src/pages/dashboards/DiagramNode.tsx
  client/yarn.lock
  data/dashboards/process.json
  testDictionaries/no-custom-fields.yml
Labels: debt

#5064 Improve print report view
  client/src/components/Compact.tsx
  client/src/components/CustomFields.tsx
  client/src/components/DictionaryField.tsx
  client/src/components/NoPositionBanner.tsx
  client/src/components/ReportWorkflow.css
  client/src/components/RichTextEditor.tsx
  client/src/components/SecurityBanner.tsx
  client/src/components/assessments/QuestionSet.tsx
  client/src/components/assessments/instant/InstantAssessmentsContainerField.tsx
  client/src/components/editor/LinkAnetEntity.tsx
  client/src/index.css
  client/src/pages/reports/Compact.tsx
  client/src/utils.tsx
  client/tests/webdriver/baseSpecs/printReport.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
Labels: improvement

#5048 Add hierarchical view of objectives
  anet-dictionary.yml
  client/src/components/Nav.tsx
  client/src/components/TaskTree.tsx
  client/src/pages/Routing.tsx
  client/src/pages/tasks/Top.tsx
  client/src/pages/util.ts
  client/tests/webdriver/baseSpecs/createNewTask.spec.js
  client/tests/webdriver/baseSpecs/showAllTasks.spec.js
  client/tests/webdriver/pages/createNewTask.page.js
  client/tests/webdriver/pages/showAllTasks.page.js
  src/main/java/mil/dds/anet/search/AbstractTaskSearcher.java
  src/main/resources/anet-schema.yml
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  testDictionaries/no-custom-fields.yml
Labels: enhancement

#5092 Remove PowerMock
  build.gradle
  src/test/java/mil/dds/anet/test/emails/AccountDeactivationWorkerTest.java
Labels: debt

#5093 Switch back to APP-6(D)
  client/src/components/graphs/OrganizationalChart.tsx
  src/main/java/mil/dds/anet/ws/Nvg20WebService.java
Labels: debt

#5077 Improve engagement report entity-link representation
  anet-dictionary.yml
  client/src/components/RichTextEditor.tsx
  client/src/utils.tsx
  client/tests/jest/utils/utils.test.ts
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5088 Make engagements shown on the map clickable
  client/src/components/aggregations/ReportsMapWidget.tsx
Labels: enhancement

#5071 Hide non-applicable assessments
  anet-dictionary.yml
  client/src/components/assessments/AssessmentResultsContainer.tsx
  client/tests/e2e/report.js
  client/tests/webdriver/baseSpecs/assessmentsForPeople.spec.js
  client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
  client/tests/webdriver/baseSpecs/createReportWithoutPrincipal.spec.js
  client/tests/webdriver/pages/advancedSearch.page.js
  client/tests/webdriver/pages/createAuthorizationGroup.page.js
  client/tests/webdriver/pages/createNewPerson.page.js
  client/tests/webdriver/pages/createNewTask.page.js
  client/tests/webdriver/pages/createReport.page.js
  client/tests/webdriver/pages/home.page.js
  client/tests/webdriver/pages/mergePositions.page.js
  client/tests/webdriver/pages/myCounterparts.page.js
  client/tests/webdriver/pages/myTasks.page.js
  client/tests/webdriver/pages/report/createReport.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/pages/search.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  client/tests/webdriver/pages/showPerson.page.js
  client/tests/webdriver/pages/showTask.page.js
  insertBaseData-psql.sql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5070 Edit attachments in view mode
  client/src/components/Attachment/Attachment.css
  client/src/components/Attachment/AttachmentsDetailView.tsx
  client/src/pages/locations/Show.tsx
  client/src/pages/organizations/Show.tsx
  client/src/pages/people/Show.tsx
  client/src/pages/reports/Show.tsx
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/baseSpecs/showOrganization.spec.js
  client/tests/webdriver/baseSpecs/showPerson.spec.js
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/pages/location/showLocation.page.js
  client/tests/webdriver/pages/report/showReport.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  client/tests/webdriver/pages/showPerson.page.js
Labels: enhancement

#5078 Better way of displaying key outcomes and next steps
  client/src/components/ListItems.tsx
  client/src/pages/reports/Show.tsx
  client/tests/webdriver/baseSpecs/showReport.spec.js
  client/tests/webdriver/pages/report/showReport.page.js
  insertBaseData-psql.sql
Labels: improvement
