Repository NCI-Agency/anet, pull requests merged in 2025-06, with the labels that each got.

#5160 Improve APP-06 symbology selection
  anet-dictionary.yml
  client/src/components/App6.ts
  client/src/components/App6Symbol.tsx
  client/src/components/App6SymbolPreview.tsx
  client/src/components/editor/EditApp6SymbolModal.tsx
  client/src/components/graphs/OrganizationalChart.tsx
  client/src/components/previews/OrganizationPreview.tsx
  client/src/models/Organization.ts
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/admin/merge/MergePeople.tsx
  client/src/pages/organizations/Edit.tsx
  client/src/pages/organizations/Form.tsx
  client/src/pages/organizations/Show.tsx
  client/tests/sim/stories/OrganizationStories.js
  client/tests/webdriver/baseSpecs/createNewOrganization.spec.js
  client/tests/webdriver/pages/createNewOrganization.page.js
  client/tests/webdriver/pages/showOrganization.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Organization.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/mappers/OrganizationMapper.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/resources/anet.graphql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5136 Display objective tree on search filter
  client/src/components/Checkbox.tsx
  client/src/components/SearchFilters.tsx
  client/src/components/advancedSearch/TaskFilter.tsx
  client/src/components/advancedSelectWidget/AdvancedSelect.tsx
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayTable.tsx
  client/src/index.css
Labels: improvement

#5181 Add avatars to locations
  client/src/components/EventSummary.tsx
  client/src/components/EventTable.tsx
  client/src/components/LocationTable.tsx
  client/src/components/Model.tsx
  client/src/components/MySubscriptionUpdates.tsx
  client/src/components/MySubscriptions.tsx
  client/src/components/OrganizationTable.tsx
  client/src/components/PendingAssessmentsByPosition.tsx
  client/src/components/PersonTable.tsx
  client/src/components/PositionTable.tsx
  client/src/components/ReportSummary.tsx
  client/src/components/ReportTable.tsx
  client/src/components/avatar/EntityAvatarDisplay.tsx
  client/src/components/previews/AuthorizationGroupPreview.tsx
  client/src/components/previews/LocationPreview.tsx
  client/src/components/previews/PositionPreview.tsx
  client/src/components/previews/ReportPreview.tsx
  client/src/components/previews/TaskPreview.tsx
  client/src/models/Event.ts
  client/src/models/Location.ts
  client/src/models/Organization.ts
  client/src/models/Person.ts
  client/src/models/Position.ts
  client/src/pages/App.tsx
  client/src/pages/admin/merge/MergeLocations.tsx
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/attachments/Edit.tsx
  client/src/pages/attachments/MyAttachments.tsx
  client/src/pages/attachments/Show.tsx
  client/src/pages/authorizationGroups/Edit.tsx
  client/src/pages/authorizationGroups/Show.tsx
  client/src/pages/dashboards/DecisivesDashboard.tsx
  client/src/pages/locations/Form.tsx
  client/src/pages/locations/Show.tsx
  client/src/pages/organizations/Show.tsx
  client/src/pages/reports/Compact.tsx
  client/src/pages/reports/Edit.tsx
  client/src/pages/reports/Form.tsx
  client/src/pages/reports/Show.tsx
  client/src/pages/searches/Search.tsx
  client/src/pages/tasks/Edit.tsx
  client/src/pages/tasks/Show.tsx
  client/src/resources/default-location-avatar.svg
  client/tests/webdriver/baseSpecs/showLocation.spec.js
  client/tests/webdriver/pages/location/showLocation.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Location.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/resources/EntityAvatarResource.java
  src/test/java/mil/dds/anet/test/resources/EntityAvatarResourceTest.java
  src/test/resources/anet.graphql
Labels: enhancement

#5182 Add avatars to positions
  client/src/components/Model.tsx
  client/src/components/MySubscriptionUpdates.tsx
  client/src/components/MySubscriptions.tsx
  client/src/components/PendingAssessmentsByPosition.tsx
  client/src/components/PersonTable.tsx
  client/src/components/PositionTable.tsx
  client/src/components/avatar/EntityAvatarDisplay.tsx
  client/src/components/previews/AuthorizationGroupPreview.tsx
  client/src/components/previews/OrganizationPreview.tsx
  client/src/components/previews/PersonPreview.tsx
  client/src/components/previews/PositionPreview.tsx
  client/src/components/previews/ReportPreview.tsx
  client/src/components/previews/TaskPreview.tsx
  client/src/models/Event.ts
  client/src/models/Person.ts
  client/src/models/Position.ts
  client/src/pages/App.tsx
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/admin/merge/MergePositions.tsx
  client/src/pages/attachments/Edit.tsx
  client/src/pages/attachments/MyAttachments.tsx
  client/src/pages/attachments/Show.tsx
  client/src/pages/authorizationGroups/Edit.tsx
  client/src/pages/authorizationGroups/MyAuthorizationGroups.tsx
  client/src/pages/authorizationGroups/Show.tsx
  client/src/pages/dashboards/DecisivesDashboard.tsx
  client/src/pages/organizations/Edit.tsx
  client/src/pages/organizations/Show.tsx
  client/src/pages/people/Compact.tsx
  client/src/pages/people/Show.tsx
  client/src/pages/positions/Edit.tsx
  client/src/pages/positions/Form.tsx
  client/src/pages/positions/Show.tsx
  client/src/pages/reports/Compact.tsx
  client/src/pages/reports/Edit.tsx
  client/src/pages/reports/Form.tsx
  client/src/pages/reports/Show.tsx
  client/src/pages/searches/Search.tsx
  client/src/pages/tasks/Edit.tsx
  client/src/pages/tasks/Show.tsx
  client/src/resources/default-position-avatar.svg
  client/tests/webdriver/baseSpecs/showPosition.spec.js
  client/tests/webdriver/pages/showPosition.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/beans/Position.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/resources/EntityAvatarResource.java
  src/test/java/mil/dds/anet/test/resources/EntityAvatarResourceTest.java
  src/test/resources/anet.graphql
Labels: enhancement

#5191 Add advanced select to filter MART imported reports on author
  client/src/components/advancedSelectWidget/AdvancedSelect.tsx
  client/src/pages/admin/martImporter/MartImportedReportTable.tsx
Labels: internal, improvement

#5156 Expose GraphQL as a web service
  client/src/pages/admin/accessTokens/Index.tsx
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/AccessToken.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/config/GraphQLConfig.java
  src/main/java/mil/dds/anet/config/SecurityConfig.java
  src/main/java/mil/dds/anet/database/AccessTokenDao.java
  src/main/java/mil/dds/anet/database/AssessmentDao.java
  src/main/java/mil/dds/anet/database/CustomSensitiveInformationDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/NoteDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/mappers/AccessTokenMapper.java
  src/main/java/mil/dds/anet/resources/GraphQLExecutor.java
  src/main/java/mil/dds/anet/threads/AbstractWorker.java
  src/main/java/mil/dds/anet/utils/DaoUtils.java
  src/main/java/mil/dds/anet/ws/AccessTokenPrincipal.java
  src/main/java/mil/dds/anet/ws/GraphQLWebService.java
  src/main/java/mil/dds/anet/ws/Nvg20WebService.java
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/TestData.java
  src/test/java/mil/dds/anet/test/resources/AccessTokenResourceTest.java
  src/test/java/mil/dds/anet/test/ws/GraphQLWebServiceTest.java
  src/test/resources/anet.graphql
Labels: feature

#5187 Show navigation warning when leaving any merge page
  client/src/components/MergeField.tsx
  client/src/pages/admin/merge/MergeLocations.tsx
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/admin/merge/MergePeople.tsx
  client/src/pages/admin/merge/MergePositions.tsx
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/mergeOrganizations.spec.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
Labels: improvement

#5171 Support polar coordinates in MGRS
  client/jest.config.js
  client/package.json
  client/src/geoUtils.ts
  client/tests/webdriver/baseSpecs/locationUtils.js
  client/yarn.lock
Labels: improvement

#5198 Prevent infinite loop on task filter
  client/src/components/advancedSearch/TaskFilter.tsx
  client/tests/webdriver/baseSpecs/searchFilters/taskFilter.spec.js
  client/tests/webdriver/pages/searchFilters/taskFilter.page.js
Labels: debt, internal

#5190 Prevent admins from picking identical objects for merging
  client/src/components/advancedSelectWidget/AdvancedSelect.tsx
  client/src/components/advancedSelectWidget/AdvancedSelectOverlayTable.tsx
  client/src/components/advancedSelectWidget/AdvancedSingleSelect.tsx
  client/src/pages/admin/merge/MergeLocations.tsx
  client/src/pages/admin/merge/MergeOrganizations.tsx
  client/src/pages/admin/merge/MergePeople.tsx
  client/src/pages/admin/merge/MergePositions.tsx
  client/tests/webdriver/baseSpecs/mergeLocations.spec.js
  client/tests/webdriver/baseSpecs/mergeOrganizations.spec.js
  client/tests/webdriver/baseSpecs/mergePeople.spec.js
  client/tests/webdriver/baseSpecs/mergePositions.spec.js
  client/tests/webdriver/pages/mergeLocations.page.js
  client/tests/webdriver/pages/mergeOrganizations.page.js
  client/tests/webdriver/pages/mergePeople.page.js
  client/tests/webdriver/pages/mergePositions.page.js
Labels: improvement

#5199 Support multiple domain usernames per user
  anet-dictionary.yml
  client/src/components/UserInputTable.tsx
  client/src/components/UserTable.tsx
  client/src/components/previews/PersonPreview.tsx
  client/src/models/Person.ts
  client/src/pages/admin/merge/MergePeople.tsx
  client/src/pages/onboarding/Show.tsx
  client/src/pages/people/Compact.tsx
  client/src/pages/people/Edit.tsx
  client/src/pages/people/Form.tsx
  client/src/pages/people/Show.tsx
  client/tests/e2e/permissions.js
  client/tests/sim/stories/PersonStories.js
  client/tests/sim/stories/PositionStories.js
  client/tests/sim/stories/afghanSurnames.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/User.java
  src/main/java/mil/dds/anet/commands/InitializationCommand.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/UserDao.java
  src/main/java/mil/dds/anet/database/mappers/PersonMapper.java
  src/main/java/mil/dds/anet/database/mappers/UserMapper.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/java/mil/dds/anet/utils/SecurityUtils.java
  src/main/java/mil/dds/anet/views/UserActivityFilter.java
  src/main/resources/anet-schema.yml
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/emails/AccountDeactivationWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/db/MergedEntityWorkerTest.java
  src/test/java/mil/dds/anet/test/integration/utils/TestBeans.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AdminResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AssessmentResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AttachmentResourceTest.java
  src/test/java/mil/dds/anet/test/resources/AuthorizationGroupResourceTest.java
  src/test/java/mil/dds/anet/test/resources/EntityAvatarResourceTest.java
  src/test/java/mil/dds/anet/test/resources/GraphQlResourceTest.java
  src/test/java/mil/dds/anet/test/resources/LocationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/MartImportedReportsResourceTest.java
  src/test/java/mil/dds/anet/test/resources/NoteResourceTest.java
  src/test/java/mil/dds/anet/test/resources/OrganizationResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
  src/test/java/mil/dds/anet/test/resources/ReportResourceTest.java
  src/test/java/mil/dds/anet/test/resources/RestrictedFieldsTest.java
  src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
  src/test/java/mil/dds/anet/test/resources/TaskResourceTest.java
  src/test/resources/anet.graphql
  src/test/resources/graphQLTests/person.gql
  testDictionaries/no-custom-fields.yml
Labels: improvement

#5185 Adjust spacings in organization diagram
  client/src/components/graphs/OrganizationalChart.tsx
Labels: improvement

#5202 Saved searches without name
  client/src/pages/searches/MySavedSearches.tsx
  client/src/pages/searches/Search.tsx
  src/main/java/mil/dds/anet/resources/SavedSearchResource.java
  src/main/resources/migrations.xml
Labels: improvement

#5203 Run all client-side tests in incognito mode
  client/config/browserstack.config.js
  client/config/wdio.config.js
  client/tests/util/test.js
Labels: debt, internal
