Repository NCI-Agency/anet, pull requests merged in 2025-10, with the labels that each got.

#5333 Address some lint warnings
  client/src/components/Checkbox.tsx
  client/src/components/FieldHelper.tsx
  client/src/pages/tasks/InactiveTaskModal.tsx
Labels: debt, internal

#5326 Update subscriptions and subscriptionUpdates when merging
  src/main/java/mil/dds/anet/database/AnetSubscribableObjectDao.java
  src/main/java/mil/dds/anet/database/LocationDao.java
  src/main/java/mil/dds/anet/database/OrganizationDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PositionDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/TaskDao.java
  src/main/java/mil/dds/anet/resources/AuthorizationGroupResource.java
  src/main/java/mil/dds/anet/resources/EventResource.java
  src/main/java/mil/dds/anet/resources/EventSeriesResource.java
  src/main/java/mil/dds/anet/resources/LocationResource.java
  src/main/java/mil/dds/anet/resources/OrganizationResource.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PositionResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/resources/TaskResource.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/merge/LocationMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/OrganizationMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PersonMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/PositionMergeTest.java
  src/test/java/mil/dds/anet/test/resources/merge/TaskMergeTest.java
Labels: bug

#5193 Introduce user preferences in ANET
  client/src/components/Nav.tsx
  client/src/components/preferences/ExportFieldsPanel.tsx
  client/src/components/preferences/PreferencesFieldSet.tsx
  client/src/components/preferences/UserPreferences.tsx
  client/src/exportUtils.ts
  client/src/pages/App.tsx
  client/src/pages/Routing.tsx
  client/src/pages/admin/preferences/Preferences.tsx
  client/src/pages/preferences/MyPreferences.tsx
  client/src/pages/searches/Search.tsx
  client/src/pages/util.ts
  client/src/utils.tsx
  client/tests/util/test.cjs
  client/tests/webdriver/baseSpecs/preferences.spec.js
  client/tests/webdriver/pages/preferences.page.js
  insertBaseData-psql.sql
  src/main/java/mil/dds/anet/AnetObjectEngine.java
  src/main/java/mil/dds/anet/beans/Person.java
  src/main/java/mil/dds/anet/beans/PersonPreference.java
  src/main/java/mil/dds/anet/beans/Preference.java
  src/main/java/mil/dds/anet/beans/search/PreferenceSearchQuery.java
  src/main/java/mil/dds/anet/beans/search/PreferenceSearchSortBy.java
  src/main/java/mil/dds/anet/config/GraphQLConfig.java
  src/main/java/mil/dds/anet/database/AnetBaseDao.java
  src/main/java/mil/dds/anet/database/PersonDao.java
  src/main/java/mil/dds/anet/database/PersonPreferenceDao.java
  src/main/java/mil/dds/anet/database/PreferenceDao.java
  src/main/java/mil/dds/anet/database/ReportDao.java
  src/main/java/mil/dds/anet/database/SubscriptionDao.java
  src/main/java/mil/dds/anet/database/SubscriptionUpdateGroup.java
  src/main/java/mil/dds/anet/database/mappers/PersonPreferenceMapper.java
  src/main/java/mil/dds/anet/database/mappers/PreferenceMapper.java
  src/main/java/mil/dds/anet/emails/DailyRollupEmail.java
  src/main/java/mil/dds/anet/emails/SubscriptionUpdateEmail.java
  src/main/java/mil/dds/anet/resources/PersonResource.java
  src/main/java/mil/dds/anet/resources/PreferencesResource.java
  src/main/java/mil/dds/anet/resources/ReportResource.java
  src/main/java/mil/dds/anet/search/AbstractPreferenceSearcher.java
  src/main/java/mil/dds/anet/search/IPreferenceSearcher.java
  src/main/java/mil/dds/anet/search/Searcher.java
  src/main/java/mil/dds/anet/search/pg/PostgresqlPreferenceSearcher.java
  src/main/java/mil/dds/anet/threads/FutureEngagementWorker.java
  src/main/java/mil/dds/anet/utils/BatchingUtils.java
  src/main/java/mil/dds/anet/utils/FkDataLoaderKey.java
  src/main/java/mil/dds/anet/utils/IdDataLoaderKey.java
  src/main/resources/emails/approvalNeeded.ftlh
  src/main/resources/emails/emailReport.ftlh
  src/main/resources/emails/futureEngagementUpdated.ftlh
  src/main/resources/emails/newReportComment.ftlh
  src/main/resources/emails/pendingAssessmentsNotification.ftlh
  src/main/resources/emails/reportEdited.ftlh
  src/main/resources/emails/reportPublished.ftlh
  src/main/resources/emails/reportRejection.ftlh
  src/main/resources/emails/rollup.ftlh
  src/main/resources/emails/subscriptionUpdate.ftlh
  src/main/resources/migrations.xml
  src/test/java/mil/dds/anet/test/integration/emails/EmailTemplateTest.java
  src/test/java/mil/dds/anet/test/resources/AbstractResourceTest.java
  src/test/java/mil/dds/anet/test/resources/PersonResourceTest.java
  src/test/resources/anet.graphql
Labels: feature
